import { db, modLogsTable } from "@workspace/db";
import { assertWipeUnlocked, getWipeLockState } from "./wipeLock.js";
import { resetAllLeaderboardStats } from "./leaderboardReset.js";

export type WipeKind = "map" | "general";
export type HostFile = { name: string; path: string; directory: string; size: number; group: "map" | "blueprints" };
export type WipeActor = { id: string; name: string };
export type WipeLifecycle = { onStopped?: () => Promise<void> | void };
export type DiagnosticFilePermission = { listing: boolean; write: boolean; delete: boolean; confirmed: boolean; probePath: string };

const panelUrl=()=>String(process.env.ELGAE_PANEL_URL||"").replace(/\/$/,"");
const serverId=()=>String(process.env.ELGAE_SERVER_ID||"").trim();
const apiKey=()=>String(process.env.ELGAE_API_KEY||"").trim();
const executionEnabled=()=>process.env.WIPE_EXECUTION_ENABLED==="true";
const automationEnabled=()=>process.env.WIPE_AUTOMATION_ENABLED==="true";

async function panelRequest(path:string,init:RequestInit={}):Promise<any>{
 if(!panelUrl()||!serverId()||!apiKey())throw new Error("Integração ElgaeHost incompleta no Railway.");
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);
 try{const response=await fetch(`${panelUrl()}/api/client/servers/${serverId()}${path}`,{...init,headers:{Authorization:`Bearer ${apiKey()}`,Accept:"Application/vnd.pterodactyl.v1+json","Content-Type":"application/json",...(init.headers||{})},signal:controller.signal});const text=await response.text();let data:any=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!response.ok)throw new Error(`Painel respondeu ${response.status}: ${typeof data==="string"?data.slice(0,180):data?.errors?.[0]?.detail||"falha na API"}`);return data}finally{clearTimeout(timer)}
}
async function listDirectory(directory:string):Promise<any[]>{const data=await panelRequest(`/files/list?directory=${encodeURIComponent(directory)}`);return Array.isArray(data?.data)?data.data.map((e:any)=>e?.attributes||e):[]}
async function inventoryFiles(root="/",limit=1500):Promise<{entries:string[];truncated:boolean}>{const queue=[root],entries:string[]=[];while(queue.length&&entries.length<limit){const directory=queue.shift()!;for(const item of await listDirectory(directory)){const name=String(item.name||"");if(!name||name==="."||name==="..")continue;const path=directory==="/"?`/${name}`:`${directory}/${name}`;entries.push(`${item.is_file===false?"[DIR] ":"[FILE]"} ${path}${item.is_file===false?"":` (${Number(item.size||0)} bytes)`}`);if(item.is_file===false)queue.push(path);if(entries.length>=limit)break}}return{entries,truncated:queue.length>0}}
export async function testHostFileAccess(actor:WipeActor):Promise<any>{const name=`.guerra-fria-file-test-${Date.now()}-${Math.random().toString(16).slice(2)}.txt`,testPath=`/${name}`,steps:string[]=[];let created=false,visibleAfterCreate=false,deleted=false,absentAfterDelete=false;try{await panelRequest(`/files/write?file=${encodeURIComponent(testPath)}`,{method:"POST",headers:{"Content-Type":"text/plain"},body:`Teste temporário Guerra Fria\nCriado em: ${new Date().toISOString()}\nAdministrador: ${actor.name} (${actor.id})\n`});created=true;steps.push("OK — arquivo temporário criado");visibleAfterCreate=(await listDirectory("/")).some(i=>String(i.name)===name&&i.is_file!==false);if(!visibleAfterCreate)throw new Error("O painel aceitou a escrita, mas o arquivo não apareceu na listagem.");steps.push("OK — arquivo encontrado na listagem");const inventory=await inventoryFiles();steps.push(`OK — inventário gerado (${inventory.entries.length} entradas${inventory.truncated?", limitado":""})`);await panelRequest("/files/delete",{method:"POST",body:JSON.stringify({root:"/",files:[name]})});deleted=true;steps.push("OK — arquivo temporário apagado");absentAfterDelete=!(await listDirectory("/")).some(i=>String(i.name)===name);if(!absentAfterDelete)throw new Error("O arquivo ainda aparece após a exclusão.");steps.push("OK — exclusão confirmada por nova listagem");await auditWipe("FILE_ACCESS_TEST_OK",actor,`${testPath}; ${inventory.entries.length} entradas listadas.`);return{success:true,testPath,created,visibleAfterCreate,deleted,absentAfterDelete,inventory:inventory.entries,truncated:inventory.truncated,steps}}catch(error){const message=error instanceof Error?error.message:"Falha desconhecida";steps.push(`ERRO — ${message}`);await auditWipe("FILE_ACCESS_TEST_FAILED",actor,`${testPath}; ${message}`).catch(()=>{});throw Object.assign(new Error(message),{testReport:{success:false,testPath,created,visibleAfterCreate,deleted,absentAfterDelete,inventory:[],truncated:false,steps}})}finally{if(!deleted)await panelRequest("/files/delete",{method:"POST",body:JSON.stringify({root:"/",files:[name]})}).catch(()=>null)}}
async function powerSnapshot():Promise<{state:string;uptime:number|null}>{const data=await panelRequest("/resources"),uptime=Number(data?.attributes?.resources?.uptime);return{state:String(data?.attributes?.current_state||"unknown"),uptime:Number.isFinite(uptime)?uptime:null}}
async function state(){return(await powerSnapshot()).state}
async function waitForState(expected:"offline"|"running",timeoutMs=120000){const started=Date.now();while(Date.now()-started<timeoutMs){if(await state()===expected)return;await new Promise(r=>setTimeout(r,3000))}throw new Error(`Servidor não chegou ao estado ${expected} dentro do limite.`)}
async function waitForRestart(previousUptime:number|null,timeoutMs=180000){const started=Date.now();let transitionSeen=false;while(Date.now()-started<timeoutMs){const current=await powerSnapshot();if(current.state!=="running")transitionSeen=true;if(previousUptime!==null&&current.uptime!==null&&current.uptime+5000<previousUptime)transitionSeen=true;if(transitionSeen&&current.state==="running")return;if(Date.now()-started>=30000&&current.state==="running")return;await new Promise(r=>setTimeout(r,1000))}throw new Error("A host não confirmou o ciclo completo do reinício.")}
export type HostPowerSignal="start"|"stop"|"restart";
export async function getHostPowerState(){return state()}
export async function getHostResourceSnapshot(){const data=await panelRequest("/resources"),a=data?.attributes||{},r=a.resources||{},num=(v:unknown)=>{const p=Number(v);return Number.isFinite(p)&&p>=0?p:0};return{state:String(a.current_state||"unknown"),uptime:num(r.uptime),networkRxBytes:num(r.network_rx_bytes),networkTxBytes:num(r.network_tx_bytes),memoryBytes:num(r.memory_bytes),cpuAbsolute:num(r.cpu_absolute)}}
export async function controlHostPower(signal:HostPowerSignal,actor:WipeActor){const beforeSnapshot=await powerSnapshot(),before=beforeSnapshot.state;await panelRequest("/power",{method:"POST",body:JSON.stringify({signal})});if(signal==="start")await waitForState("running",180000);if(signal==="stop")await waitForState("offline",120000);if(signal==="restart")await waitForRestart(beforeSnapshot.uptime,180000);const current=await state();await auditWipe(`SERVER_POWER_${signal.toUpperCase()}`,actor,`Painel web: ${before} → ${current}.`);return{state:current}}
export async function resolveRustMapsUrl(input:string):Promise<{pageUrl:string;mapUrl:string;imageUrl?:string}>{let url:URL;try{url=new URL(input.trim())}catch{throw new Error("Link do RustMaps inválido.")}if(url.protocol!=="https:"&&url.protocol!=="http:")throw new Error("O link do mapa precisa usar HTTPS.");if(/\.map(?:\?|$)/i.test(url.href))return{pageUrl:url.href,mapUrl:url.href};if(!/(^|\.)rustmaps\.com$/i.test(url.hostname))throw new Error("Use um link do RustMaps ou uma URL direta terminada em .map.");const response=await fetch(url.href,{redirect:"follow",signal:AbortSignal.timeout(20000)});if(!response.ok)throw new Error(`RustMaps respondeu ${response.status}.`);const html=await response.text(),candidates=[...html.matchAll(/https?:\\?\/\\?\/[^\s"'<>]+?\.map(?:\?[^\s"'<>]*)?/gi)].map(m=>m[0].replace(/\\\//g,"/").replace(/&amp;/g,"&")),mapUrl=candidates.find(c=>{try{return new URL(c).protocol.startsWith("http")}catch{return false}}),imageUrl=html.match(/<meta[^>]+property=["']og:image["'][^>]+content=["']([^"']+)/i)?.[1]||html.match(/<meta[^>]+content=["']([^"']+)["'][^>]+property=["']og:image["']/i)?.[1];if(!mapUrl)throw new Error("Não encontrei o download .map nessa página. Copie no RustMaps o link direto de download do mapa.");return{pageUrl:url.href,mapUrl,imageUrl}}
type StartupInfo={variables:any[];startupCommand:string;rawStartupCommand:string};
async function startupInfo():Promise<StartupInfo>{const data=await panelRequest("/startup");return{variables:Array.isArray(data?.data)?data.data.map((i:any)=>i?.attributes||i):[],startupCommand:String(data?.meta?.startup_command||""),rawStartupCommand:String(data?.meta?.raw_startup_command||"")}}
async function startupVariables(){return(await startupInfo()).variables}
function findLevelUrlVariable(variables:any[]){for(const alias of ["LEVEL_URL","LEVELURL","SERVER_LEVEL_URL","CUSTOM_MAP_URL","MAP_URL"]){const found=variables.find(v=>String(v.env_variable||v.name||"").toUpperCase()===alias);if(found)return String(found.env_variable||found.name)}return null}
function findStartupVariable(variables:any[],aliases:string[]){for(const alias of aliases){const found=variables.find(v=>String(v.env_variable||v.name||"").toUpperCase()===alias);if(found)return String(found.env_variable||found.name)}return null}
const SEED_ALIASES=["WORLD_SEED","SERVER_SEED","SEED","RUST_SEED"],SIZE_ALIASES=["WORLD_SIZE","SERVER_WORLD_SIZE","SERVER_SIZE","WORLD_SIZE_INT","RUST_WORLD_SIZE"],LEVEL_URL_ALIASES=["LEVEL_URL","LEVELURL","SERVER_LEVEL_URL","CUSTOM_MAP_URL","MAP_URL"];
function startupKeys(info:StartupInfo,aliases:string[]){const wanted=new Set(aliases.map(v=>v.toUpperCase())),matches=info.variables.filter(v=>wanted.has(String(v.env_variable||v.name||"").toUpperCase())),raw=info.rawStartupCommand.toUpperCase(),referenced=matches.filter(v=>{const key=String(v.env_variable||v.name||"").toUpperCase();return raw.includes(`{{${key}}}`)||raw.includes(`\${${key}}`)}),selected=referenced.length?referenced:matches;return[...new Set(selected.map(v=>String(v.env_variable||v.name||"")).filter(Boolean))]}
function proceduralKeys(variables:any[]){return{seed:findStartupVariable(variables,SEED_ALIASES),size:findStartupVariable(variables,SIZE_ALIASES),levelUrl:findLevelUrlVariable(variables)}}
function startupValue(variables:any[],key:string|null){if(!key)return null;const variable=variables.find(i=>String(i.env_variable||i.name||"")===key),value=variable?.server_value??variable?.value??variable?.default_value;return value===undefined||value===null||String(value).trim()===""?null:String(value)}
function startupEditable(variables:any[],key:string|null){if(!key)return false;const v=variables.find(i=>String(i.env_variable||i.name||"")===key);return Boolean(v&&(v.is_editable===true||v.user_editable===true))}
async function probeFilePermissions():Promise<DiagnosticFilePermission>{const name=`.guerra-fria-diagnostic-${Date.now()}-${Math.random().toString(16).slice(2)}.tmp`,probePath=`/${name}`;let listing=false,write=false,deleted=false;try{await listDirectory("/");listing=true;await panelRequest(`/files/write?file=${encodeURIComponent(probePath)}`,{method:"POST",headers:{"Content-Type":"text/plain"},body:"Guerra Fria wipe diagnostic permission probe\n"});write=true;if(!(await listDirectory("/")).some(i=>String(i.name)===name))throw new Error("O arquivo temporário não apareceu após a escrita.");await panelRequest("/files/delete",{method:"POST",body:JSON.stringify({root:"/",files:[name]})});deleted=!(await listDirectory("/")).some(i=>String(i.name)===name);if(!deleted)throw new Error("O arquivo temporário continuou presente após a exclusão.");return{listing,write,delete:deleted,confirmed:listing&&write&&deleted,probePath}}finally{if(write&&!deleted)await panelRequest("/files/delete",{method:"POST",body:JSON.stringify({root:"/",files:[name]})}).catch(()=>null)}}
export async function diagnoseHost(){const[server,resources,root,startup,filePermissions,mapPlan,generalPlan]=await Promise.all([panelRequest(""),panelRequest("/resources"),listDirectory("/"),startupInfo().catch(()=>({variables:[],startupCommand:"",rawStartupCommand:""})),probeFilePermissions(),buildWipePlan("map"),buildWipePlan("general")]),keys=proceduralKeys(startup.variables),levelUrlVariable=keys.levelUrl,effectiveSeed=/(?:^|\s)[+-]?server\.seed(?:=|\s+)/i.test(startup.startupCommand),effectiveSize=/(?:^|\s)[+-]?server\.worldsize(?:=|\s+)/i.test(startup.startupCommand),currentSeed=startupValue(startup.variables,keys.seed),currentSize=startupValue(startup.variables,keys.size),seedEditable=startupEditable(startup.variables,keys.seed),sizeEditable=startupEditable(startup.variables,keys.size),lock=await getWipeLockState();return{connected:true,server:{name:server?.attributes?.name||"Rust",identifier:server?.attributes?.identifier||serverId(),state:resources?.attributes?.current_state||"unknown"},currentMap:{seed:currentSeed,size:currentSize,mapFiles:mapPlan.files.filter(f=>f.name.toLowerCase().endsWith(".map"))},permissions:{files:filePermissions,startup:{seedEditable,sizeEditable,confirmed:seedEditable&&sizeEditable}},plans:{map:mapPlan,general:generalPlan},capabilities:{api:true,power:true,backups:true,files:filePermissions.confirmed,startup:Boolean(levelUrlVariable||keys.seed||keys.size),proceduralStartup:Boolean(keys.seed&&keys.size&&seedEditable&&sizeEditable&&effectiveSeed&&effectiveSize),destructiveEnabled:executionEnabled(),automationEnabled:automationEnabled(),wipeUnlocked:lock.unlocked},wipeLock:lock,levelUrlVariable,seedVariable:keys.seed,sizeVariable:keys.size,startupCommand:startup.startupCommand,startupValidation:{seedArgument:effectiveSeed,sizeArgument:effectiveSize,seedEditable,sizeEditable},root:root.map((e:any)=>({name:e.name,directory:e.is_file===false,size:Number(e.size||0)})).slice(0,100)}}
async function discoverIdentityDirectories(){const entries=await listDirectory("/server").catch(()=>[]);return entries.filter((e:any)=>e.is_file===false&&e.name&&e.name!=="."&&e.name!=="..").map((e:any)=>`/server/${e.name}`)}
function classify(name:string):"map"|"blueprints"|null{const lower=name.toLowerCase();if(lower.endsWith(".map")||lower.endsWith(".sav")||/\.sav(?:\.\d+|\.bak)?$/.test(lower))return"map";if(/player\.blueprints.*\.db(?:-(?:wal|shm))?$/.test(lower))return"blueprints";return null}
async function collectWipeFiles(directory:string,depth=0):Promise<HostFile[]>{if(depth>3)return[];const files:HostFile[]=[];for(const entry of await listDirectory(directory)){const name=String(entry.name||"");if(!name||name==="."||name==="..")continue;const path=`${directory}/${name}`;if(entry.is_file===false){files.push(...await collectWipeFiles(path,depth+1));continue}const group=classify(name);if(group)files.push({name,path,directory,size:Number(entry.size||0),group})}return files}
export async function buildWipePlan(kind:WipeKind,rustMapsUrl?:string){const map=rustMapsUrl?await resolveRustMapsUrl(rustMapsUrl):undefined,directories=await discoverIdentityDirectories(),files:HostFile[]=[];for(const directory of directories)for(const file of await collectWipeFiles(directory)){if(file.group==="blueprints"&&kind!=="general")continue;files.push(file)}return{kind,map,files,directories,totalBytes:files.reduce((s,f)=>s+f.size,0),destructiveEnabled:executionEnabled()}}
export async function auditWipe(action:string,actor:WipeActor,reason:string){await db.insert(modLogsTable).values({action,steamId:"SERVER",playerName:"Servidor Guerra Fria",reason,adminId:actor.id,adminName:actor.name})}
async function createBackup(kind:WipeKind){const created=await panelRequest("/backups",{method:"POST",body:JSON.stringify({name:`pre-wipe-${kind}-${new Date().toISOString()}`,ignored:""})}),uuid=String(created?.attributes?.uuid||created?.data?.attributes?.uuid||"");if(!uuid)throw new Error("A host não retornou o identificador do backup.");const started=Date.now();while(Date.now()-started<900000){const data=await panelRequest(`/backups/${uuid}`),backup=data?.attributes||data?.data?.attributes||data;if(backup?.completed_at){if(backup.is_successful===false)throw new Error("O backup de segurança falhou.");return uuid}await new Promise(r=>setTimeout(r,5000))}throw new Error("O backup não terminou dentro de 15 minutos; wipe cancelado.")}
async function setMapUrl(mapUrl:string){const key=findLevelUrlVariable(await startupVariables());if(!key)throw new Error("A variável de URL do mapa não foi encontrada na inicialização da host.");await panelRequest("/startup/variable",{method:"PUT",body:JSON.stringify({key,value:mapUrl})});const current=(await startupVariables()).find(v=>String(v.env_variable||v.name||"")===key);if(String(current?.server_value||current?.value||"")!==mapUrl)throw new Error("A host não confirmou a nova URL do mapa.")}
async function setStartupValue(key:string,value:string){const response=await panelRequest("/startup/variable",{method:"PUT",body:JSON.stringify({key,value})}),returned=response?.attributes||response?.data?.attributes||response;if(String(returned?.server_value??"")!==value)throw new Error(`O Pterodactyl não retornou ${key}=${value}.`);const current=(await startupVariables()).find(v=>String(v.env_variable||v.name||"")===key);if(String(current?.server_value??current?.value??"")!==value)throw new Error(`A host não confirmou a variável ${key}.`)}
function commandHasValue(command:string,argument:string,value:number):boolean{
 const normalized=command.replace(/\\/g,"").replace(/["']/g,"").replace(/\s+/g," ").trim();
 const escaped=argument.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");
 return new RegExp(`(?:^|\\s)[+-]?${escaped}(?:=|\\s+)${value}(?=\\s|$)`,`i`).test(normalized);
}
async function setProceduralMap(seed:number,size:number){const before=await startupInfo(),seedKeys=startupKeys(before,SEED_ALIASES),sizeKeys=startupKeys(before,SIZE_ALIASES),levelKeys=startupKeys(before,LEVEL_URL_ALIASES);if(!seedKeys.length||!sizeKeys.length)throw new Error("As variáveis de seed e size não foram encontradas no startup do Pterodactyl.");for(const key of levelKeys)await setStartupValue(key,"");for(const key of seedKeys)await setStartupValue(key,String(seed));for(const key of sizeKeys)await setStartupValue(key,String(size));const after=await startupInfo();for(const key of seedKeys){const current=after.variables.find(v=>String(v.env_variable||v.name||"")===key);if(String(current?.server_value??"")!==String(seed))throw new Error(`Seed não confirmada em ${key}.`)}for(const key of sizeKeys){const current=after.variables.find(v=>String(v.env_variable||v.name||"")===key);if(String(current?.server_value??"")!==String(size))throw new Error(`Size não confirmado em ${key}.`)}const seedInCommand=commandHasValue(after.startupCommand,"server.seed",seed),sizeInCommand=commandHasValue(after.startupCommand,"server.worldsize",size);if(!seedInCommand||!sizeInCommand){await auditWipe("WIPE_STARTUP_RENDER_WARNING",{id:"SYSTEM",name:"Startup validator"},`Variáveis confirmadas pela API (seed=${seed}, size=${size}), mas parser do comando renderizado não confirmou ambos. Prosseguindo porque os server_value foram confirmados.`).catch(()=>{})}return{seedKeys,sizeKeys,startupCommand:after.startupCommand}}
async function deletePlannedFiles(files:HostFile[]){const grouped=new Map<string,string[]>();for(const file of files)grouped.set(file.directory,[...(grouped.get(file.directory)||[]),file.name]);for(const[root,names]of grouped)await panelRequest("/files/delete",{method:"POST",body:JSON.stringify({root,files:names})});for(const[root,names]of grouped){const remaining=new Set((await listDirectory(root)).map(i=>String(i.name))),failed=names.filter(n=>remaining.has(n));if(failed.length)throw new Error(`A exclusão não foi confirmada em ${root}: ${failed.join(", ")}`)}}
async function waitForGeneratedProceduralMap(seed:number,size:number,timeoutMs=600000){const expected=new RegExp(`(?:^|\\.)${size}(?:\\.1)?\\.${seed}(?:\\.|$)`,`i`),started=Date.now();while(Date.now()-started<timeoutMs){const directories=await discoverIdentityDirectories(),maps:HostFile[]=(await Promise.all(directories.map(d=>collectWipeFiles(d)))).flat().filter(f=>f.name.toLowerCase().endsWith(".map")),correct=maps.find(f=>expected.test(f.name));if(correct)return correct.path;await new Promise(r=>setTimeout(r,5000))}const directories=await discoverIdentityDirectories(),maps:HostFile[]=(await Promise.all(directories.map(d=>collectWipeFiles(d)))).flat().filter(f=>f.name.toLowerCase().endsWith(".map"));throw new Error(`Mapa esperado size ${size} seed ${seed} não apareceu. Encontrados: ${maps.map(f=>f.name).join(", ")||"nenhum"}.`)}
export async function prepareProceduralWipeBackup(kind:WipeKind,seed:number,size:number,actor:WipeActor){await assertWipeUnlocked();if(!Number.isInteger(seed)||!Number.isInteger(size))throw new Error("Seed ou size inválidos para preparar o wipe.");const plan=await buildWipePlan(kind);if(!plan.files.some(f=>f.group==="map"))throw new Error("Nenhum save de mapa localizado para preparar o wipe.");const startup=await setProceduralMap(seed,size),backupId=await createBackup(kind);await auditWipe("WIPE_BACKUP_PREPARED",actor,`${kind}; seed ${seed} via ${startup.seedKeys.join(",")}; size ${size} via ${startup.sizeKeys.join(",")}; backup ${backupId}`);return backupId}
export async function restartHostServer(actor:WipeActor){await panelRequest("/power",{method:"POST",body:JSON.stringify({signal:"restart"})});await auditWipe("AUTO_RESTART_TRIGGERED",actor,"Reinício diário enviado para a host.")}
export async function executePreparedWipe(kind:WipeKind,rustMapsUrl:string,actor:WipeActor,automated=false,lifecycle:WipeLifecycle={}){await assertWipeUnlocked();if(!executionEnabled())throw new Error("Execução bloqueada por WIPE_EXECUTION_ENABLED=false.");if(automated&&!automationEnabled())throw new Error("Automação bloqueada por WIPE_AUTOMATION_ENABLED=false.");const plan=await buildWipePlan(kind,rustMapsUrl);if(!plan.map?.mapUrl)throw new Error("Mapa não validado.");if(!plan.files.some(f=>f.group==="map"))throw new Error("Nenhum save de mapa foi localizado; wipe cancelado por segurança.");await auditWipe("WIPE_STARTED",actor,`${kind}; ${plan.files.length} arquivos; ${plan.map.pageUrl}`);const backupId=await createBackup(kind);await assertWipeUnlocked();await panelRequest("/power",{method:"POST",body:JSON.stringify({signal:"stop"})});await waitForState("offline");await lifecycle.onStopped?.();try{await setMapUrl(plan.map.mapUrl);await deletePlannedFiles(plan.files);await panelRequest("/power",{method:"POST",body:JSON.stringify({signal:"start"})});try{await waitForState("running",600000)}catch{const current=await state().catch(()=>"unknown");throw new Error(`O comando START foi enviado, mas o Pterodactyl não confirmou running no tempo esperado. Estado atual: ${current}. O bot NÃO enviou STOP.`)}await resetAllLeaderboardStats();await auditWipe("LEADERBOARD_RESET_AFTER_WIPE",actor,`${kind}; reset automático concluído.`);await auditWipe("WIPE_COMPLETED",actor,`${kind}; ${plan.files.length} arquivos; mapa ${plan.map.pageUrl}; backup ${backupId}`);return{filesDeleted:plan.files.length,mapUrl:plan.map.mapUrl}}catch(error){await auditWipe("WIPE_FAILED_AFTER_START_NO_STOP",actor,error instanceof Error?error.message:"Falha desconhecida");throw error}}
export async function executePreparedProceduralWipe(kind:WipeKind,seed:number,size:number,actor:WipeActor,automated=false,lifecycle:WipeLifecycle={},preparedBackupId?:string):Promise<{filesDeleted:number;seed:number;size:number;mapFile:string}>{await assertWipeUnlocked();if(!Number.isInteger(seed)||seed<0||seed>2147483647)throw new Error("Seed inválida.");if(!Number.isInteger(size)||size<1000||size>6000)throw new Error("Size deve estar entre 1000 e 6000.");if(!executionEnabled())throw new Error("Execução bloqueada por WIPE_EXECUTION_ENABLED=false.");if(automated&&!automationEnabled())throw new Error("Automação bloqueada por WIPE_AUTOMATION_ENABLED=false.");const plan=await buildWipePlan(kind);if(!plan.files.some(f=>f.group==="map"))throw new Error("Nenhum save de mapa foi localizado; wipe cancelado por segurança.");await auditWipe("WIPE_STARTED",actor,`${kind}; ${plan.files.length} arquivos; seed ${seed}; size ${size}`);await panelRequest("/power",{method:"POST",body:JSON.stringify({signal:"stop"})});await waitForState("offline",120000);await lifecycle.onStopped?.();const backupId=preparedBackupId||await createBackup(kind);await assertWipeUnlocked();const startup=await setProceduralMap(seed,size);await auditWipe("WIPE_MAP_STARTUP_CONFIRMED",actor,`seed ${seed} via ${startup.seedKeys.join(",")}; size ${size} via ${startup.sizeKeys.join(",")}`);await deletePlannedFiles(plan.files);await panelRequest("/power",{method:"POST",body:JSON.stringify({signal:"start"})});try{await waitForState("running",600000)}catch{const current=await state().catch(()=>"unknown");await auditWipe("WIPE_START_NOT_CONFIRMED_NO_STOP",actor,`seed ${seed}; size ${size}; estado ${current}; nenhum STOP adicional enviado.`).catch(()=>{});throw new Error(`O comando START foi enviado, mas o Pterodactyl não confirmou running no tempo esperado. Estado atual: ${current}. O bot NÃO enviou STOP.`)}const mapFile=await waitForGeneratedProceduralMap(seed,size,600000);await resetAllLeaderboardStats();await auditWipe("LEADERBOARD_RESET_AFTER_WIPE",actor,`${kind}; reset automático concluído.`);await auditWipe("WIPE_COMPLETED",actor,`${kind}; ${plan.files.length} arquivos; seed ${seed}; size ${size}; mapa ${mapFile}; backup ${backupId}; fluxo unificado com wipe test.`);return{filesDeleted:plan.files.length,seed,size,mapFile}}
export async function executeWipe(kind:WipeKind,rustMapsUrl:string,confirmation:string,actor:WipeActor){if(confirmation!=="WIPE GUERRA FRIA")throw new Error("Confirmação inválida.");return executePreparedWipe(kind,rustMapsUrl,actor,false)}
export async function executeProceduralWipe(kind:WipeKind,seed:number,size:number,confirmation:string,actor:WipeActor){if(confirmation!=="WIPE GUERRA FRIA")throw new Error("Confirmação inválida.");return executePreparedProceduralWipe(kind,seed,size,actor,false)}
