export function renderDuoPage(): string {
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>Resgatar Super Combo Duo • Guerra Fria</title><style>
  [hidden]{display:none!important}*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;background:radial-gradient(at top,#3b2445,#070608 65%);color:#f7f3f8;font-family:system-ui;padding:20px}main{width:min(560px,100%);padding:28px;border:1px solid #644775;border-radius:24px;background:linear-gradient(145deg,#17111b,#0b090e)}small{color:#efbd69;letter-spacing:.12em}h1{font-size:32px}p{color:#b8adbf;line-height:1.6}a,button{display:block;width:100%;text-align:center;padding:14px;margin:12px 0;border-radius:12px;border:1px solid #705a31;background:#21162a;color:white;font:inherit;font-weight:800;text-decoration:none;cursor:pointer}button{background:linear-gradient(135deg,#ffd85c,#cc9518);color:#211704}button:disabled{opacity:.45;cursor:not-allowed}#status{padding:14px;border:1px solid #46364e;border-radius:12px;white-space:pre-line}.back{background:transparent;font-weight:400}</style></head><body><main><small>LOJA OFICIAL GUERRA FRIA</small><h1>👥 Super Combo Duo</h1><p>Resgate VIP Bronze + Prata + Ouro por 30 dias na sua conta. Confirme seu Discord e sua Steam antes de continuar. Este link tem uma única vaga e o comprador não pode usá-la.</p><p id="account"></p><a id="discord" href="/api/admin/auth/login?target=duo">ENTRAR COM DISCORD</a><a id="steam" href="/api/store/steam/login?duo=1" hidden>ENTRAR COM STEAM</a><p id="status" role="status" aria-live="polite">Verificando link…</p><button id="claim" disabled>RESGATAR OS TRÊS VIPs</button><a class="back" href="/loja">Voltar à loja</a></main><script>
  (async()=>{const status=document.getElementById('status'),claim=document.getElementById('claim');let token='';
  try{if(location.hash){token=location.hash.slice(1);sessionStorage.setItem('gf_duo_token',token);history.replaceState(null,'',location.pathname)}else token=sessionStorage.getItem('gf_duo_token')||''}catch{status.textContent='Permita o armazenamento desta aba para continuar com o login.';return}
  if(!token){status.textContent='Abra o link enviado pelo comprador para iniciar o resgate.';return}
  const post=async(path)=>{const r=await fetch('/api/store/duo/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})});const d=await r.json();if(!r.ok)throw new Error(d.error);return d};
  let active=false;
  async function refresh(){const info=await post('inspect');active=['available','delivering'].includes(info.status);if(info.status==='expired')status.textContent='Este link expirou. O prazo para iniciar o resgate é de 30 dias após o pagamento.';else if(info.status==='redeemed'){status.textContent='✅ Este link já foi resgatado. Os VIPs foram entregues.';claim.disabled=true;sessionStorage.removeItem('gf_duo_token');active=false}else status.textContent=(info.status==='delivering'?'Entrega em processamento para a conta que confirmou o resgate.':'Link disponível. Confirme suas contas para resgatar.')+'\\nPrazo: '+new Date(info.expiresAt).toLocaleString('pt-BR');return info}
  try{await refresh();const r=await fetch('/api/store/me',{cache:'no-store'});if(r.ok){const me=await r.json();document.getElementById('discord').hidden=true;document.getElementById('account').textContent='Discord: '+me.username+' • Steam: '+(me.steamId||'não conectada');document.getElementById('steam').hidden=Boolean(me.steamVerified);claim.disabled=!(active&&me.steamVerified)}}catch(e){status.textContent=e.message||'Falha ao verificar o link. Recarregue para tentar novamente.'}
  claim.onclick=async()=>{claim.disabled=true;status.textContent='Entregando seus VIPs…';try{await post('claim');status.textContent='✅ Bronze, Prata e Ouro ativados por 30 dias na sua conta!';sessionStorage.removeItem('gf_duo_token')}catch(e){status.textContent=e.message;claim.disabled=false}};
  })();</script></body></html>`;
}
