export const adminExtraJs = `
(function(){
  function e(id){return document.getElementById(id)}
  function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]})}
  async function getJson(url){var r=await fetch(url);var j={};try{j=await r.json()}catch(_x){}if(!r.ok)throw new Error(j.error||('Erro '+r.status));return j}
  var pages={overview:'Visão Geral',players:'Jogadores',chat:'Chat ao vivo',events:'Eventos',steam:'Steam / Boosters',vip:'VIPs',finance:'Financeiro',logs:'Logs'};
  function translate(){
    var dict={'Resumen':'Visão Geral','Jugadores online':'Jogadores online','Cola':'Fila','Durmientes':'Dormindo','Conocidos':'Jogadores conhecidos','VIP activos':'VIPs ativos','Actividad reciente':'Atividade recente','Jugadores':'Jogadores','Acciones':'Ações','Selecciona un jugador':'Selecione um jogador','Banear':'Banir','Desbanear':'Desbanir','Cantidad':'Quantidade','Vaciar inventario':'Limpar inventário','Chat del juego':'Chat do jogo','Eventos detectados':'Eventos detectados','Actualizar':'Atualizar','Finanzas':'Financeiro','Finanzas • Mercado Pago':'Financeiro • Mercado Pago','Facturación bruta':'Faturamento bruto','Facturación neta':'Faturamento líquido','Aprobados':'Aprovados','Fecha':'Data','Descripción':'Descrição','Historial de moderación':'Histórico de moderação'};
    var all=document.querySelectorAll('h1,h2,h3,small,label,button,span,th,option');
    for(var i=0;i<all.length;i++){var t=(all[i].textContent||'').trim();if(dict[t])all[i].textContent=dict[t]}
    if(e('pageTitle'))e('pageTitle').textContent='Visão Geral';
  }
  function show(id){var vs=document.querySelectorAll('.view');for(var i=0;i<vs.length;i++)vs[i].classList.remove('active');if(e(id))e(id).classList.add('active');if(e('pageTitle'))e('pageTitle').textContent=pages[id]||'Painel';if(id==='players')loadPlayers();if(id==='chat')loadChat();if(id==='events')loadEvents();if(id==='steam')loadSteam();if(id==='vip')loadVips();if(id==='finance')loadFinance();if(id==='logs')loadLogs()}
  function buildNav(){var boxes=[e('nav'),e('mobileNav')],ids=Object.keys(pages);for(var b=0;b<boxes.length;b++){if(!boxes[b])continue;boxes[b].innerHTML='';for(var i=0;i<ids.length;i++){var id=ids[i],bt=document.createElement('button');bt.textContent=pages[id];bt.onclick=(function(x){return function(){show(x)}})(id);boxes[b].appendChild(bt)}}}
  async function loadOverview(){var o=null,s=null;try{o=await getJson('/api/admin/overview')}catch(_a){}try{s=await getJson('/api/admin/server/online')}catch(_b){}var info=(s&&s.info)||(o&&o.server)||{};var count=typeof info.players==='number'?info.players:(s&&s.players?s.players.length:0);if(e('online'))e('online').textContent=String(count);if(e('queue'))e('queue').textContent=String(info.queued||0);if(e('sleepers'))e('sleepers').textContent=String(info.sleepers||0);if(e('slots'))e('slots').textContent=String(count)+'/'+String(info.maxPlayers||0);if(e('map'))e('map').textContent=info.map||'Indisponível';if(o&&o.summary){if(e('known'))e('known').textContent=String(o.summary.knownPlayers||0);if(e('vipsCount'))e('vipsCount').textContent=String(o.summary.activeVips||0);if(e('boostersCount'))e('boostersCount').textContent=String(o.summary.activeBoosters||0)}if(o&&Array.isArray(o.recentModeration)&&e('recentLogs'))e('recentLogs').innerHTML=o.recentModeration.map(function(x){return '<tr><td>'+esc(x.action)+'</td><td>'+esc(x.playerName)+'</td><td>'+esc(x.adminName)+'</td><td>'+esc(x.reason||'—')+'</td></tr>'}).join('')}
  async function loadPlayers(){try{var q=e('playerSearch')?e('playerSearch').value:'';var d=await getJson('/api/admin/players?q='+encodeURIComponent(q));if(e('playerRows'))e('playerRows').innerHTML=(d.players||[]).map(function(p){return '<tr><td class="'+(p.isOnline?'online':'offline')+'">'+(p.isOnline?'● Online':'● Offline')+'</td><td>'+esc(p.playerName||p.name)+'</td><td class="mono">'+esc(p.steamId)+'</td><td>'+(p.lastSeen?new Date(p.lastSeen).toLocaleString('pt-BR'):'—')+'</td></tr>'}).join('')}catch(_e){}}
  async function loadChat(){try{var d=await getJson('/api/admin/server/chat');if(e('chatBox'))e('chatBox').innerHTML=(d.messages||[]).map(function(m){return '<div class="msg"><b>'+esc(m.player)+'</b><div>'+esc(m.message)+'</div></div>'}).join('')}catch(_e){}}
  async function loadEvents(){try{var d=await getJson('/api/admin/server/events');if(e('eventGrid'))e('eventGrid').innerHTML=(d.events||[]).map(function(x){return '<div class="event"><b>'+esc(x.label)+'</b><div>'+(x.active?'● ATIVO':'● NÃO DETECTADO')+'</div></div>'}).join('')}catch(_e){}}
  async function loadSteam(){try{var d=await getJson('/api/admin/steam-links');if(e('steamRows'))e('steamRows').innerHTML=(d.links||[]).map(function(x){return '<tr><td>'+esc(x.discordUserId)+'</td><td>'+esc(x.steamId)+'</td><td>'+(x.active?'Ativo':'Inativo')+'</td></tr>'}).join('')}catch(_e){}}
  async function loadVips(){try{var d=await getJson('/api/admin/vips');if(e('vipRows'))e('vipRows').innerHTML=(d.vips||[]).map(function(v){return '<tr><td>'+esc(v.id)+'</td><td>'+esc(v.steamId)+'</td><td>'+esc(v.vipTier)+'</td><td>'+(v.expiresAt?new Date(v.expiresAt).toLocaleString('pt-BR'):'—')+'</td></tr>'}).join('')}catch(_e){}}
  async function loadFinance(){try{var days=e('financeDays')?e('financeDays').value:'30';var d=await getJson('/api/admin/finance/live?days='+encodeURIComponent(days));var brl=function(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})};if(e('gross'))e('gross').textContent=brl(d.summary&&d.summary.grossRevenue);if(e('refunded'))e('refunded').textContent=brl(d.summary&&d.summary.refunded);if(e('net'))e('net').textContent=brl(d.summary&&d.summary.netRevenue);if(e('approved'))e('approved').textContent=String(d.summary&&d.summary.approved||0)}catch(_e){}}
  async function loadLogs(){try{var d=await getJson('/api/admin/modlogs');if(e('logRows'))e('logRows').innerHTML=(d.logs||[]).map(function(x){return '<tr><td>'+esc(x.action)+'</td><td>'+esc(x.playerName)+'</td><td>'+esc(x.adminName)+'</td><td>'+esc(x.reason||'—')+'</td></tr>'}).join('')}catch(_e){}}
  function start(){translate();buildNav();if(e('app'))e('app').style.display='grid';if(e('login'))e('login').style.display='none';var ps=e('playerSearch');if(ps)ps.addEventListener('input',function(){clearTimeout(window.gfSearch);window.gfSearch=setTimeout(loadPlayers,250)});var card=e('online');if(card&&card.parentElement)card.parentElement.onclick=function(){show('players')};loadOverview()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();setTimeout(start,700);setInterval(loadOverview,30000);
})();
`;