import type { Request } from "express";
import { renderHome as renderBaseHome } from "./homePage.js";
import { publicMilitaryThemeCss } from "./publicMilitaryTheme.js";

export function renderHome(req: Request): string {
  const motionCss = `<style id="gf-home-motion">.homeMenuToggle{display:none}.homeDrawerBackdrop,.homeDrawer{display:none}.homeMotion{opacity:0;transform:translateY(22px);transition:opacity .65s cubic-bezier(.22,1,.36,1),transform .65s cubic-bezier(.22,1,.36,1)}.homeMotion.in{opacity:1;transform:none}@media(max-width:700px){.menu{display:none!important}.homeMenuToggle{display:block;width:34px;height:34px;border:1px solid #23292d;background:#0b0e11;padding:8px;margin-left:6px}.homeMenuToggle span{display:block;height:1px;background:#eee;margin:4px 0}.homeDrawerBackdrop{display:block;position:fixed;inset:0;z-index:99991;background:#0000;pointer-events:none;transition:.32s}.homeDrawerBackdrop.open{background:#000b;pointer-events:auto}.homeDrawer{display:flex;position:fixed;top:0;right:0;bottom:0;width:min(86vw,360px);z-index:99992;background:#07090b;border-left:1px solid #20252a;transform:translateX(102%);transition:transform .38s cubic-bezier(.22,1,.36,1);flex-direction:column;box-shadow:-22px 0 60px #0008}.homeDrawer.open{transform:none}.homeDrawerHead{height:70px;border-bottom:1px solid #1b2024;display:flex;align-items:center;justify-content:space-between;padding:0 18px}.homeDrawerBrand{display:flex;align-items:center;gap:10px;text-decoration:none;color:#fff}.homeDrawerBrand i{width:27px;height:27px;background:#f59d0a;color:#080808;display:grid;place-items:center;font-style:normal;font-size:8px;font-weight:1000}.homeDrawerBrand b{font-size:9px;letter-spacing:.14em}.homeDrawerHead button{width:34px;height:34px;background:#0d1012;border:1px solid #252b2f;color:#fff;font-size:21px}.homeDrawer nav{padding:18px}.homeDrawer a.item{height:57px;border-bottom:1px solid #181d20;display:grid;grid-template-columns:30px 1fr auto;align-items:center;text-decoration:none;color:#e7e7e3}.homeDrawer a.item span{font-size:7px;color:#f59d0a;font-weight:950}.homeDrawer a.item b{font-size:12px;text-transform:uppercase;letter-spacing:.16em}.homeDrawer a.item em{font-style:normal;color:#596167;font-size:18px}.homeDrawer a.item.active b{color:#f59d0a}.homeDrawerFoot{margin-top:auto;border-top:1px solid #1b2024;padding:18px;color:#666;font-size:7px;letter-spacing:.12em}}@media(prefers-reduced-motion:reduce){.homeMotion,.homeDrawer,.homeDrawerBackdrop{transition:none!important}.homeMotion{opacity:1!important;transform:none!important}}</style>`;
  const drawer = `<div class="homeDrawerBackdrop" id="homeDrawerBackdrop"></div><aside class="homeDrawer" id="homeDrawer"><div class="homeDrawerHead"><a class="homeDrawerBrand" href="/"><i>GF</i><b>GUERRA FRIA</b></a><button id="homeDrawerClose">×</button></div><nav><a class="item active" href="/"><span>01</span><b>Início</b><em>›</em></a><a class="item" href="/loja"><span>02</span><b>Loja</b><em>›</em></a><a class="item" href="/leaderboard"><span>03</span><b>Leaderboard</b><em>›</em></a><a class="item" href="/season1"><span>04</span><b>Season</b><em>›</em></a><a class="item" href="/api/status"><span>05</span><b>Status</b><em>›</em></a></nav><div class="homeDrawerFoot">RUST 2X • DUO</div></aside>`;
  const js = `<script id="gf-home-motion-js">(()=>{const nav=document.querySelector('.nav'),account=document.querySelector('.account');if(nav&&account&&!document.getElementById('homeMenuToggle')){const b=document.createElement('button');b.id='homeMenuToggle';b.className='homeMenuToggle';b.setAttribute('aria-label','Abrir menu');b.innerHTML='<span></span><span></span><span></span>';account.after(b)}const btn=document.getElementById('homeMenuToggle'),drawer=document.getElementById('homeDrawer'),back=document.getElementById('homeDrawerBackdrop'),close=document.getElementById('homeDrawerClose');const set=o=>{drawer?.classList.toggle('open',o);back?.classList.toggle('open',o);document.documentElement.style.overflow=o?'hidden':''};btn?.addEventListener('click',()=>set(!drawer?.classList.contains('open')));close?.addEventListener('click',()=>set(false));back?.addEventListener('click',()=>set(false));drawer?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>set(false)));const els=[...new Set(['main section','main .optionBtn','main .fact','main .mode','main .wipe','main .linkCard','main h1','main h2','main .sectionTag','main .prize'].flatMap(s=>[...document.querySelectorAll(s)]))];els.forEach(el=>el.classList.add('homeMotion'));if('IntersectionObserver'in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.08,rootMargin:'0px 0px -30px'});els.forEach(el=>io.observe(el))}else els.forEach(el=>el.classList.add('in'));})();</script>`;
  let out = renderBaseHome(req).replace("</head>", `${publicMilitaryThemeCss}${motionCss}</head>`);
  out = out.replace(/<body([^>]*)>/i, `<body$1>${drawer}`);
  out = out.replace("</body>", `${js}</body>`);
  return out;
}
