import type { Request } from "express";
import { renderHome as renderBaseHome } from "./homePage.js";
import { publicMilitaryThemeCss } from "./publicMilitaryTheme.js";
import { getCommunitySession } from "./communitySession.js";

const heroRawUrl = "https://raw.githubusercontent.com/kaiquedupix-max/Guerrafira-railway/main/artifacts/api-server/public/banner-guerra-fria-infinito.gif";

export function renderHome(req: Request): string {
  const session = getCommunitySession(req);
  const storeHref = session ? "/loja" : "/api/admin/auth/login?target=store";
  const seasonCta = `<a class="seasonCta" href="/season1/guia"><span class="seasonGlow"></span><span class="seasonIcon">🎖</span><span class="seasonCopy"><small>SEASON 1 • 03/09/2026</small><b>Sistema de Season</b><em>MMR, ranking, patentes, cargos no Discord e mais de R$ 300 em premiações. Veja como vai funcionar.</em></span><span class="seasonArrow">→</span></a>`;
  const storeCta = `<a class="storeCta" href="${storeHref}"><span class="storeGlow"></span><span class="storeIcon">🛒</span><span class="storeCopy"><small>LOJA OFICIAL</small><b>Compre seu VIP</b><em>PIX ou cartão • entrega automática no Rust + cargo no Discord</em></span><span class="storeArrow">→</span></a>`;

  return renderBaseHome(req)
    .replace("</head>", `${publicMilitaryThemeCss}</head>`)
    .replace("</style>", `.homeMedia{position:relative;margin:0 auto 34px;border:1px solid #7a3023;border-radius:10px;overflow:hidden;background:#080b0d;box-shadow:0 28px 90px #000c;aspect-ratio:16/9}.homeMedia img{display:block;width:100%;height:100%;object-fit:cover}.homeMedia:after{content:'';position:absolute;inset:0;box-shadow:inset 0 0 80px #000b;pointer-events:none}.seasonCta,.storeCta{position:relative;overflow:hidden;max-width:850px;margin:30px auto 18px;display:flex;align-items:center;gap:17px;text-decoration:none;color:#fff;padding:20px 22px;border-radius:10px;box-shadow:0 22px 60px #0009,inset 0 1px #fff1;transition:transform .2s,border-color .2s,box-shadow .2s;isolation:isolate}.seasonCta{border:1px solid #943521;background:radial-gradient(circle at 90% 10%,#e2361f30,transparent 28%),linear-gradient(120deg,#1b1311 0%,#0b1013 55%,#17100d 100%)}.seasonCta:hover{transform:translateY(-3px);border-color:#e75a3b;box-shadow:0 28px 72px #000b,0 0 40px #e2361f25}.storeCta{margin-top:18px;margin-bottom:34px;border:1px solid #75502a;background:radial-gradient(circle at 90% 10%,#f3a21d22,transparent 30%),linear-gradient(120deg,#18120d 0%,#0a0f12 65%)}.storeCta:hover{transform:translateY(-3px);border-color:#c78336;box-shadow:0 28px 72px #000b,0 0 34px #f3a21d18}.seasonGlow,.storeGlow{position:absolute;width:230px;height:230px;border-radius:50%;right:-80px;top:-100px;z-index:-1}.seasonGlow{background:radial-gradient(circle,#e2361f55 0%,#e2361f12 45%,transparent 70%)}.storeGlow{background:radial-gradient(circle,#f3a21d38 0%,#f3a21d0c 45%,transparent 70%)}.seasonIcon,.storeIcon{width:60px;height:60px;flex:0 0 60px;border-radius:6px;display:grid;place-items:center;font-size:29px;box-shadow:inset 0 1px #fff2,0 8px 24px #0008;background:linear-gradient(145deg,#2b1712,#101519);border:1px solid #8e3425}.storeIcon{border-color:#795127}.seasonCopy,.storeCopy{display:flex;flex-direction:column;min-width:0}.seasonCopy small,.storeCopy small{font-size:10px;letter-spacing:.2em;font-weight:950;color:#ef653e}.storeCopy small{color:#efad4b}.seasonCopy b,.storeCopy b{font-size:24px;letter-spacing:-.02em;margin:4px 0 3px}.seasonCopy em,.storeCopy em{font-size:12px;color:#a9afb3;font-style:normal;line-height:1.45}.seasonArrow,.storeArrow{margin-left:auto;color:#f05a24;font-size:28px;font-weight:950;transition:transform .2s}.storeArrow{color:#f3a21d}.seasonCta:hover .seasonArrow,.storeCta:hover .storeArrow{transform:translateX(4px)}@media(max-width:700px){.homeMedia{margin-bottom:28px;border-radius:8px}.nav{margin-bottom:36px!important}.seasonCta,.storeCta{margin:22px 0 16px;padding:17px;border-radius:8px;gap:13px}.storeCta{margin-top:12px;margin-bottom:28px}.seasonIcon,.storeIcon{width:50px;height:50px;flex-basis:50px;font-size:24px}.seasonCopy small,.storeCopy small{font-size:8px}.seasonCopy b,.storeCopy b{font-size:19px}.seasonCopy em,.storeCopy em{font-size:10px;max-width:240px}.seasonArrow,.storeArrow{font-size:22px}}</style>`)
    .replace("</nav>", `</nav><div class="homeMedia"><img src="${heroRawUrl}" alt="Guerra Fria 2X"></div>`)
    .replace('</section><section class="choices">', `</section>${seasonCta}${storeCta}<section class="choices">`);
}
