import type { Request } from "express";
import { renderHome as renderBaseHome } from "./homePage.js";
import { brandThemeCss } from "./brandTheme.js";
import { getCommunitySession } from "./communitySession.js";

const heroRawUrl = "https://raw.githubusercontent.com/kaiquedupix-max/Guerrafira-railway/main/artifacts/api-server/public/banner-guerra-fria-infinito.gif";

export function renderHome(req: Request): string {
  const session = getCommunitySession(req);
  const storeHref = session ? "/loja" : "/api/admin/auth/login?target=store";
  const seasonCta = `<a class="seasonCta" href="/season1/guia"><span class="seasonGlow"></span><span class="seasonIcon">🏆</span><span class="seasonCopy"><small>VEM AÍ • SISTEMA DE SEASON</small><b>Season 1 começa em 03/09</b><em>Clique aqui para saber como funciona o MMR, as pontuações, categorias e regras da temporada premiada.</em></span><span class="seasonArrow">→</span></a>`;
  const storeCta = `<a class="storeCta" href="${storeHref}"><span class="storeGlow"></span><span class="storeIcon">🛒</span><span class="storeCopy"><small>LOJINHA OFICIAL</small><b>Compre seu VIP aqui</b><em>PIX ou cartão • entrega automática no Rust + cargo no Discord</em></span><span class="storeArrow">→</span></a>`;

  return renderBaseHome(req)
    .replace("</head>", `${brandThemeCss}</head>`)
    .replace("</style>", `.homeMedia{position:relative;margin:0 auto 34px;border:1px solid #72502b;border-radius:24px;overflow:hidden;background:#0a070c;box-shadow:0 28px 80px #0009;aspect-ratio:16/9}.homeMedia img{display:block;width:100%;height:100%;object-fit:cover}.homeMedia:after{content:'';position:absolute;inset:0;box-shadow:inset 0 0 60px #0008;pointer-events:none}.seasonCta,.storeCta{position:relative;overflow:hidden;max-width:850px;margin:30px auto 18px;display:flex;align-items:center;gap:17px;text-decoration:none;color:#fff;padding:20px 22px;border-radius:22px;box-shadow:0 22px 60px #0008,inset 0 1px #fff1;transition:transform .2s,border-color .2s,box-shadow .2s;isolation:isolate}.seasonCta{border:1px solid #7046a0;background:linear-gradient(120deg,#180d24 0%,#21122f 48%,#271709 100%);box-shadow:0 22px 60px #0008,0 0 42px #8b5cf615}.seasonCta:hover{transform:translateY(-3px);border-color:#ab7cdd;box-shadow:0 28px 72px #0009,0 0 38px #9b6cff30}.storeCta{margin-top:18px;margin-bottom:34px;border:1px solid #9b6a2d;background:linear-gradient(120deg,#271709 0%,#17100f 42%,#17101f 72%,#251431 100%)}.storeCta:hover{transform:translateY(-3px);border-color:#e0a748;box-shadow:0 28px 72px #0009,0 0 34px #c98a2930}.seasonGlow,.storeGlow{position:absolute;width:230px;height:230px;border-radius:50%;right:-80px;top:-100px;z-index:-1}.seasonGlow{background:radial-gradient(circle,#9b6cff66 0%,#8b5cf615 45%,transparent 70%)}.storeGlow{background:radial-gradient(circle,#8b5cf655 0%,#8b5cf610 45%,transparent 70%)}.seasonIcon,.storeIcon{width:60px;height:60px;flex:0 0 60px;border-radius:18px;display:grid;place-items:center;font-size:29px;box-shadow:inset 0 1px #fff2,0 8px 24px #0006}.seasonIcon{background:linear-gradient(145deg,#301b45,#160d20);border:1px solid #8054aa}.storeIcon{background:linear-gradient(145deg,#402910,#201309);border:1px solid #a16e2b}.seasonCopy,.storeCopy{display:flex;flex-direction:column;min-width:0}.seasonCopy small,.storeCopy small{font-size:10px;letter-spacing:.2em;font-weight:950}.seasonCopy small{color:#d9bfff}.storeCopy small{color:#efbd65}.seasonCopy b,.storeCopy b{font-size:24px;letter-spacing:-.02em;margin:4px 0 3px}.seasonCopy em,.storeCopy em{font-size:12px;color:#b5a9be;font-style:normal;line-height:1.45}.seasonArrow,.storeArrow{margin-left:auto;color:#ffd84d;font-size:28px;font-weight:950;transition:transform .2s}.seasonCta:hover .seasonArrow,.storeCta:hover .storeArrow{transform:translateX(4px)}@media(max-width:700px){.homeMedia{margin-bottom:28px;border-radius:18px}.nav{margin-bottom:36px!important}.seasonCta,.storeCta{margin:22px 0 16px;padding:17px;border-radius:19px;gap:13px}.storeCta{margin-top:12px;margin-bottom:28px}.seasonIcon,.storeIcon{width:50px;height:50px;flex-basis:50px;font-size:24px}.seasonCopy small,.storeCopy small{font-size:8px}.seasonCopy b,.storeCopy b{font-size:19px}.seasonCopy em,.storeCopy em{font-size:10px;max-width:240px}.seasonArrow,.storeArrow{font-size:22px}}</style>`)
    .replace("</nav>", `</nav><div class="homeMedia"><img src="${heroRawUrl}" alt="Guerra Fria 2X"></div>`)
    .replace('</section><section class="choices">', `</section>${seasonCta}${storeCta}<section class="choices">`);
}
