export const panelServerControlJs = String.raw`
(function(){
  const $=id=>document.getElementById(id);let timer=null,consoleTimer=null,consoleAfter=0,currentDirectory='/';
  async function api(url,opt){const r=await fetch(url,opt||{});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||('Erro '+r.status));return d}
  const post=data=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  function toast(msg,bad){const t=$('toast');if(!t)return alert(msg);t.textContent=msg;t.classList.remove('hidden');t.style.borderColor=bad?'#943540':'#9b692c';setTimeout(()=>t.classList.add('hidden'),5000)}
  function stateLabel(state){return ({running:'Online',offline:'Desligado',starting:'Iniciando',stopping:'Desligando'}[state]||state||'Indisponível')}
  function create(){const main=document.querySelector('.main');if(!main||$('serverControl'))return;const view=document.createElement('section');view.id='serverControl';view.className='view';view.innerHTML=
    '<div class="section"><div class="body"><div class="actionGrid"><button class="btn yellow" data-host-tab="overview">Visão geral</button><button class="btn" data-host-tab="console">Console da hospedagem</button><button class="btn" data-host-tab="files">Gerenciador de arquivos</button></div></div></div>'+
    '<div class="section serverPane" data-host-pane="overview" style="margin-top:16px"><div class="sectionHead"><div><h2>Servidor</h2><div class="subtitle">Energia, reinícios e estado da hospedagem em um só lugar.</div></div><span id="serverPowerBadge" class="badge yellow">CARREGANDO</span></div><div class="body">'+
    '<div class="cards"><div class="card accent"><small>ESTADO ATUAL</small><strong id="serverPowerState">—</strong></div><div class="card"><small>TEMPO ONLINE</small><strong id="serverUptime">—</strong></div><div class="card"><small>REDE ↓ ENTRADA</small><strong id="serverNetworkRx">—</strong></div><div class="card"><small>REDE ↑ SAÍDA</small><strong id="serverNetworkTx">—</strong></div><div class="card"><small>SEGURANÇA DE REDE</small><strong id="serverSecurity">Analisando</strong></div><div class="card"><small>REINÍCIO AGENDADO</small><strong id="serverRestartState">Nenhum</strong></div></div>'+
    '<div id="serverPowerNotice" class="stateCard" style="margin-top:14px"><b>Controle seguro da host</b><small>As ações só são confirmadas depois que o Pterodactyl informa o novo estado.</small></div>'+
    '<div class="actionGrid" style="margin-top:12px"><button id="serverStart" class="btn yellow">▶ Ligar servidor</button><button id="serverRestart" class="btn">↻ Reiniciar agora</button><button id="serverStop" class="btn red">■ Desligar servidor</button><button id="serverRefresh" class="btn">Atualizar estado</button></div></div></div>'+
    '<div class="section serverPane" data-host-pane="overview" style="margin-top:16px"><div class="sectionHead"><div><h2>Reinício com aviso</h2><div class="subtitle">Avisa os jogadores no chat antes de reiniciar.</div></div><span class="badge green">RCON + HOST</span></div><div class="body"><div class="field"><label>Antecedência do aviso</label><select id="serverWarningMinutes"><option value="5">5 minutos</option><option value="15">15 minutos</option><option value="1">1 minuto</option></select><small>O bot envia o primeiro aviso agora e reforça a contagem antes do reinício.</small></div><button id="serverWarningRestart" class="btn yellow" style="width:100%">Agendar reinício com aviso</button></div></div>'+
    '<div class="section serverPane" data-host-pane="console" style="display:none;margin-top:16px"><div class="sectionHead"><div><h2>Console da hospedagem</h2><div class="subtitle">Saída ao vivo diretamente do WebSocket do Pterodactyl.</div></div><span id="hostConsoleBadge" class="badge yellow">CONECTANDO</span></div><div class="body"><div id="hostConsoleOutput" style="height:480px;overflow:auto;background:#050505;border:1px solid #49351e;border-radius:14px;padding:14px;color:#ddd;font:12px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace;white-space:pre-wrap;word-break:break-word">Aguardando o console…</div><div class="actionGrid" style="margin-top:10px"><input id="hostConsoleCommand" placeholder="Digite um comando para o console da host" autocomplete="off"><button id="hostConsoleSend" class="btn yellow">Enviar comando</button><button id="hostConsoleClear" class="btn">Limpar tela</button></div></div></div>'+
    '<div class="section serverPane" data-host-pane="files" style="display:none;margin-top:16px"><div class="sectionHead"><div><h2>Gerenciador de arquivos</h2><div class="subtitle">Envie, crie e remova arquivos diretamente no servidor.</div></div><span class="badge red">ACESSO CRÍTICO</span></div><div class="body"><div class="stateCard"><b id="hostFilePath">/</b><small>Caminho atual na hospedagem</small></div><div class="actionGrid" style="margin-top:10px"><button id="hostFileUp" class="btn">⬆ Voltar</button><button id="hostFileRefresh" class="btn">Atualizar</button><button id="hostFolderCreate" class="btn">Nova pasta</button><label class="btn yellow" style="text-align:center;cursor:pointer">Enviar arquivo<input id="hostFileUpload" type="file" style="display:none"></label></div><div id="hostFileList" style="display:grid;gap:8px;margin-top:12px"><div class="empty">Carregando arquivos…</div></div></div></div>';
    main.appendChild(view);$('serverStart').onclick=()=>power('start');$('serverStop').onclick=()=>power('stop');$('serverRestart').onclick=()=>power('restart');$('serverRefresh').onclick=load;$('serverWarningRestart').onclick=schedule;view.querySelectorAll('[data-host-tab]').forEach(b=>b.onclick=()=>hostTab(b.dataset.hostTab));$('hostConsoleSend').onclick=sendConsole;$('hostConsoleClear').onclick=()=>{$('hostConsoleOutput').textContent='';consoleAfter=0};$('hostConsoleCommand').onkeydown=e=>{if(e.key==='Enter')sendConsole()};$('hostFileRefresh').onclick=loadFiles;$('hostFileUp').onclick=()=>{if(currentDirectory!=='/'){currentDirectory=currentDirectory.split('/').slice(0,-1).join('/')||'/';loadFiles()}};$('hostFolderCreate').onclick=createFolder;$('hostFileUpload').onchange=uploadFile;
  }
  function nav(){for(const id of ['nav','mobileNav']){const box=$(id);if(!box||box.querySelector('[data-server-control]'))continue;const b=document.createElement('button');b.type='button';b.textContent='🖥 Servidor';b.dataset.serverControl='1';b.dataset.view='serverControl';b.onclick=open;box.appendChild(b)}}
  function open(){create();nav();document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$('serverControl').classList.add('active');document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='serverControl'));if($('pageTitle'))$('pageTitle').textContent='Configurações do Servidor';load()}
  function uptime(ms){let s=Math.floor(Number(ms||0)/1000),d=Math.floor(s/86400);s%=86400;const h=Math.floor(s/3600),m=Math.floor(s%3600/60);return (d?d+'d ':'')+h+'h '+m+'min'}
  async function load(){try{const d=await api('/api/admin/server/power/status',{cache:'no-store'}),state=String(d.state||'unknown');$('serverPowerState').textContent=stateLabel(state);$('serverUptime').textContent=state==='running'?uptime(d.uptime):'—';$('serverNetworkRx').textContent=Number(d.network?.rxMbps||0).toFixed(2)+' Mbps';$('serverNetworkTx').textContent=Number(d.network?.txMbps||0).toFixed(2)+' Mbps';const suspect=d.security?.status==='suspected';$('serverSecurity').textContent=suspect?'⚠ Possível ataque':'✓ Tráfego normal';$('serverSecurity').style.color=suspect?'#ff6b6b':'#57d68d';$('serverPowerBadge').textContent=stateLabel(state).toUpperCase();$('serverPowerBadge').className='badge '+(state==='running'?'green':state==='offline'?'red':'yellow');$('serverStart').disabled=state==='running';$('serverStop').disabled=state==='offline';if(d.scheduledRestart){const when=new Date(d.scheduledRestart.executeAt);$('serverRestartState').textContent=when.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});$('serverPowerNotice').innerHTML='<b>Reinício com aviso programado</b><small>Solicitado por '+String(d.scheduledRestart.requestedBy||'Administrador')+' para '+when.toLocaleString('pt-BR')+'.</small>'}else if(suspect){$('serverRestartState').textContent='Nenhum';$('serverPowerNotice').innerHTML='<b>⚠ Tráfego de entrada anormal</b><small>Possível ataque detectado. Confirme o evento e a mitigação no painel da hospedagem.</small>'}else{$('serverRestartState').textContent='Nenhum';$('serverPowerNotice').innerHTML='<b>Monitoramento ativo</b><small>Rede estável. O detector compara picos consecutivos com a média normal do servidor.</small>'}}catch(e){$('serverPowerBadge').textContent='FALHA';$('serverPowerBadge').className='badge red';toast(e.message,true)}}
  async function power(signal){const labels={start:'ligar',stop:'desligar',restart:'reiniciar'};if(!confirm('Deseja realmente '+labels[signal]+' o servidor agora?'))return;const buttons=[$('serverStart'),$('serverStop'),$('serverRestart')];buttons.forEach(b=>b.disabled=true);try{await api('/api/admin/server/power',post({signal}));toast('Ação confirmada pela host.');await load()}catch(e){toast(e.message,true);await load()}finally{buttons.forEach(b=>b.disabled=false)}}
  async function schedule(){const minutes=Number($('serverWarningMinutes').value);if(!confirm('Avisar no jogo e reiniciar o servidor em '+minutes+' minuto(s)?'))return;const b=$('serverWarningRestart');b.disabled=true;try{const d=await api('/api/admin/server/restart-warning',post({minutes}));toast('Aviso enviado. Reinício agendado.');await load()}catch(e){toast(e.message,true)}finally{b.disabled=false}}
  function hostTab(name){document.querySelectorAll('.serverPane').forEach(p=>p.style.display=p.dataset.hostPane===name?'block':'none');document.querySelectorAll('[data-host-tab]').forEach(b=>b.classList.toggle('yellow',b.dataset.hostTab===name));if(name==='console'){loadConsole();if(!consoleTimer)consoleTimer=setInterval(()=>{$('serverControl')?.classList.contains('active')&&document.querySelector('[data-host-pane="console"]')?.style.display!=='none'&&loadConsole()},1500)}if(name==='files')loadFiles()}
  async function loadConsole(){try{const d=await api('/api/admin/server/host-console?after='+consoleAfter,{cache:'no-store'}),out=$('hostConsoleOutput');$('hostConsoleBadge').textContent=d.connected?'AO VIVO':'DESCONECTADO';$('hostConsoleBadge').className='badge '+(d.connected?'green':'red');if(d.lines?.length){if(out.textContent==='Aguardando o console…'||out.dataset.error==='1')out.textContent='';out.dataset.error='0';out.textContent+=(out.textContent?'\n':'')+d.lines.map(line=>line.text).join('\n');consoleAfter=d.lastId||consoleAfter;out.scrollTop=out.scrollHeight}}catch(e){$('hostConsoleBadge').textContent='FALHA';$('hostConsoleBadge').className='badge red';const out=$('hostConsoleOutput');out.dataset.error='1';out.textContent='Falha ao conectar ao console da hospedagem:\n\n'+e.message+'\n\nO sistema tentará conectar novamente automaticamente.'}}
  async function sendConsole(){const input=$('hostConsoleCommand'),command=input.value.trim();if(!command)return;const b=$('hostConsoleSend');b.disabled=true;try{await api('/api/admin/server/host-console/command',post({command}));input.value='';await loadConsole()}catch(e){toast(e.message,true)}finally{b.disabled=false}}
  function bytes(n){n=Number(n||0);if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';if(n<1073741824)return(n/1048576).toFixed(1)+' MB';return(n/1073741824).toFixed(1)+' GB'}
  async function loadFiles(){try{const d=await api('/api/admin/server/host-files?directory='+encodeURIComponent(currentDirectory),{cache:'no-store'});currentDirectory=d.directory;$('hostFilePath').textContent=currentDirectory;$('hostFileList').innerHTML=d.entries?.length?d.entries.sort((a,b)=>Number(b.directory)-Number(a.directory)||a.name.localeCompare(b.name)).map(entry=>'<div class="stateCard" style="display:flex;align-items:center;justify-content:space-between;gap:8px"><button class="btn" style="flex:1;text-align:left" data-file-open="'+esc(entry.name)+'" data-directory="'+entry.directory+'">'+(entry.directory?'📁 ':'📄 ')+esc(entry.name)+'<small style="display:block">'+(entry.directory?'Pasta':bytes(entry.size))+'</small></button><button class="btn red" data-file-delete="'+esc(entry.name)+'">Apagar</button></div>').join(''):'<div class="empty">Pasta vazia.</div>';$('hostFileList').querySelectorAll('[data-file-open]').forEach(b=>b.onclick=()=>{if(b.dataset.directory==='true'){currentDirectory=(currentDirectory==='/'?'':currentDirectory)+'/'+b.dataset.fileOpen;loadFiles()}});$('hostFileList').querySelectorAll('[data-file-delete]').forEach(b=>b.onclick=()=>deleteFile(b.dataset.fileDelete))}catch(e){toast(e.message,true)}}
  async function deleteFile(name){if(!confirm('APAGAR DA HOSPEDAGEM?\n\n'+currentDirectory+'/'+name+'\n\nEsta ação não pode ser desfeita.'))return;try{await api('/api/admin/server/host-files/delete',post({directory:currentDirectory,files:[name]}));toast('Arquivo ou pasta removido.');loadFiles()}catch(e){toast(e.message,true)}}
  async function createFolder(){const name=prompt('Nome da nova pasta:');if(!name)return;try{await api('/api/admin/server/host-files/folder',post({directory:currentDirectory,name}));toast('Pasta criada.');loadFiles()}catch(e){toast(e.message,true)}}
  function readBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]||'');reader.onerror=()=>reject(new Error('Falha ao ler arquivo.'));reader.readAsDataURL(file)})}
  async function uploadFile(e){const file=e.target.files?.[0];if(!file)return;if(file.size>12*1024*1024){toast('O arquivo deve ter no máximo 12 MB.',true);e.target.value='';return}try{toast('Enviando '+file.name+'…');await api('/api/admin/server/host-files/upload',post({directory:currentDirectory,name:file.name,base64:await readBase64(file)}));toast('Arquivo enviado com sucesso.');loadFiles()}catch(error){toast(error.message,true)}finally{e.target.value=''}}
  function boot(){create();nav();setInterval(nav,2000);timer=setInterval(()=>{if($('serverControl')?.classList.contains('active'))load()},5000)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
`;
