export const panelIntegrityManagerJs = String.raw`
(function(){'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const fmt=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('pt-BR')};
let records=[];
let filter='all';

function ensureStyles(){if(document.getElementById('integrityManagerStyle'))return;const s=document.createElement('style');s.id='integrityManagerStyle';s.textContent='.integrityTools{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px}.integrityFilters{display:flex;gap:6px;flex-wrap:wrap}.integrityFilters button{border:1px solid #3d2e50;background:#0b0810;color:#a99db5;border-radius:999px;padding:7px 11px;font-weight:850}.integrityFilters button.active{background:#2b193d;color:#fff;border-color:#714fa0}.integrityGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:12px}.integrityRecord{border:1px solid #30243f;background:linear-gradient(145deg,#120d19,#0c0911);border-radius:15px;padding:14px;position:relative;overflow:hidden}.integrityRecord.warn{border-left:4px solid #ff9a2f}.integrityRecord.ban{border-left:4px solid #ef4444}.integrityRecord.verify{border-left:4px solid #22c55e}.integrityRecord.hiddenRecord{opacity:.62}.integrityTitle{display:flex;justify-content:space-between;gap:8px;align-items:start}.integrityTitle b{font-size:16px}.integrityMeta{display:flex;gap:6px;flex-wrap:wrap;margin:10px 0}.integrityPill{border:1px solid #3b2c4b;border-radius:999px;padding:4px 8px;color:#a99db5;font-size:10px}.integrityReason{color:#d5ccdf;line-height:1.45;font-size:13px;min-height:38px}.integrityActions{display:flex;justify-content:flex-end;margin-top:12px}.integrityStatus{font-size:9px;font-weight:900;letter-spacing:.08em;padding:4px 7px;border-radius:999px}.integrityStatus.visible{color:#7ce5a3;border:1px solid #285f3d}.integrityStatus.hidden{display:inline-block!important;color:#ff9aa3;border:1px solid #76303a}.integrityMessage{margin-top:10px;color:#9f94ab;font-size:12px}@media(max-width:760px){.integrityTools{grid-template-columns:1fr}.integrityGrid{grid-template-columns:1fr}}';document.head.appendChild(s)}

function ensurePage(){ensureStyles();const main=document.querySelector('.main');if(!main||document.getElementById('integrityAdmin'))return;const sec=document.createElement('section');sec.id='integrityAdmin';sec.className='view';sec.innerHTML='<div class="section"><div class="sectionHead"><div><h2>Gerenciar Central de Integridade</h2><div class="subtitle">Controle o que aparece publicamente em Punições e Verificações sem apagar o histórico administrativo.</div></div><span class="badge green">Histórico preservado</span></div><div class="body"><div class="integrityTools"><input id="integritySearch" placeholder="Pesquisar jogador, SteamID, administrador ou motivo"><div class="integrityFilters"><button data-ifilter="all" class="active">Todos</button><button data-ifilter="punishments">Punições</button><button data-ifilter="verifications">Verificações</button><button data-ifilter="hidden">Ocultos</button></div></div><div id="integrityMessage" class="integrityMessage"></div><div id="integrityGrid" class="integrityGrid"></div></div></div>';main.appendChild(sec);document.getElementById('integritySearch').addEventListener('input',render);sec.querySelectorAll('[data-ifilter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.ifilter;sec.querySelectorAll('[data-ifilter]').forEach(x=>x.classList.toggle('active',x===b));render()}))}

function ensureNav(){for(const id of ['nav','mobileNav']){const box=document.getElementById(id);if(!box||box.querySelector('[data-integrity-manager]'))continue;const b=document.createElement('button');b.textContent='Integridade';b.dataset.integrityManager='1';b.dataset.view='integrityAdmin';b.onclick=()=>openPage();box.appendChild(b)}}

async function api(url,opt){const r=await fetch(url,opt||{});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||('Erro '+r.status));return j}
async function load(){const msg=document.getElementById('integrityMessage');if(msg)msg.textContent='Carregando registros...';try{const d=await api('/api/admin/integrity/records');records=d.records||[];if(msg)msg.textContent=records.length+' registros administrativos encontrados.';render()}catch(e){if(msg)msg.textContent='Erro: '+e.message}}

function label(a){a=String(a||'').toUpperCase();return a==='BAN'?'BANIMENTO':a==='WARN'?'ADVERTÊNCIA':a==='VERIFICAR'?'VERIFICAÇÃO':a}
function cls(a){a=String(a||'').toUpperCase();return a==='BAN'?'ban':a==='WARN'?'warn':'verify'}
function render(){const grid=document.getElementById('integrityGrid');if(!grid)return;const q=(document.getElementById('integritySearch')?.value||'').trim().toLowerCase();let rows=records.filter(r=>{const a=String(r.action||'').toUpperCase();if(filter==='punishments'&&!['BAN','WARN'].includes(a))return false;if(filter==='verifications'&&a!=='VERIFICAR')return false;if(filter==='hidden'&&r.publicVisible!==false)return false;return !q||[r.playerName,r.steamId,r.adminName,r.reason,a].some(v=>String(v||'').toLowerCase().includes(q))});grid.innerHTML=rows.length?rows.map(r=>'<article class="integrityRecord '+cls(r.action)+' '+(r.publicVisible===false?'hiddenRecord':'')+'"><div class="integrityTitle"><div><span class="integrityStatus '+(r.publicVisible===false?'hidden':'visible')+'">'+(r.publicVisible===false?'OCULTO':'PÚBLICO')+'</span><div style="margin-top:8px"><b>'+esc(label(r.action))+' • '+esc(r.playerName||'Jogador')+'</b></div></div><span class="integrityPill">#'+esc(r.id)+'</span></div><div class="integrityMeta"><span class="integrityPill">SteamID: '+esc(r.steamId)+'</span><span class="integrityPill">Responsável: '+esc(r.adminName||'Administração')+'</span><span class="integrityPill">'+esc(fmt(r.createdAt))+'</span></div><div class="integrityReason">'+esc(r.reason||'Sem motivo informado.')+'</div><div class="integrityActions"><button class="btn '+(r.publicVisible===false?'green':'red')+'" data-record-id="'+esc(r.id)+'" data-visible="'+(r.publicVisible===false?'true':'false')+'">'+(r.publicVisible===false?'Restaurar na Central':'Ocultar da Central')+'</button></div></article>').join(''):'<div class="empty">Nenhum registro encontrado.</div>';grid.querySelectorAll('[data-record-id]').forEach(b=>b.onclick=()=>changeVisibility(Number(b.dataset.recordId),b.dataset.visible==='true'))}

async function changeVisibility(id,visible){if(!confirm(visible?'Restaurar este registro na página pública?':'Ocultar este registro da página pública? O histórico administrativo será preservado.'))return;const msg=document.getElementById('integrityMessage');try{await api('/api/admin/integrity/records/'+id+'/visibility',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visible})});const r=records.find(x=>Number(x.id)===id);if(r)r.publicVisible=visible;if(msg)msg.textContent=visible?'Registro restaurado na Central de Integridade.':'Registro ocultado da Central de Integridade.';render()}catch(e){if(msg)msg.textContent='Erro: '+e.message}}

function openPage(){ensurePage();document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById('integrityAdmin')?.classList.add('active');document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='integrityAdmin'));const title=document.getElementById('pageTitle');if(title)title.textContent='Integridade';load()}

const timer=setInterval(()=>{ensurePage();ensureNav();if(document.getElementById('nav')?.children.length)clearInterval(timer)},300);setTimeout(()=>{ensurePage();ensureNav()},1200);
})();`;
