export const panelWipeJs = String.raw`
(function(){
  const $=id=>document.getElementById(id);let currentKind='map',lastPlan=null,lockState=null;
  function toast(msg,bad){const t=$('toast');if(!t)return alert(msg);t.textContent=msg;t.classList.remove('hidden');t.style.borderColor=bad?'#943540':'#9b692c';setTimeout(()=>t.classList.add('hidden'),5000)}
  async function api(url,opt){const r=await fetch(url,opt||{});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||('Erro '+r.status));return d}
  const body=data=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const date=v=>v?new Date(v).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',weekday:'long',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—';
  function selectedSchedule(){const value=$('voteDate')?.value;if(!value)return null;const voteAt=Date.parse(value+'T18:00:00-03:00');return Number.isFinite(voteAt)?{voteEndsAt:voteAt,wipeAt:voteAt+25*60*1000}:null}
  function readImage(file){return new Promise((resolve,reject)=>{if(!file)return resolve(undefined);if(!/^image\/(png|jpeg|webp|gif)$/i.test(file.type))return reject(new Error('Use uma imagem PNG, JPG, WEBP ou GIF.'));if(file.size>5*1024*1024)return reject(new Error('Cada imagem pode ter no máximo 5 MB.'));const reader=new FileReader();reader.onload=()=>resolve({name:file.name,mime:file.type,data:String(reader.result)});reader.onerror=()=>reject(new Error('Não foi possível ler a imagem.'));reader.readAsDataURL(file)})}
  function create(){const main=document.querySelector('.main');if(!main||$('wipeAdmin'))return;const view=document.createElement('section');view.id='wipeAdmin';view.className='view';view.innerHTML=
    '<div class="section"><div class="sectionHead"><div><h2>🔥 Central de Wipe</h2><div class="subtitle">Votação, mapas, automação e execução manual em um só lugar.</div></div><span id="wipeMode" class="badge yellow">CARREGANDO</span></div><div class="body">'+
    '<div class="cards"><div class="card"><small>API ELGAE</small><strong id="wipeApi">—</strong></div><div class="card"><small>SERVIDOR</small><strong id="wipeState">—</strong></div><div class="card"><small>MAPA VIA STARTUP</small><strong id="wipeStartup">—</strong></div><div class="card accent"><small>AUTOMAÇÃO</small><strong id="wipeLock">—</strong></div></div>'+
    '<div id="wipeLockBox" class="stateCard" style="margin-top:14px"><b>Carregando trava…</b><small>A trava bloqueia qualquer exclusão de arquivos.</small></div><div class="actionGrid" style="margin-top:10px"><button id="wipeToggleLock" class="btn red">Carregando…</button><button id="wipeDiagnostic" class="btn">Atualizar diagnóstico</button><button id="wipeRefresh" class="btn">Atualizar votações</button></div></div></div>'+

    '<div class="section" style="margin-top:16px"><div class="sectionHead"><div><h2>🗳️ Criar votação de mapa</h2><div class="subtitle">Escolha a data. Votação às 18h e fluxo do wipe às 18h25.</div></div><span class="badge green">DISCORD</span></div><div class="body">'+
    '<div class="field"><label>Data da votação e do wipe</label><input id="voteDate" type="date"><small>Encerramento: 18h • início técnico do wipe: 18h25 • horário de São Paulo.</small></div>'+
    '<div id="nextWipeGuard" class="stateCard" style="margin-bottom:14px;border-color:#9b692c"><b>🛡️ Wipe protegido</b><small>Nenhuma ação será executada antes da data escolhida às 18h25.</small></div>'+
    [1,2,3].map(n=>'<div class="stateCard" style="margin-bottom:10px"><b>Mapa '+n+'</b><div class="actionGrid"><div class="field"><label>Seed</label><input id="voteSeed'+n+'" type="number" min="0" max="2147483647" inputmode="numeric" placeholder="Ex.: 123456789"></div><div class="field"><label>Size</label><input id="voteSize'+n+'" type="number" min="1000" max="6000" inputmode="numeric" placeholder="Ex.: 3500"></div></div><div class="field"><label>Imagem do mapa (arquivo opcional)</label><input id="voteImage'+n+'" type="file" accept="image/png,image/jpeg,image/webp,image/gif"><small>PNG, JPG, WEBP ou GIF • máximo 5 MB</small></div></div>').join('')+
    '<button id="createMapVote" class="btn yellow" style="width:100%">Revisar data e publicar votação</button></div></div>'+

    '<div class="section" style="margin-top:16px"><div class="sectionHead"><div><h2>📅 Votação e próximo wipe</h2><div class="subtitle">Acompanhe vencedor, horários, aplicação e eventuais falhas.</div></div><span id="voteStatusBadge" class="badge">SEM VOTAÇÃO</span></div><div id="voteStatus" class="body"><div class="empty">Nenhuma votação carregada.</div></div></div>'+

    '<div class="section" style="margin-top:16px"><div class="sectionHead"><div><h2>🧊 Wipe manual</h2><div class="subtitle">Mesmas funções /wipe mapa e /wipe geral.</div></div><span class="badge red">AÇÃO CRÍTICA</span></div><div class="body">'+
    '<div class="field"><label>Tipo</label><select id="wipeKind"><option value="map">Wipe mapa — mantém BPs</option><option value="general">Wipe geral — mapa + BPs</option></select></div>'+
    '<div class="field"><label>Link do novo mapa</label><input id="wipeRustMaps" type="url" placeholder="https://rustmaps.com/... ou download .map"></div>'+
    '<button id="wipePlan" class="btn">1. Validar e visualizar plano</button>'+
    '<div id="wipePlanSummary" class="stateCard" style="margin-top:12px"><b>Nenhum plano validado</b><small>O botão de execução só será liberado depois da simulação.</small></div>'+
    '<div id="wipeFiles" style="margin-top:10px"></div>'+
    '<div class="field"><label>Confirmação obrigatória</label><input id="wipeConfirmation" autocomplete="off" placeholder="Digite WIPE GUERRA FRIA"></div>'+
    '<button id="wipeExecute" class="btn red" disabled style="width:100%;opacity:.55">2. Executar wipe</button></div></div>';
    main.appendChild(view);$('wipeToggleLock').onclick=toggleLock;$('wipeDiagnostic').onclick=diagnostic;$('wipeRefresh').onclick=loadVotes;$('createMapVote').onclick=createVote;$('wipePlan').onclick=plan;$('wipeExecute').onclick=executeWipe;$('wipeKind').onchange=e=>{currentKind=e.target.value;invalidatePlan()};$('wipeRustMaps').oninput=invalidatePlan;$('wipeConfirmation').oninput=syncExecute;
  }
  function nav(){for(const id of ['nav','mobileNav']){const box=$(id);if(!box||box.querySelector('[data-wipe]'))continue;const b=document.createElement('button');b.type='button';b.textContent='🔥 Wipe';b.dataset.wipe='1';b.dataset.view='wipeAdmin';b.onclick=open;box.appendChild(b)}}
  function open(){create();nav();document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$('wipeAdmin').classList.add('active');document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='wipeAdmin'));if($('pageTitle'))$('pageTitle').textContent='Central de Wipe';diagnostic();loadLock();loadVotes()}
  async function loadLock(){try{lockState=await api('/api/admin/wipe/lock',{cache:'no-store'});$('wipeLockBox').innerHTML=lockState.unlocked?'<b>🔓 Sistema de wipe destravado</b><small>Execuções automáticas e manuais estão liberadas.</small>':'<b>🔒 Sistema de wipe travado</b><small>Nenhum arquivo poderá ser apagado até você destravar.</small>';$('wipeToggleLock').textContent=lockState.unlocked?'🔒 Travar sistema de wipe':'🔓 Destravar sistema de wipe';$('wipeToggleLock').className='btn '+(lockState.unlocked?'red':'yellow')}catch(e){toast(e.message,true)}}
  async function toggleLock(){if(!lockState)return;if(!confirm(lockState.unlocked?'Travar agora todas as execuções de wipe?':'Destravar as execuções de wipe? Um wipe vencido e pendente poderá iniciar imediatamente.'))return;const b=$('wipeToggleLock');b.disabled=true;try{lockState=await api('/api/admin/wipe/lock',body({unlocked:!lockState.unlocked}));toast(lockState.unlocked?'Sistema de wipe destravado.':'Sistema de wipe travado.');await loadLock();await diagnostic()}catch(e){toast(e.message,true)}finally{b.disabled=false}}
  async function diagnostic(){const b=$('wipeDiagnostic');b.disabled=true;try{const d=await api('/api/admin/wipe/diagnostic',{cache:'no-store'});$('wipeApi').textContent=d.connected?'Conectada':'Falha';$('wipeState').textContent=d.server?.state||'—';$('wipeStartup').textContent=d.capabilities?.proceduralStartup?((d.seedVariable||'seed')+' + '+(d.sizeVariable||'size')):'Seed/size ausentes';const active=d.capabilities?.destructiveEnabled&&d.capabilities?.automationEnabled&&d.capabilities?.wipeUnlocked;$('wipeLock').textContent=active?'Destravada':'Travada';$('wipeMode').textContent=active?'AUTOMAÇÃO ATIVA':'WIPE TRAVADO';$('wipeMode').className='badge '+(active?'green':'red')}catch(e){$('wipeApi').textContent='Falha';toast(e.message,true)}finally{b.disabled=false}}
  async function createVote(){const b=$('createMapVote');b.disabled=true;b.textContent='Preparando imagens…';try{const schedule=selectedSchedule();if(!schedule)throw new Error('Escolha a data do wipe.');const data={date:$('voteDate').value,expectedWipeAt:schedule.wipeAt};for(let n=1;n<=3;n++){data['seed'+n]=Number($('voteSeed'+n).value);data['size'+n]=Number($('voteSize'+n).value);if(!Number.isInteger(data['seed'+n])||!Number.isInteger(data['size'+n]))throw new Error('Preencha seed e size dos três mapas.');data['image'+n]=await readImage($('voteImage'+n).files?.[0])}const message='CONFIRME A AGENDA\n\nEncerramento da votação:\n'+date(schedule.voteEndsAt)+'\n\nInício do wipe:\n'+date(schedule.wipeAt)+'\n\nO mapa vencedor será aplicado por seed e size. Deseja publicar agora?';if(!confirm(message))return;b.textContent='Validando Pterodactyl e publicando…';const d=await api('/api/admin/wipe/vote',body(data));toast('Votação publicada. Wipe confirmado para '+date(d.wipeAt)+'.');for(let n=1;n<=3;n++){$('voteSeed'+n).value='';$('voteSize'+n).value='';$('voteImage'+n).value=''}loadVotes()}catch(e){toast(e.message,true)}finally{b.disabled=false;b.textContent='Revisar data e publicar votação'}}
  async function loadVotes(){try{const d=await api('/api/admin/wipe/status',{cache:'no-store'}),v=d.votes?.[0];if(!v){$('voteStatus').innerHTML='<div class="empty">Nenhuma votação registrada.</div>';return}$('voteStatusBadge').textContent=String(v.status||'—').toUpperCase();const winner=v.winnerIndex==null?null:v.maps?.[v.winnerIndex];$('voteStatus').innerHTML='<div class="cards"><div class="card"><small>STATUS</small><strong>'+esc(v.status)+'</strong></div><div class="card"><small>RESULTADO / WIPE</small><strong>'+date(v.wipeAt)+'</strong></div><div class="card accent"><small>VENCEDOR</small><strong>'+esc(winner?.name||'Aguardando')+'</strong></div></div>'+(v.failureReason?'<div class="stateCard" style="border-color:#943540;margin-top:12px"><b>Falha registrada</b><small>'+esc(v.failureReason)+'</small></div>':'')+'<div style="display:grid;gap:8px;margin-top:12px">'+(v.maps||[]).map((m,i)=>'<div class="stateCard"><b>'+(i===v.winnerIndex?'🏆 ':'')+esc(m.name)+'</b><small>Seed: '+esc(m.seed)+' • Size: '+esc(m.size)+'</small></div>').join('')+'</div>'}catch(e){toast(e.message,true)}}
  function invalidatePlan(){lastPlan=null;$('wipePlanSummary').innerHTML='<b>Plano precisa ser validado</b><small>O tipo ou link do mapa foi alterado.</small>';syncExecute()}
  async function plan(){const b=$('wipePlan'),link=$('wipeRustMaps').value.trim();if(!link)return toast('Informe o link do mapa.',true);b.disabled=true;b.textContent='Validando…';try{const d=await api('/api/admin/wipe/plan?kind='+encodeURIComponent(currentKind)+'&rustmaps='+encodeURIComponent(link),{cache:'no-store'});lastPlan={kind:currentKind,link};$('wipePlanSummary').innerHTML='<b>✅ Plano validado</b><small>'+d.files.length+' arquivos • '+Math.round(d.totalBytes/1048576*100)/100+' MB • '+(currentKind==='general'?'mapa + blueprints':'somente mapa')+'</small>';$('wipeFiles').innerHTML=d.files.slice(0,50).map(f=>'<div class="stateCard" style="margin-bottom:6px"><b>'+esc(f.name)+'</b><small>'+esc(f.path)+'</small></div>').join('');syncExecute();toast('Plano validado. Revise antes de executar.')}catch(e){invalidatePlan();toast(e.message,true)}finally{b.disabled=false;b.textContent='1. Validar e visualizar plano'}}
  function syncExecute(){const ok=lastPlan&&$('wipeConfirmation').value.trim()==='WIPE GUERRA FRIA';$('wipeExecute').disabled=!ok;$('wipeExecute').style.opacity=ok?'1':'.55'}
  async function executeWipe(){if(!lastPlan||$('wipeConfirmation').value.trim()!=='WIPE GUERRA FRIA')return;if(!confirm('CONFIRMA O WIPE DO SERVIDOR? Um backup será criado antes da exclusão.'))return;const b=$('wipeExecute');b.disabled=true;b.textContent='Executando wipe… não feche esta página';try{const d=await api('/api/admin/wipe/execute',body({kind:lastPlan.kind,rustmaps:lastPlan.link,confirmation:'WIPE GUERRA FRIA'}));toast('Wipe concluído e servidor iniciado.');$('wipeConfirmation').value='';invalidatePlan();loadVotes();diagnostic()}catch(e){toast(e.message,true)}finally{b.textContent='2. Executar wipe';syncExecute()}}
  function boot(){create();nav();setInterval(nav,2000)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
`;
