export const panelMultiServerSeasonAddonJs = String.raw`
(function(){'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>{if(!v)return'—';const d=new Date(v);return isNaN(d.getTime())?'—':d.toLocaleString('pt-BR')};
const money=v=>'R$ '+Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
let season=2;
function tokenHeaders(){const token=localStorage.getItem('gf_admin_token')||sessionStorage.getItem('gf_admin_token')||'';return token?{Authorization:'Bearer '+token}:{}}
function installServerSelector(){if(document.getElementById('gfServerSelector'))return;const target=document.querySelector('.topbar,.header,.top,.sidebar')||document.body;const box=document.createElement('div');box.id='gfServerSelector';box.style.cssText='position:fixed;right:18px;top:18px;z-index:99999;background:#0d1117;border:1px solid #39414b;border-radius:12px;padding:10px 12px;box-shadow:0 12px 35px #0009;color:#fff;font:800 11px system-ui';box.innerHTML='<div style="font-size:8px;color:#8b95a3;letter-spacing:.12em;margin-bottom:6px">SERVIDOR ADMINISTRADO</div><select id="gfServerSelect" style="background:#080b0f;color:#fff;border:1px solid #46505c;border-radius:8px;padding:7px 9px;font-weight:800"><option value="solo-duo">Solo/Duo</option><option value="trio">Trio • Em breve</option></select><div id="gfServerState" style="margin-top:6px;color:#86efac;font-size:9px">ATIVO • Solo/Duo</div>';target.appendChild(box);const s=document.getElementById('gfServerSelect');s.value=localStorage.getItem('gf_admin_server')||'solo-duo';const apply=()=>{const v=s.value;localStorage.setItem('gf_admin_server',v);const st=document.getElementById('gfServerState');if(v==='trio'){st.textContent='EM BREVE • aguardando variáveis do Trio';st.style.color='#fbbf24'}else{st.textContent='ATIVO • Solo/Duo';st.style.color='#86efac'};window.GF_ADMIN_SERVER=v;window.dispatchEvent(new CustomEvent('gf-server-change',{detail:{serverId:v}}))};s.onchange=apply;apply()}
function installSeasonResults(){const old=document.getElementById('seasonOfficialAdmin');if(old)old.style.display='none';const host=document.getElementById('seasonRegistrations')||document.querySelector('[data-tab="season"]')||document.body;if(document.getElementById('seasonUnifiedAdmin'))return;const wrap=document.createElement('div');wrap.id='seasonUnifiedAdmin';wrap.innerHTML='<div class="section" style="border-color:#8a641d;margin-top:16px"><div class="sectionHead"><div><h2>🏆 Inscrições Oficiais • Resultados</h2><div class="subtitle">Somente Season do Solo/Duo. Inscrição gratuita desativada.</div></div><div class="toolbar"><select id="seasonUnifiedSelect" class="btn"><option value="2">Season 2</option><option value="1">Season 1</option></select><button class="btn" id="seasonUnifiedRefresh">↻ Atualizar</button></div></div><div class="body"><div class="cards"><div class="card accent"><small>Total</small><strong id="suTotal">—</strong></div><div class="card"><small>Pagos confirmados</small><strong id="suPaid">—</strong></div><div class="card"><small>Pendentes</small><strong id="suPending">—</strong></div><div class="card"><small>Legado/gratuito</small><strong id="suLegacy">—</strong></div><div class="card"><small>Receita confirmada</small><strong id="suRevenue">—</strong></div></div><div class="notice" id="suNotice" style="margin-top:12px">Season vinculada exclusivamente ao servidor Solo/Duo.</div></div><div class="tableWrap"><table class="table" style="min-width:1350px"><thead><tr><th>Pagamento</th><th>Status</th><th>Participante</th><th>Discord</th><th>Steam</th><th>Tipo</th><th>Valor</th><th>ID pagamento</th><th>Pago em</th><th>Inscrito em</th></tr></thead><tbody id="suRows"><tr><td colspan="10"><div class="empty">Carregando...</div></td></tr></tbody></table></div></div>';host.appendChild(wrap);document.getElementById('seasonUnifiedSelect').onchange=e=>{season=Number(e.target.value)||2;loadSeason()};document.getElementById('seasonUnifiedRefresh').onclick=loadSeason;loadSeason()}
async function loadSeason(){try{const r=await fetch('/api/admin/season/registrations-unified?season='+season,{cache:'no-store',headers:tokenHeaders()});const d=await r.json();if(!r.ok)throw new Error(d.error||'Falha ao carregar');const s=d.summary||{};document.getElementById('suTotal').textContent=s.total??0;document.getElementById('suPaid').textContent=s.paid??0;document.getElementById('suPending').textContent=s.pending??0;document.getElementById('suLegacy').textContent=s.legacyOrFree??0;document.getElementById('suRevenue').textContent=money(s.paidTotal);document.getElementById('suNotice').innerHTML='<b>Season '+d.season+'</b> • servidor: <b>Solo/Duo</b> • inscrição gratuita: <b style="color:#86efac">DESATIVADA</b>';const b=document.getElementById('suRows');const rows=d.registrations||[];b.innerHTML=rows.length?rows.map(x=>'<tr><td><span class="badge '+(x.paid?'green':x.status==='pending'?'yellow':'orange')+'">'+(x.paid?'PAGO':x.status==='pending'?'PENDENTE':'NÃO PAGO')+'</span></td><td>'+esc(String(x.status||'—').toUpperCase())+'</td><td><b>'+esc(x.full_name||x.discord_name||'—')+'</b></td><td>'+esc(x.discord_name||'—')+'<div class="mono subtitle">'+esc(x.discord_id||'')+'</div></td><td class="mono">'+esc(x.steam_id||'—')+'</td><td>'+esc(String(x.entry_type||'—').toUpperCase())+'</td><td>'+money(x.amount)+'</td><td class="mono">'+esc(x.mp_payment_id||x.mp_preference_id||'—')+'</td><td>'+fmt(x.paid_at)+'</td><td>'+fmt(x.created_at)+'</td></tr>').join(''):'<tr><td colspan="10"><div class="empty">Nenhuma inscrição encontrada para esta Season.</div></td></tr>'}catch(e){const b=document.getElementById('suRows');if(b)b.innerHTML='<tr><td colspan="10"><div class="empty">❌ '+esc(e.message)+'</div></td></tr>'}}
const obs=new MutationObserver(()=>{installServerSelector();installSeasonResults()});obs.observe(document.documentElement,{childList:true,subtree:true});let n=0;const t=setInterval(()=>{n++;installServerSelector();installSeasonResults();if(n>80)clearInterval(t)},400);
})();
`;