export const panelSlotControlJs = String.raw`
(function(){
  const $=id=>document.getElementById(id);
  function toastLocal(msg,bad){const t=$('toast');if(!t){alert(msg);return}t.textContent=msg;t.classList.remove('hidden');t.style.borderColor=bad?'#943540':'#60428b';clearTimeout(t._slotTimer);t._slotTimer=setTimeout(()=>t.classList.add('hidden'),3200)}
  async function request(url,opt){const r=await fetch(url,opt||{});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||('Erro '+r.status));return j}
  function html(){
    const server=$('server');if(!server||$('slotControlSection'))return;
    const wrap=document.createElement('div');wrap.id='slotControlSection';wrap.className='section';
    wrap.innerHTML='<div class="sectionHead"><div><h2>🎛️ Gerenciamento de Slots</h2><div class="subtitle">Controle a capacidade do Guerra Fria diretamente pelo painel.</div></div><span id="slotModeBadge" class="badge green">Carregando...</span></div><div class="body">'+
    '<div class="segmented" style="margin-bottom:14px"><button id="slotModeAuto" type="button">⚡ Automático</button><button id="slotModeManual" type="button">✋ Manual</button></div>'+
    '<div id="slotAutoFields"><div class="stateCard" style="margin-bottom:12px"><b>Modo automático</b><small>O bot abre e fecha slots conforme população e fila. Você continua decidindo os limites mínimo e máximo.</small></div><div class="grid2"><div class="field"><label>Mínimo automático</label><input id="slotMin" type="number" min="1" max="1000" step="1" inputmode="numeric"><div class="subtitle">O bot não reduz abaixo deste valor.</div></div><div class="field"><label>Máximo automático</label><input id="slotMax" type="number" min="1" max="1000" step="1" inputmode="numeric"><div class="subtitle">O bot nunca ultrapassa este valor.</div></div></div></div>'+
    '<div id="slotManualFields" class="hidden"><div class="stateCard" style="margin-bottom:12px"><b>Modo manual</b><small>Você assume o controle e escolhe uma capacidade fixa. O sistema protege jogadores já conectados.</small></div><div class="field"><label>Quantidade fixa de slots</label><input id="slotManual" type="number" min="1" max="1000" step="1" inputmode="numeric"></div></div>'+
    '<div class="stateCard" style="margin:12px 0"><b id="slotStatusTitle">Status do servidor</b><small id="slotStatusText">Carregando configuração...</small></div><button id="slotSave" type="button" class="btn yellow" style="width:100%">Salvar configuração de slots</button><div class="subtitle" style="text-align:center;margin-top:10px">Desenvolvido por Maciota</div></div>';
    server.insertBefore(wrap,server.firstChild)
  }
  let mode='automatic';
  function setMode(next){mode=next==='manual'?'manual':'automatic';$('slotModeAuto')?.classList.toggle('active',mode==='automatic');$('slotModeManual')?.classList.toggle('active',mode==='manual');$('slotAutoFields')?.classList.toggle('hidden',mode!=='automatic');$('slotManualFields')?.classList.toggle('hidden',mode!=='manual');if($('slotModeBadge')){$('slotModeBadge').textContent=mode==='automatic'?'AUTOMÁTICO':'MANUAL';$('slotModeBadge').className='badge '+(mode==='automatic'?'green':'yellow')}}
  async function load(){try{const d=await request('/api/admin/server/slot-control',{cache:'no-store'}),s=d.settings||{},i=d.info||{};if($('slotMin'))$('slotMin').value=String(s.minSlots??100);if($('slotMax'))$('slotMax').value=String(s.maxSlots??250);if($('slotManual'))$('slotManual').value=String(s.manualSlots??s.minSlots??100);setMode(s.mode);const current=Number(i.maxPlayers||s.currentSlots||0),players=Number(i.players||0),queue=Number(i.queued||0);if($('slotStatusTitle'))$('slotStatusTitle').textContent='Capacidade atual: '+(current||'—')+' slots';if($('slotStatusText'))$('slotStatusText').textContent=mode==='automatic'?'Automático entre '+s.minSlots+' e '+s.maxSlots+' • '+players+' online • '+queue+' na fila':'Manual em '+s.manualSlots+' slots • '+players+' online'}catch(e){toastLocal(e.message,true)}}
  async function save(){const minSlots=Number($('slotMin')?.value),maxSlots=Number($('slotMax')?.value),manualSlots=Number($('slotManual')?.value);if(!Number.isFinite(minSlots)||!Number.isFinite(maxSlots)||minSlots<1||maxSlots<minSlots)return toastLocal('Confira o mínimo e o máximo de slots.',true);if(mode==='manual'&&(!Number.isFinite(manualSlots)||manualSlots<1))return toastLocal('Informe a quantidade manual de slots.',true);const btn=$('slotSave');if(btn){btn.disabled=true;btn.textContent='Salvando...'}try{const d=await request('/api/admin/server/slot-control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,minSlots,maxSlots,manualSlots})});toastLocal(mode==='automatic'?'Automático salvo: '+minSlots+'–'+maxSlots+' slots.':'Controle manual aplicado: '+manualSlots+' slots.');await load();if(!d.applied)toastLocal('Configuração salva, mas o RCON não confirmou a alteração imediatamente.',true)}catch(e){toastLocal(e.message,true)}finally{if(btn){btn.disabled=false;btn.textContent='Salvar configuração de slots'}}}
  function boot(){html();$('slotModeAuto')?.addEventListener('click',()=>setMode('automatic'));$('slotModeManual')?.addEventListener('click',()=>setMode('manual'));$('slotSave')?.addEventListener('click',save);load();setInterval(()=>{if(document.getElementById('server')?.classList.contains('active'))load()},10000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot()
})();
`;