export const panelWipeJs = String.raw`
(function(){
  const $=id=>document.getElementById(id);let currentKind='map';
  function toast(msg,bad){const t=$('toast');if(!t)return alert(msg);t.textContent=msg;t.classList.remove('hidden');t.style.borderColor=bad?'#943540':'#9b692c';setTimeout(()=>t.classList.add('hidden'),4500)}
  async function api(url,opt){const r=await fetch(url,opt||{});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||('Erro '+r.status));return d}
  function create(){const main=document.querySelector('.main');if(!main||$('wipeAdmin'))return;const view=document.createElement('section');view.id='wipeAdmin';view.className='view';view.innerHTML=
    '<div class="section"><div class="sectionHead"><div><h2>🔥 Central de Wipe</h2><div class="subtitle">Diagnóstico, planejamento, backup e execução protegida do servidor.</div></div><span class="badge yellow">MODO SEGURO</span></div><div class="body">'+
    '<div class="stateCard" style="border-color:#8b5e28;margin-bottom:14px"><b>🔒 Exclusão desabilitada</b><small>Todo o sistema pode ser testado e planejado, mas nenhum arquivo será removido até a liberação manual no dia do wipe.</small></div>'+
    '<div class="actionGrid"><button id="wipeDiagnostic" class="btn" type="button">Executar diagnóstico</button><button id="wipePlan" class="btn yellow" type="button">Gerar plano de wipe</button></div>'+
    '<div class="field"><label>Tipo de wipe</label><select id="wipeKind"><option value="map">Wipe mapa</option><option value="general">Wipe geral (mapa + BPs)</option></select></div>'+
    '<div class="field"><label>Link do mapa no RustMaps</label><input id="wipeRustMaps" type="url" placeholder="https://rustmaps.com/... ou download .map"></div>'+
    '<div class="cards" style="margin-top:14px"><div class="card"><small>API do painel</small><strong id="wipeApi">—</strong></div><div class="card"><small>Estado do servidor</small><strong id="wipeState">—</strong></div><div class="card"><small>Arquivos planejados</small><strong id="wipeCount">—</strong></div><div class="card accent"><small>Execução</small><strong id="wipeLock">Bloqueada</strong></div></div>'+
    '<div class="section" style="margin-top:14px"><div class="sectionHead"><h2>Arquivos identificados</h2><span id="wipeTotal" class="badge">Nenhum plano</span></div><div id="wipeFiles" class="body"><div class="empty">Execute o diagnóstico e gere um plano. Nenhuma alteração será feita.</div></div></div>'+
    '<div class="stateCard" style="margin-top:14px"><b>Etapas preparadas para o dia do wipe</b><small>Salvar servidor → avisar jogadores → criar backup → parar → validar lista → excluir → iniciar → aguardar RCON → auditar.</small></div>'+
    '<button id="wipeExecute" class="btn red" type="button" disabled style="width:100%;margin-top:14px;opacity:.55">Execução bloqueada até o dia do wipe</button></div></div>';main.appendChild(view);
    $('wipeDiagnostic').onclick=diagnostic;$('wipePlan').onclick=plan;$('wipeKind').onchange=e=>{currentKind=e.target.value};
  }
  function nav(){for(const id of ['nav','mobileNav']){const box=$(id);if(!box||box.querySelector('[data-wipe]'))continue;const b=document.createElement('button');b.type='button';b.textContent='Wipe';b.dataset.wipe='1';b.dataset.view='wipeAdmin';b.onclick=open;box.appendChild(b)}}
  function open(){create();nav();document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$('wipeAdmin').classList.add('active');document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='wipeAdmin'));if($('pageTitle'))$('pageTitle').textContent='Central de Wipe';diagnostic()}
  async function diagnostic(){const b=$('wipeDiagnostic');b.disabled=true;b.textContent='Verificando…';try{const d=await api('/api/admin/wipe/diagnostic',{cache:'no-store'});$('wipeApi').textContent=d.connected?'Conectada':'Falha';$('wipeState').textContent=d.server?.state||'—';$('wipeLock').textContent=d.capabilities?.destructiveEnabled?'Liberada':'Bloqueada';toast('Diagnóstico concluído sem alterar arquivos.')}catch(e){$('wipeApi').textContent='Falha';toast(e.message,true)}finally{b.disabled=false;b.textContent='Executar diagnóstico'}}
  async function plan(){const b=$('wipePlan');b.disabled=true;b.textContent='Mapeando…';try{const link=$('wipeRustMaps').value.trim();if(!link)throw new Error('Informe o link do RustMaps.');const d=await api('/api/admin/wipe/plan?kind='+encodeURIComponent(currentKind)+'&rustmaps='+encodeURIComponent(link),{cache:'no-store'});$('wipeCount').textContent=String(d.files.length);$('wipeTotal').textContent=d.files.length+' arquivos • '+Math.round(d.totalBytes/1048576*100)/100+' MB';$('wipeFiles').innerHTML=d.files.length?d.files.map(f=>'<div class="stateCard" style="margin-bottom:7px"><b>'+escapeHtml(f.name)+'</b><small>'+escapeHtml(f.path)+' • '+Math.round(f.size/1024)+' KB</small></div>').join(''):'<div class="empty">Nenhum arquivo compatível encontrado. Revise o diretório antes do wipe.</div>';toast('Plano criado e link do mapa validado. Nenhum arquivo foi alterado.')}catch(e){toast(e.message,true)}finally{b.disabled=false;b.textContent='Gerar plano de wipe'}}
  function escapeHtml(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function boot(){create();nav();setInterval(nav,2000)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
`;
