export const panelAlertsJs = String.raw`
(function(){'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]||c));
const fmt=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('pt-BR')};
let alerts=[],lastAlertId=null,firstLoad=true;

function styles(){if(document.getElementById('gfAlertsStyle'))return;const s=document.createElement('style');s.id='gfAlertsStyle';s.textContent='.alertHero{display:grid;grid-template-columns:1.4fr .6fr;gap:12px}.alertSettings{border:1px solid #3b2a4c;border-radius:16px;background:linear-gradient(145deg,#16101e,#0c0911);padding:16px}.alertSettings h3{margin:0 0 6px}.alertSettings p{color:#9e92a9;font-size:12px;line-height:1.5}.alertActions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.alertList{display:grid;gap:10px;margin-top:14px}.alertItem{position:relative;border:1px solid #332541;border-left:5px solid #8b5cf6;border-radius:15px;background:linear-gradient(145deg,#120d19,#0b0810);padding:14px}.alertItem.critical{border-left-color:#ef4444}.alertItem.warning{border-left-color:#ff9a2f}.alertItem.success{border-left-color:#22c55e}.alertTop{display:flex;justify-content:space-between;gap:10px;align-items:start}.alertTop b{font-size:15px}.alertKind{font-size:9px;font-weight:950;letter-spacing:.08em;border:1px solid #49355d;border-radius:999px;padding:4px 7px;color:#cbb9dc}.alertBody{margin-top:8px;color:#d8cfdf;font-size:13px;line-height:1.5}.alertMeta{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.alertMeta span{font-size:10px;color:#978aa4;border:1px solid #30233c;border-radius:999px;padding:4px 7px}.alertEmpty{padding:30px;text-align:center;color:#8e8299;border:1px dashed #3b2b49;border-radius:15px}@media(max-width:980px){.mobileNav{position:fixed!important;left:0;right:0;top:auto!important;bottom:0;z-index:1500;display:flex!important;gap:4px;overflow-x:auto;background:#09060ff5;border-top:1px solid #38264a;padding:7px 8px calc(7px + env(safe-area-inset-bottom));backdrop-filter:blur(18px);box-shadow:0 -10px 30px #0009}.mobileNav button{flex:0 0 auto;min-width:88px;padding:10px 12px!important;border-radius:12px!important;font-size:12px}.main{padding-bottom:calc(105px + env(safe-area-inset-bottom))!important}.alertHero{grid-template-columns:1fr}.alertActions .btn{flex:1;min-width:140px}.alertTop{display:block}.alertKind{display:inline-block;margin-top:7px}}';document.head.appendChild(s)}
function ensure(){styles();const main=document.querySelector('.main');if(!main||document.getElementById('alertsAdmin'))return;const sec=document.createElement('section');sec.id='alertsAdmin';sec.className='view';sec.innerHTML='<div class="alertHero"><div class="section"><div class="sectionHead"><div><h2>Central de Alertas</h2><div class="subtitle">Anticheat e ações críticas do servidor em tempo real.</div></div><span class="badge orange">Ao vivo</span></div><div class="body"><div id="alertList" class="alertList"><div class="alertEmpty">Carregando alertas...</div></div></div></div><div class="alertSettings"><h3>📱 Notificações no telefone</h3><p>Escolha onde receber os alertas. O Discord envia no privado; o GF Admin também pode exibir notificações próprias do aplicativo quando estiver instalado.</p><div id="notifyState" class="subtitle">Verificando...</div><div id="appNotifyState" class="subtitle" style="margin-top:6px">App: verificando...</div><div class="alertActions"><button id="toggleNotify" class="btn green">Ativar no Discord</button><button id="toggleAppNotify" class="btn green">Ativar no aplicativo</button><button id="installGfAdmin" class="btn yellow">📲 Instalar GF Admin</button></div></div></div>';main.appendChild(sec);document.getElementById('toggleNotify').onclick=toggleNotify;document.getElementById('toggleAppNotify').onclick=toggleAppNotify;document.getElementById('installGfAdmin').onclick=()=>{const top=document.getElementById('gfInstall');if(top){top.click();return}document.getElementById('gfInstallModal')?.classList.add('open')}}
function nav(){for(const id of ['nav','mobileNav']){const box=document.getElementById(id);if(!box||box.querySelector('[data-alerts-page]'))continue;const b=document.createElement('button');b.textContent='Alertas';b.dataset.alertsPage='1';b.dataset.view='alertsAdmin';b.onclick=open;box.appendChild(b)}}
async function api(url,opt){const r=await fetch(url,opt||{});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||('Erro '+r.status));return j}
async function state(){try{const d=await api('/api/admin/notifications/discord');const b=document.getElementById('toggleNotify'),t=document.getElementById('notifyState');b.dataset.enabled=d.enabled?'1':'0';b.textContent=d.enabled?'Desativar Discord':'Ativar no Discord';b.className='btn '+(d.enabled?'red':'green');t.textContent=d.enabled?'✅ Discord: alertas privados ativados.':'Discord: notificações privadas desativadas.'}catch(e){document.getElementById('notifyState').textContent='Discord: não foi possível verificar.'}appState()}
function appState(){const b=document.getElementById('toggleAppNotify'),t=document.getElementById('appNotifyState');if(!b||!t)return;if(!('Notification' in window)){b.disabled=true;t.textContent='App: este navegador não oferece notificações web.';return}const enabled=localStorage.getItem('gfAppNotify')==='1'&&Notification.permission==='granted';b.dataset.enabled=enabled?'1':'0';b.textContent=enabled?'Desativar no aplicativo':'Ativar no aplicativo';b.className='btn '+(enabled?'red':'green');t.textContent=enabled?'✅ App: notificações do GF Admin ativadas.':Notification.permission==='denied'?'App: permissão bloqueada nos ajustes do aparelho.':'App: notificações próprias desativadas.'}
async function toggleAppNotify(){const enabled=localStorage.getItem('gfAppNotify')==='1'&&Notification.permission==='granted';if(enabled){localStorage.setItem('gfAppNotify','0');appState();return}try{const p=await Notification.requestPermission();if(p!=='granted')throw new Error('Permissão de notificações não concedida.');localStorage.setItem('gfAppNotify','1');appState();await appNotify({title:'Guerra Fria Admin',message:'Notificações do aplicativo ativadas.',kind:'system'})}catch(e){appState();alert(e.message)}}
async function appNotify(a){if(localStorage.getItem('gfAppNotify')!=='1'||!('Notification' in window)||Notification.permission!=='granted')return;const title=a.kind==='anticheat'?'🛡️ '+a.title:a.severity==='critical'?'🚨 '+a.title:a.title;const opts={body:a.message||'',tag:'gf-'+(a.id||Date.now()),renotify:true,data:{url:'/admin'}};try{const reg=await navigator.serviceWorker?.ready;if(reg){await reg.showNotification(title,opts);return}}catch{}try{new Notification(title,opts)}catch{}}
async function toggleNotify(){const b=document.getElementById('toggleNotify'),enabled=b.dataset.enabled!=='1';try{await api('/api/admin/notifications/discord',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled})});await state()}catch(e){alert(e.message)}}
async function load(){try{const d=await api('/api/admin/notifications/alerts?limit=150'),next=d.alerts||[];if(next.length){const newest=next[0],id=String(newest.id||newest.createdAt||'');if(!firstLoad&&lastAlertId&&id!==lastAlertId)appNotify(newest);lastAlertId=id}firstLoad=false;alerts=next;render()}catch(e){const box=document.getElementById('alertList');if(box)box.innerHTML='<div class="alertEmpty">Erro ao carregar alertas.</div>'}}
function render(){const box=document.getElementById('alertList');if(!box)return;box.innerHTML=alerts.length?alerts.map(a=>'<article class="alertItem '+esc(a.severity)+'"><div class="alertTop"><b>'+esc(a.title)+'</b><span class="alertKind">'+esc(String(a.kind||'system').toUpperCase())+'</span></div><div class="alertBody">'+esc(a.message||'')+'</div><div class="alertMeta">'+(a.playerName?'<span>Jogador: '+esc(a.playerName)+'</span>':'')+(a.steamId?'<span>SteamID: '+esc(a.steamId)+'</span>':'')+'<span>'+esc(fmt(a.createdAt))+'</span></div></article>').join(''):'<div class="alertEmpty">Nenhum alerta desde o último início do sistema.</div>'}
function open(){ensure();document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById('alertsAdmin')?.classList.add('active');document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='alertsAdmin'));const title=document.getElementById('pageTitle');if(title)title.textContent='Alertas';state();load()}
const t=setInterval(()=>{ensure();nav();if(document.getElementById('nav')?.children.length)clearInterval(t)},300);setInterval(()=>{if(document.getElementById('alertsAdmin')?.classList.contains('active')||localStorage.getItem('gfAppNotify')==='1')load()},3000);setTimeout(()=>{ensure();nav();appState()},1200);
})();`;
