export const panelAlertsJs = String.raw`
(function(){'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const fmt=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('pt-BR')};
let alerts=[];

function styles(){if(document.getElementById('gfAlertsStyle'))return;const s=document.createElement('style');s.id='gfAlertsStyle';s.textContent='.alertHero{display:grid;grid-template-columns:1.4fr .6fr;gap:12px}.alertSettings{border:1px solid #3b2a4c;border-radius:16px;background:linear-gradient(145deg,#16101e,#0c0911);padding:16px}.alertSettings h3{margin:0 0 6px}.alertSettings p{color:#9e92a9;font-size:12px;line-height:1.5}.alertActions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.alertList{display:grid;gap:10px;margin-top:14px}.alertItem{position:relative;border:1px solid #332541;border-left:5px solid #8b5cf6;border-radius:15px;background:linear-gradient(145deg,#120d19,#0b0810);padding:14px}.alertItem.critical{border-left-color:#ef4444}.alertItem.warning{border-left-color:#ff9a2f}.alertItem.success{border-left-color:#22c55e}.alertTop{display:flex;justify-content:space-between;gap:10px;align-items:start}.alertTop b{font-size:15px}.alertKind{font-size:9px;font-weight:950;letter-spacing:.08em;border:1px solid #49355d;border-radius:999px;padding:4px 7px;color:#cbb9dc}.alertBody{margin-top:8px;color:#d8cfdf;font-size:13px;line-height:1.5}.alertMeta{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.alertMeta span{font-size:10px;color:#978aa4;border:1px solid #30233c;border-radius:999px;padding:4px 7px}.alertEmpty{padding:30px;text-align:center;color:#8e8299;border:1px dashed #3b2b49;border-radius:15px}@media(max-width:760px){.alertHero{grid-template-columns:1fr}.alertActions .btn{flex:1;min-width:140px}.alertTop{display:block}.alertKind{display:inline-block;margin-top:7px}}';document.head.appendChild(s)}
function ensure(){styles();const main=document.querySelector('.main');if(!main||document.getElementById('alertsAdmin'))return;const sec=document.createElement('section');sec.id='alertsAdmin';sec.className='view';sec.innerHTML='<div class="alertHero"><div class="section"><div class="sectionHead"><div><h2>Central de Alertas</h2><div class="subtitle">Anticheat e ações críticas do servidor em tempo real.</div></div><span class="badge orange">Ao vivo</span></div><div class="body"><div id="alertList" class="alertList"><div class="alertEmpty">Carregando alertas...</div></div></div></div><div class="alertSettings"><h3>📱 Notificações no telefone</h3><p>Ative para receber no privado do Discord alertas de anticheat, banimentos, kicks, advertências e outras ações administrativas.</p><div id="notifyState" class="subtitle">Verificando...</div><div class="alertActions"><button id="toggleNotify" class="btn green">Ativar no Discord</button><button id="installGfAdmin" class="btn yellow">📲 Instalar GF Admin</button></div></div></div>';main.appendChild(sec);document.getElementById('toggleNotify').onclick=toggleNotify;document.getElementById('installGfAdmin').onclick=()=>{const top=document.getElementById('gfInstall');if(top){top.click();return}document.getElementById('gfInstallModal')?.classList.add('open')}}
function nav(){for(const id of ['nav','mobileNav']){const box=document.getElementById(id);if(!box||box.querySelector('[data-alerts-page]'))continue;const b=document.createElement('button');b.textContent='Alertas';b.dataset.alertsPage='1';b.dataset.view='alertsAdmin';b.onclick=open;box.appendChild(b)}}
async function api(url,opt){const r=await fetch(url,opt||{});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||('Erro '+r.status));return j}
async function state(){try{const d=await api('/api/admin/notifications/discord');const b=document.getElementById('toggleNotify'),t=document.getElementById('notifyState');b.dataset.enabled=d.enabled?'1':'0';b.textContent=d.enabled?'Desativar notificações':'Ativar no Discord';b.className='btn '+(d.enabled?'red':'green');t.textContent=d.enabled?'✅ Você receberá alertas no privado do Discord.':'Notificações privadas estão desativadas.'}catch(e){document.getElementById('notifyState').textContent='Não foi possível verificar as notificações.'}}
async function toggleNotify(){const b=document.getElementById('toggleNotify'),enabled=b.dataset.enabled!=='1';try{await api('/api/admin/notifications/discord',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled})});await state()}catch(e){alert(e.message)}}
async function load(){try{const d=await api('/api/admin/notifications/alerts?limit=150');alerts=d.alerts||[];render()}catch(e){document.getElementById('alertList').innerHTML='<div class="alertEmpty">Erro ao carregar alertas.</div>'}}
function render(){const box=document.getElementById('alertList');if(!box)return;box.innerHTML=alerts.length?alerts.map(a=>'<article class="alertItem '+esc(a.severity)+'"><div class="alertTop"><b>'+esc(a.title)+'</b><span class="alertKind">'+esc(String(a.kind||'system').toUpperCase())+'</span></div><div class="alertBody">'+esc(a.message||'')+'</div><div class="alertMeta">'+(a.playerName?'<span>Jogador: '+esc(a.playerName)+'</span>':'')+(a.steamId?'<span>SteamID: '+esc(a.steamId)+'</span>':'')+'<span>'+esc(fmt(a.createdAt))+'</span></div></article>').join(''):'<div class="alertEmpty">Nenhum alerta desde o último início do sistema.</div>'}
function open(){ensure();document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById('alertsAdmin')?.classList.add('active');document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='alertsAdmin'));const title=document.getElementById('pageTitle');if(title)title.textContent='Alertas';state();load()}
const t=setInterval(()=>{ensure();nav();if(document.getElementById('nav')?.children.length)clearInterval(t)},300);setInterval(()=>{if(document.getElementById('alertsAdmin')?.classList.contains('active'))load()},3000);setTimeout(()=>{ensure();nav()},1200);
})();`;
