export const panelSeasonBackupAddonJs = String.raw`
(function(){'use strict';
const $=id=>document.getElementById(id);
const fmt=v=>{if(!v)return'Nenhum backup ainda';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('pt-BR')};
async function api(path,method='GET',body){const r=await fetch('/api/admin/season/control/backup'+path,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Falha no backup');return d}
function mount(){const view=$('seasonRegistrations');if(!view||$('seasonBackupCard'))return false;const first=view.querySelector('.section');if(!first)return false;const card=document.createElement('div');card.className='section';card.id='seasonBackupCard';card.style.borderColor='#3b5d49';card.innerHTML='<div class="sectionHead"><div><h2>💾 Backup automático da Season</h2><div class="subtitle">Um único backup é renovado a cada 1 hora. O backup anterior é substituído pelo novo.</div></div><span class="badge green">A CADA 1 HORA</span></div><div class="body"><div class="stateCard" id="seasonBackupState"><b>Carregando backup...</b><small>Protege pontuação e histórico competitivo da Season 1.</small></div><div class="toolbar" style="margin-top:14px"><button class="btn green" id="seasonBackupNow">💾 CRIAR BACKUP AGORA</button><button class="btn red" id="seasonBackupRestore">↩ RESTAURAR BACKUP</button><button class="btn" id="seasonBackupRefresh">↻ STATUS</button></div><div class="subtitle" id="seasonBackupMsg" style="margin-top:10px">Ao restaurar, a pontuação é bloqueada automaticamente até você conferir os dados e clicar em INICIAR PONTUAÇÃO.</div></div>';first.insertAdjacentElement('afterend',card);$('seasonBackupRefresh').onclick=load;$('seasonBackupNow').onclick=createNow;$('seasonBackupRestore').onclick=restore;load();return true}
async function load(){const box=$('seasonBackupState');try{const d=await api('');const b=d.backup;if(!box)return;if(!b){box.innerHTML='<b>⚠️ Nenhum backup criado ainda</b><small>O sistema criará o primeiro automaticamente; você também pode criar agora.</small>';return}box.innerHTML='<b>✅ Último backup: '+fmt(b.created_at)+'</b><small>Jogadores salvos: <b>'+Number(b.players_count||0)+'</b> • transações/histórico: <b>'+Number(b.transactions_count||0)+'</b><br>Season ID: <span class="mono">'+String(b.season_id||'—')+'</span></small>'}catch(e){if(box)box.innerHTML='<b class="danger">Falha ao consultar backup</b><small>'+e.message+'</small>'}}
async function createNow(){const msg=$('seasonBackupMsg');const btn=$('seasonBackupNow');try{btn.disabled=true;msg.textContent='Criando backup e substituindo o anterior...';const d=await api('','POST',{});msg.textContent='✅ '+d.message;await load()}catch(e){msg.textContent='❌ '+e.message}finally{btn.disabled=false}}
async function restore(){const typed=prompt('ATENÇÃO: restaurar volta a pontuação e o histórico para o último backup salvo.\n\nA pontuação será BLOQUEADA durante a restauração.\n\nDigite RESTAURAR para confirmar:');if(String(typed||'').trim().toUpperCase()!=='RESTAURAR')return;const msg=$('seasonBackupMsg');const btn=$('seasonBackupRestore');try{btn.disabled=true;msg.textContent='Restaurando e verificando backup... não feche esta tela.';const d=await api('/restore','POST',{confirm:'RESTAURAR'});msg.textContent='✅ '+d.message;await load();if(typeof window.loadControl==='function')await window.loadControl();}catch(e){msg.textContent='❌ '+e.message}finally{btn.disabled=false}}
const t=setInterval(()=>{if(mount())clearInterval(t)},500);setTimeout(()=>clearInterval(t),30000);document.addEventListener('click',()=>setTimeout(mount,50),true);
})();
`;
