export const cleanAdminJs = String.raw`
(function(){
'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const pages={overview:'Visão Geral',players:'Jogadores',chat:'Chat ao vivo',events:'Eventos',server:'Servidor',discord:'Discord',steam:'Steam / Boosters',vip:'VIPs',finance:'Financeiro',logs:'Logs'};
let selectedPlayer=null, chatTimer=null, playerMode='all', searchTimer=null;

function setupAuthTransport(){
  const params=new URLSearchParams(location.search); const token=params.get('auth');
  if(token){sessionStorage.setItem('gf_admin_token',token);params.delete('auth');history.replaceState(null,'',location.pathname+(params.toString()?'?'+params.toString():''));}
  const nativeFetch=window.fetch.bind(window);
  window.fetch=function(input,init){const cfg=Object.assign({},init||{});const headers=new Headers(cfg.headers||{});const saved=sessionStorage.getItem('gf_admin_token')||'';const url=typeof input==='string'?input:(input&&input.url)||'';if(saved&&(url.startsWith('/api/admin')||url.startsWith(location.origin+'/api/admin')))headers.set('Authorization','Bearer '+saved);cfg.headers=headers;return nativeFetch(input,cfg)};
}
setupAuthTransport();

async function api(url,opt){const r=await fetch(url,opt||{});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||('Erro '+r.status));return j}
async function post(url,data){return api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data||{})})}
function toast(msg,bad=false){const t=$('toast');t.textContent=msg;t.classList.remove('hidden');t.style.borderColor=bad?'#943540':'#60428b';clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.add('hidden'),3200)}
function fmtDate(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('pt-BR')}

function buildNav(){for(const box of [$('nav'),$('mobileNav')]){box.innerHTML='';Object.entries(pages).forEach(([id,label])=>{const b=document.createElement('button');b.textContent=label;b.dataset.view=id;b.onclick=()=>show(id);box.appendChild(b)})}}
function markNav(id){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id))}
function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(id)?.classList.add('active');$('pageTitle').textContent=pages[id]||'Painel';markNav(id);if(chatTimer){clearInterval(chatTimer);chatTimer=null}if(id==='overview')loadOverview();if(id==='players')loadPlayers();if(id==='chat'){loadChat();chatTimer=setInterval(loadChat,2500)}if(id==='events')loadEvents();if(id==='steam')loadSteam();if(id==='vip')loadVips();if(id==='finance')loadFinance();if(id==='logs')loadLogs()}

async function boot(){try{const me=await api('/api/admin/me');$('username').textContent=me.user?.username||'Administrador';$('login').classList.add('hidden');$('app').classList.remove('hidden');buildNav();bind();show('overview')}catch(e){$('app').classList.add('hidden');$('login').classList.remove('hidden')}}

async function loadOverview(){
  const [server,players,links,vips,logs]=await Promise.allSettled([api('/api/admin/server/online'),api('/api/admin/players'),api('/api/admin/steam-links'),api('/api/admin/vips'),api('/api/admin/modlogs')]);
  if(server.status==='fulfilled'){const d=server.value,info=d.info||{};const count=typeof info.players==='number'?info.players:(d.players||[]).length;$('ovOnline').textContent=count;$('ovQueue').textContent=info.queued??0;$('ovSleepers').textContent=info.sleepers??0;$('ovSlots').textContent=count+'/'+(info.maxPlayers??0);$('ovMap').textContent=info.map||'Indisponível'}else{$('ovOnline').textContent='—';$('ovQueue').textContent='—';$('ovSleepers').textContent='—';$('ovSlots').textContent='—';$('ovMap').textContent='RCON indisponível'}
  if(players.status==='fulfilled')$('ovKnown').textContent=(players.value.players||[]).length;else $('ovKnown').textContent='—';
  if(links.status==='fulfilled')$('ovBoosters').textContent=(links.value.links||[]).filter(x=>x.active).length;else $('ovBoosters').textContent='—';
  if(vips.status==='fulfilled'){$('ovVips').textContent=(vips.value.vips||[]).filter(v=>new Date(v.expiresAt).getTime()>Date.now()).length}else $('ovVips').textContent='—';
  if(logs.status==='fulfilled')$('overviewLogs').innerHTML=(logs.value.logs||[]).slice(0,20).map(x=>'<tr><td>'+esc(x.action)+'</td><td>'+esc(x.playerName||'—')+'</td><td>'+esc(x.adminName||'—')+'</td><td>'+esc(x.reason||'—')+'</td><td>'+fmtDate(x.createdAt)+'</td></tr>').join('');
}

function renderPlayers(rows){const body=$('playersRows');body.innerHTML='';if(!rows.length){body.innerHTML='<tr><td colspan="4"><div class="empty">Nenhum jogador encontrado.</div></td></tr>';return}rows.forEach(p=>{const tr=document.createElement('tr');tr.className='clickable';const online=p.isOnline===true;tr.innerHTML='<td><span class="status '+(online?'online':'offline')+'">● '+(online?'Online':'Offline')+'</span></td><td>'+esc(p.playerName||p.name||'Jogador')+'</td><td class="mono">'+esc(p.steamId)+'</td><td>'+(p.ping!=null?esc(p.ping)+' ms':fmtDate(p.lastSeen))+'</td>';tr.onclick=()=>openPlayerDrawer({...p,name:p.playerName||p.name});body.appendChild(tr)})}
async function loadPlayers(){try{const q=$('playerSearch').value.trim();if(playerMode==='online'){const d=await api('/api/admin/server/online');renderPlayers((d.players||[]).map(p=>({...p,isOnline:true})))}else{const d=await api('/api/admin/players?q='+encodeURIComponent(q));renderPlayers(d.players||[])}}catch(e){toast(e.message,true)}}

function drawerHtml(p){return '<div class="drawerBackdrop" id="drawerBackdrop"><aside class="drawer"><div class="drawerHead"><div><small class="subtitle">Jogador selecionado</small><h2>'+esc(p.name||'Jogador')+'</h2><div class="mono subtitle">'+esc(p.steamId)+'</div></div><button class="btn" id="closeDrawer">Fechar</button></div><div class="badge '+(p.isOnline?'ok':'')+'">● '+(p.isOnline?'Online':'Offline')+(p.ping!=null?' • '+esc(p.ping)+' ms':'')+'</div><div class="field"><label>Motivo da ação</label><input id="actReason" placeholder="Informe o motivo"></div><div class="field"><label>Duração do ban</label><select id="actBanDuration"><option value="3d">3 dias</option><option value="7d">7 dias</option><option value="30d">30 dias</option><option value="perm">Permanente</option></select></div><div class="toolbar"><button class="btn red" id="actBan">Banir</button><button class="btn" id="actKick">Kickar</button><button class="btn green" id="actUnban">Desbanir</button></div><hr class="divider"><h3>Dar item</h3><div class="picker"><input id="itemSearch" placeholder="Digite o nome do item"><div id="itemResults" class="pickerResults hidden"></div></div><input id="itemShortname" type="hidden"><div class="field"><label>Quantidade</label><input id="itemAmount" type="number" min="1" value="1"></div><button class="btn yellow" id="actGive">Dar item</button><hr class="divider"><h3>Teleportar / inventário</h3><div class="field"><label>SteamID de destino</label><input id="tpTarget" placeholder="7656119..."></div><div class="toolbar"><button class="btn" id="actTp">Teleportar</button><button class="btn red" id="actClear">Limpar inventário</button></div><hr class="divider"><h3>Verificação</h3><div class="picker"><input id="memberSearch" placeholder="Digite o nome do membro no Discord"><div id="memberResults" class="pickerResults hidden"></div></div><input id="memberId" type="hidden"><div id="memberSelected" class="subtitle" style="margin:8px 0"></div><button class="btn green" id="actVerify">Verificar jogador + VR</button></aside></div>'}
function openPlayerDrawer(p){selectedPlayer=p;$('drawerHost').innerHTML=drawerHtml(p);$('closeDrawer').onclick=closeDrawer;$('drawerBackdrop').onclick=e=>{if(e.target.id==='drawerBackdrop')closeDrawer()};$('actBan').onclick=ban;$('actKick').onclick=kick;$('actUnban').onclick=unban;$('actGive').onclick=give;$('actTp').onclick=teleport;$('actClear').onclick=clearInventory;$('actVerify').onclick=verify;bindItemPicker();bindMemberPicker()}
function closeDrawer(){$('drawerHost').innerHTML='';selectedPlayer=null}
function reason(){return $('actReason')?.value.trim()||''}
async function ban(){if(!reason())return toast('Informe o motivo.',true);if(!confirm('Banir '+selectedPlayer.name+'?'))return;try{await post('/api/admin/moderation/ban',{steamId:selectedPlayer.steamId,duration:$('actBanDuration').value,reason:reason()});toast('Banimento aplicado.');closeDrawer();loadPlayers()}catch(e){toast(e.message,true)}}
async function kick(){if(!reason())return toast('Informe o motivo.',true);try{await post('/api/admin/moderation/kick',{steamId:selectedPlayer.steamId,reason:reason()});toast('Jogador kickado.');closeDrawer();loadPlayers()}catch(e){toast(e.message,true)}}
async function unban(){try{await post('/api/admin/moderation/unban',{steamId:selectedPlayer.steamId});toast('Jogador desbanido.');closeDrawer()}catch(e){toast(e.message,true)}}
async function give(){const item=$('itemShortname').value.trim();if(!item)return toast('Selecione um item da lista.',true);try{await post('/api/admin/server/give',{steamId:selectedPlayer.steamId,item,amount:Number($('itemAmount').value||1)});toast('Item enviado.')}catch(e){toast(e.message,true)}}
async function teleport(){try{await post('/api/admin/server/teleport',{from:selectedPlayer.steamId,to:$('tpTarget').value.trim()});toast('Teleport executado.')}catch(e){toast(e.message,true)}}
async function clearInventory(){if(!confirm('Limpar o inventário deste jogador?'))return;try{await post('/api/admin/server/clear-inventory',{steamId:selectedPlayer.steamId});toast('Inventário limpo.')}catch(e){toast(e.message,true)}}
async function verify(){const id=$('memberId').value.trim();if(!id)return toast('Selecione um membro do Discord.',true);try{await post('/api/admin/moderation/verify',{steamId:selectedPlayer.steamId,discordUserId:id});toast('Jogador verificado.');closeDrawer()}catch(e){toast(e.message,true)}}

function bindItemPicker(){let timer;$('itemSearch').oninput=()=>{clearTimeout(timer);timer=setTimeout(searchItems,220)};$('itemSearch').onfocus=searchItems}
async function searchItems(){const box=$('itemResults');try{const d=await api('/api/admin/server/items?q='+encodeURIComponent($('itemSearch').value.trim()));const rows=d.items||[];box.innerHTML=rows.length?rows.map(i=>'<button type="button" class="pickerItem" data-short="'+esc(i.shortname)+'" data-name="'+esc(i.name)+'"><span><b>'+esc(i.name)+'</b><small>'+esc(i.shortname)+(i.category?' • '+esc(i.category):'')+'</small></span></button>').join(''):'<div class="empty">Nenhum item encontrado.</div>';box.classList.remove('hidden');box.querySelectorAll('[data-short]').forEach(b=>b.onclick=()=>{$('itemShortname').value=b.dataset.short;$('itemSearch').value=b.dataset.name+' • '+b.dataset.short;box.classList.add('hidden')})}catch(e){box.innerHTML='<div class="empty danger">'+esc(e.message)+'</div>';box.classList.remove('hidden')}}
function bindMemberPicker(){let timer;$('memberSearch').oninput=()=>{clearTimeout(timer);timer=setTimeout(searchMembers,220)};$('memberSearch').onfocus=searchMembers}
async function searchMembers(){const box=$('memberResults');try{const d=await api('/api/admin/discord/members?q='+encodeURIComponent($('memberSearch').value.trim()));const rows=d.members||[];box.innerHTML=rows.length?rows.map(m=>'<button type="button" class="pickerItem" data-id="'+esc(m.id)+'" data-name="'+esc(m.displayName||m.username)+'">'+(m.avatar?'<img src="'+esc(m.avatar)+'" width="34" height="34" style="border-radius:50%">':'')+'<span><b>'+esc(m.displayName||m.username)+'</b><small>@'+esc(m.username)+'</small></span></button>').join(''):'<div class="empty">Nenhum membro encontrado.</div>';box.classList.remove('hidden');box.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{$('memberId').value=b.dataset.id;$('memberSearch').value=b.dataset.name;$('memberSelected').textContent='Selecionado: '+b.dataset.name;box.classList.add('hidden')})}catch(e){box.innerHTML='<div class="empty danger">'+esc(e.message)+'</div>';box.classList.remove('hidden')}}

async function loadChat(){try{const d=await api('/api/admin/server/chat');const box=$('chatBox');box.innerHTML=(d.messages||[]).map(m=>'<div class="chatMsg '+(m.type==='moderation'?'mod':'')+'"><b>'+esc(m.player||'Jogador')+'</b><small>'+fmtDate(m.at)+'</small><div>'+esc(m.message)+'</div></div>').join('')||'<div class="empty">Nenhuma mensagem capturada ainda.</div>';box.scrollTop=box.scrollHeight}catch(e){toast(e.message,true)}}
async function sendChat(){const input=$('chatInput');const message=input.value.trim();if(!message)return;try{const r=await post('/api/admin/server/chat',{message});input.value='';await loadChat();if(r.warning)toast(r.warning,true);else toast('Mensagem enviada ao jogo.')}catch(e){toast(e.message,true)}}
async function loadEvents(){try{const d=await api('/api/admin/server/events');$('eventsGrid').innerHTML=(d.events||[]).map(x=>'<div class="event"><b>'+esc(x.label)+'</b><div class="status '+(x.active?'online':'offline')+'">● '+(x.active?'ATIVO':'NÃO DETECTADO')+'</div><div class="subtitle">Última detecção: '+fmtDate(x.lastSeen)+'</div></div>').join('')||'<div class="empty">Sem eventos detectados.</div>'}catch(e){toast(e.message,true)}}
async function loadSteam(){try{const d=await api('/api/admin/steam-links');$('steamRows').innerHTML=(d.links||[]).map(x=>'<tr><td class="mono">'+esc(x.discordUserId)+'</td><td class="mono">'+esc(x.steamId)+'</td><td><span class="status '+(x.active?'online':'offline')+'">'+(x.active?'Ativo':'Inativo')+'</span></td></tr>').join('')}catch(e){toast(e.message,true)}}
async function loadVips(){try{const d=await api('/api/admin/vips');$('vipRows').innerHTML=(d.vips||[]).map(v=>'<tr><td>'+esc(v.id)+'</td><td class="mono">'+esc(v.steamId)+'</td><td>'+esc(v.vipTier)+'</td><td>'+fmtDate(v.expiresAt)+'</td></tr>').join('')}catch(e){toast(e.message,true)}}
async function loadLogs(){try{const d=await api('/api/admin/modlogs');$('logsRows').innerHTML=(d.logs||[]).map(x=>'<tr><td>'+fmtDate(x.createdAt)+'</td><td>'+esc(x.action)+'</td><td>'+esc(x.playerName||'—')+'</td><td>'+esc(x.adminName||'—')+'</td><td>'+esc(x.reason||'—')+'</td></tr>').join('')}catch(e){toast(e.message,true)}}
async function loadFinance(){try{const d=await api('/api/admin/finance/live?days='+encodeURIComponent($('financeDays').value));$('finGross').textContent=money(d.summary?.grossRevenue);$('finRefunded').textContent=money(d.summary?.refunded);$('finNet').textContent=money(d.summary?.netRevenue);$('finApproved').textContent=d.summary?.approved??0;const vals=d.trend||[],max=Math.max(1,...vals.map(x=>Number(x.revenue||0)));$('financeChart').innerHTML=vals.map(x=>'<div class="financeBar" title="'+esc(x.day)+' • '+money(x.revenue)+'" style="height:'+Math.max(3,Number(x.revenue||0)/max*100)+'%"></div>').join('');$('financeRows').innerHTML=(d.payments||[]).map(p=>'<tr><td>'+fmtDate(p.dateApproved||p.dateCreated)+'</td><td class="mono">'+esc(p.id)+'</td><td>'+esc(p.description)+'</td><td>'+esc(p.method)+'</td><td>'+esc(p.status)+'</td><td>'+money(p.amount)+'</td></tr>').join('')}catch(e){toast(e.message,true)}}

function bind(){
  document.querySelectorAll('[data-open]').forEach(x=>x.onclick=()=>show(x.dataset.open));
  $('refreshOverview').onclick=loadOverview;$('onlineOnly').onclick=()=>{playerMode='online';loadPlayers()};$('allPlayers').onclick=()=>{playerMode='all';loadPlayers()};$('playerSearch').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(loadPlayers,220)};
  $('sendChat').onclick=sendChat;$('refreshChat').onclick=loadChat;$('chatInput').onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();sendChat()}};$('refreshEvents').onclick=loadEvents;
  $('sendAnnouncement').onclick=async()=>{try{await post('/api/admin/server/say',{message:$('announcement').value.trim()});toast('Anúncio enviado.')}catch(e){toast(e.message,true)}};$('refreshServer').onclick=()=>{loadOverview();toast('Servidor atualizado.')};
  $('sendDiscordMessage').onclick=async()=>{try{await post('/api/admin/discord/message',{channelId:$('discordChannel').value.trim(),message:$('discordMessage').value.trim()});toast('Mensagem enviada no Discord.')}catch(e){toast(e.message,true)}};
  $('createRaffle').onclick=async()=>{try{await post('/api/admin/discord/raffle',{tier:$('raffleTier').value,vipDays:Number($('raffleDays').value),hours:Number($('raffleHours').value)});toast('Sorteio criado.')}catch(e){toast(e.message,true)}};
  $('refreshSteam').onclick=loadSteam;$('refreshVips').onclick=loadVips;$('refreshLogs').onclick=loadLogs;$('financeDays').onchange=loadFinance;
}
boot();
})();
`;