export const panelSeasonAddonJs = String.raw`
(function(){'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('pt-BR')};
const num=v=>Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:2});
let rows=[];let loading=false;let selectedSteam='';

function ensureView(){
  if($('seasonRegistrations'))return;
  const main=document.querySelector('.main');if(!main)return;
  const view=document.createElement('section');view.id='seasonRegistrations';view.className='view';
  view.innerHTML='<div class="section" style="border-color:#7f1d1d"><div class="sectionHead"><div><h2>🧪 Season Beta • Inscritos</h2><div class="subtitle">Gestão completa dos inscritos, classificação e auditoria de MMR</div></div><div class="toolbar"><button class="btn orange" id="seasonActionsTop">⚙️ Ações da Season</button><button class="btn" id="seasonRefresh">↻ Atualizar</button><span class="badge orange">BETA / TESTE</span></div></div><div class="body"><div class="cards" style="margin-bottom:14px"><div class="card accent"><small>Inscritos</small><strong id="seasonTotal">—</strong></div><div class="card"><small>Steam confirmada</small><strong id="seasonLinked">—</strong></div><div class="card"><small>Com dados</small><strong id="seasonData">—</strong></div><div class="card"><small>Líder atual</small><strong id="seasonLeader" style="font-size:18px">—</strong></div></div><div class="field"><label>Pesquisar inscrito</label><input id="seasonSearch" placeholder="Discord, jogador ou SteamID"></div></div><div class="tableWrap"><table class="table" style="min-width:1180px"><thead><tr><th>#</th><th>Discord</th><th>Steam</th><th>Jogador</th><th>Patente</th><th>MMR efetivo</th><th>Ajuste ADM</th><th>K / D</th><th>Raids</th><th>Eventos</th><th>Inscrição</th><th>Ações</th></tr></thead><tbody id="seasonRows"><tr><td colspan="12"><div class="empty">Carregando inscritos...</div></td></tr></tbody></table></div></div>';
  main.appendChild(view);$('seasonSearch').oninput=render;$('seasonActionsTop').onclick=()=>openActions();$('seasonRefresh').onclick=load;
}

function addNav(){ensureView();for(const box of [$('nav'),$('mobileNav')]){if(!box||box.querySelector('[data-season-registrations]'))continue;const b=document.createElement('button');b.type='button';b.textContent='Season • Inscritos';b.dataset.seasonRegistrations='1';b.onclick=showSeason;box.appendChild(b)}}
function showSeason(){ensureView();addNav();document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$('seasonRegistrations')?.classList.add('active');if($('pageTitle'))$('pageTitle').textContent='Season • Inscritos e MMR';document.querySelectorAll('[data-view]').forEach(b=>b.classList.remove('active'));document.querySelectorAll('[data-season-registrations]').forEach(b=>b.classList.add('active'));load()}

function render(){const q=String($('seasonSearch')?.value||'').trim().toLowerCase();const filtered=rows.filter(x=>!q||[x.discordName,x.discordId,x.playerName,x.steamId,x.rank].some(v=>String(v||'').toLowerCase().includes(q)));const body=$('seasonRows');if(!body)return;body.innerHTML=filtered.length?filtered.map(x=>'<tr><td>'+(x.position?'#'+esc(x.position):'—')+'</td><td><b>'+esc(x.discordName||'—')+'</b><div class="mono subtitle">'+esc(x.discordId||'')+'</div></td><td class="mono">'+esc(x.steamId||'Não vinculada')+'</td><td>'+esc(x.playerName||'Aguardando dados')+'</td><td><span class="badge '+(x.rank==='General de Guerra'?'yellow':'')+'">'+esc(x.rank||'—')+'</span></td><td><b>'+(x.mmr==null?'—':num(x.mmr))+'</b></td><td class="'+(Number(x.adminDelta||0)>0?'ok':Number(x.adminDelta||0)<0?'danger':'')+'">'+(x.adminDelta?((x.adminDelta>0?'+':'')+num(x.adminDelta)):'0')+'</td><td>'+esc(x.kills||0)+' / '+esc(x.deaths||0)+'</td><td>'+esc(x.raids||0)+'</td><td>'+esc(x.events||0)+'</td><td>'+fmt(x.createdAt)+'</td><td>'+(x.steamId?'<button class="btn" data-season-action="'+esc(x.steamId)+'">AÇÕES</button>':'—')+'</td></tr>').join(''):'<tr><td colspan="12"><div class="empty">Nenhum inscrito encontrado.</div></td></tr>';body.querySelectorAll('[data-season-action]').forEach(b=>b.onclick=()=>openActions(b.dataset.seasonAction))}

async function load(){if(loading)return;loading=true;try{const r=await fetch('/api/admin/season/registrations?season=1',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||('Erro '+r.status));rows=Array.isArray(d.registrations)?d.registrations:[];const s=d.summary||{};if($('seasonTotal'))$('seasonTotal').textContent=s.total??0;if($('seasonLinked'))$('seasonLinked').textContent=s.linkedSteam??0;if($('seasonData'))$('seasonData').textContent=s.withSeasonData??0;if($('seasonLeader'))$('seasonLeader').textContent=s.leader?(s.leader.playerName||s.leader.discordName||'—'):'—';render()}catch(e){if($('seasonRows'))$('seasonRows').innerHTML='<tr><td colspan="12"><div class="empty danger">'+esc(e.message)+'</div></td></tr>'}finally{loading=false}}

function actionModal(){let host=$('seasonActionHost');if(host)return host;host=document.createElement('div');host.id='seasonActionHost';document.body.appendChild(host);return host}
function rowBySteam(id){return rows.find(x=>String(x.steamId||'')===String(id||''))}
function openActions(steam){const usable=rows.filter(x=>x.steamId);selectedSteam=steam||selectedSteam||usable[0]?.steamId||'';const host=actionModal();host.innerHTML='<div class="drawerBackdrop" id="seasonActionBackdrop"><aside class="drawer" style="width:min(760px,100%)"><div class="drawerHead"><div><div class="subtitle">SEASON • CONTROLE DE PONTUAÇÃO</div><h2>⚙️ Ações de MMR</h2></div><button class="btn" id="seasonCloseActions">Fechar</button></div><div class="field"><label>Jogador</label><select id="seasonPlayerSelect">'+usable.map(x=>'<option value="'+esc(x.steamId)+'" '+(x.steamId===selectedSteam?'selected':'')+'>'+esc(x.playerName||x.discordName||x.steamId)+' • '+esc(x.steamId)+'</option>').join('')+'</select></div><div id="seasonPlayerSummary" class="stateCard"></div><div class="section"><div class="sectionHead"><div><h2>Alterar pontuação</h2><div class="subtitle">Use valor positivo para adicionar e negativo para remover MMR. Todo ajuste fica auditado.</div></div></div><div class="body"><div class="grid2"><div class="field"><label>Valor do ajuste</label><input id="seasonDelta" type="number" step="0.01" placeholder="Ex.: 25 ou -10"></div><div class="field"><label>Motivo obrigatório</label><input id="seasonReason" placeholder="Ex.: correção de pontuação duplicada"></div></div><div class="toolbar"><button class="btn green" data-quick="10">+10 MMR</button><button class="btn green" data-quick="25">+25 MMR</button><button class="btn red" data-quick="-10">-10 MMR</button><button class="btn red" data-quick="-25">-25 MMR</button><button class="btn yellow" id="seasonApplyDelta">APLICAR AJUSTE</button></div><div id="seasonActionMsg" class="subtitle" style="margin-top:10px"></div></div></div><div class="section"><div class="sectionHead"><div><h2>Histórico completo de MMR</h2><div class="subtitle">Mostra exatamente qual evento gerou/perdeu pontos, multiplicador, valor final e motivo.</div></div><button class="btn" id="seasonReloadHistory">↻</button></div><div class="tableWrap"><table class="table" style="min-width:920px"><thead><tr><th>Data</th><th>Categoria</th><th>Evento</th><th>Base</th><th>Mult.</th><th>MMR</th><th>Resultado</th><th>Detalhes</th><th>Ação</th></tr></thead><tbody id="seasonHistoryRows"><tr><td colspan="9"><div class="empty">Carregando histórico...</div></td></tr></tbody></table></div></div></aside></div>';
$('seasonCloseActions').onclick=()=>host.innerHTML='';$('seasonActionBackdrop').onclick=e=>{if(e.target.id==='seasonActionBackdrop')host.innerHTML=''};$('seasonPlayerSelect').onchange=e=>{selectedSteam=e.target.value;loadHistory()};document.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>{$('seasonDelta').value=b.dataset.quick});$('seasonApplyDelta').onclick=applyDelta;$('seasonReloadHistory').onclick=loadHistory;loadHistory()}

async function loadHistory(){const steam=String($('seasonPlayerSelect')?.value||selectedSteam||'');if(!steam)return;selectedSteam=steam;const body=$('seasonHistoryRows');if(body)body.innerHTML='<tr><td colspan="9"><div class="empty">Carregando...</div></td></tr>';try{const r=await fetch('/api/admin/season/player/'+encodeURIComponent(steam)+'/history?season=1',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Erro ao carregar histórico');const p=d.player||rowBySteam(steam)||{};if($('seasonPlayerSummary'))$('seasonPlayerSummary').innerHTML='<b>'+esc(p.playerName||'Jogador')+'</b><small class="mono">'+esc(steam)+'</small><div class="toolbar" style="margin-top:10px"><span class="badge yellow">MMR '+num(p.mmr||0)+'</span><span class="badge">Patente '+esc(p.rank||'—')+'</span><span class="badge '+(Number(p.adminDelta||0)>=0?'green':'orange')+'">Ajuste ADM '+(Number(p.adminDelta||0)>0?'+':'')+num(p.adminDelta||0)+'</span></div>';const tx=Array.isArray(d.transactions)?d.transactions:[];if(body)body.innerHTML=tx.length?tx.map(t=>'<tr><td>'+fmt(t.happened_at)+'</td><td><span class="badge '+(t.category==='admin'?'orange':'')+'">'+esc(t.category||'—')+'</span></td><td>'+esc(t.event_type||'—')+'</td><td>'+num(t.base_value)+'</td><td>'+num(t.multiplier)+'</td><td class="'+(Number(t.final_value)>0?'ok':Number(t.final_value)<0?'danger':'')+'"><b>'+(Number(t.final_value)>0?'+':'')+num(t.final_value)+'</b></td><td>'+num(t.resulting_mmr)+'</td><td style="max-width:260px;white-space:normal">'+esc(t.details||'—')+'</td><td>'+(Number(t.final_value)!==0&&t.event_type!=='admin_reversal'?'<button class="btn red" data-reverse="'+esc(t.transaction_id)+'" data-value="'+esc(t.final_value)+'">ESTORNAR</button>':'—')+'</td></tr>').join(''):'<tr><td colspan="9"><div class="empty">Nenhum lançamento registrado.</div></td></tr>';body?.querySelectorAll('[data-reverse]').forEach(b=>b.onclick=()=>reverseTx(b.dataset.reverse,b.dataset.value))}catch(e){if(body)body.innerHTML='<tr><td colspan="9"><div class="empty danger">'+esc(e.message)+'</div></td></tr>'}}

async function applyDelta(){const steam=selectedSteam,delta=Number($('seasonDelta')?.value),reason=String($('seasonReason')?.value||'').trim(),msg=$('seasonActionMsg');if(!Number.isFinite(delta)||delta===0){msg.textContent='Informe um valor diferente de zero.';return}if(reason.length<3){msg.textContent='Informe o motivo do ajuste.';return}if(!confirm('Aplicar '+(delta>0?'+':'')+delta+' MMR a este jogador?'))return;try{msg.textContent='Aplicando ajuste...';const r=await fetch('/api/admin/season/player/'+encodeURIComponent(steam)+'/adjust',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({season:1,delta,reason})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Falha ao ajustar');msg.textContent='✅ Ajuste aplicado. MMR: '+num(d.before)+' → '+num(d.after);$('seasonDelta').value='';$('seasonReason').value='';await load();await loadHistory()}catch(e){msg.textContent='❌ '+e.message}}
async function reverseTx(id,value){const reason=prompt('Motivo do estorno deste lançamento de '+value+' MMR:');if(!reason||reason.trim().length<3)return;try{const r=await fetch('/api/admin/season/player/'+encodeURIComponent(selectedSteam)+'/reverse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({season:1,transactionId:id,reason:reason.trim()})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Falha ao estornar');alert('Estorno aplicado: '+num(d.before)+' → '+num(d.after));await load();await loadHistory()}catch(e){alert('Erro: '+e.message)}}

function watchNavigation(){const attach=()=>{addNav();for(const id of ['nav','mobileNav']){const el=$(id);if(el&&!el.dataset.seasonObserved){el.dataset.seasonObserved='1';new MutationObserver(()=>{if(!el.querySelector('[data-season-registrations]'))setTimeout(addNav,0)}).observe(el,{childList:true})}}};attach();[100,300,700,1200,2200,4000].forEach(ms=>setTimeout(attach,ms))}
function boot(){ensureView();watchNavigation();setInterval(()=>{addNav();if($('seasonRegistrations')?.classList.contains('active'))load()},5000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,0));else setTimeout(boot,0);
})();`;
