export const panelServerControlJs = String.raw`
(function(){
  const $=id=>document.getElementById(id);let timer=null;
  async function api(url,opt){const r=await fetch(url,opt||{});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||('Erro '+r.status));return d}
  const post=data=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
  function toast(msg,bad){const t=$('toast');if(!t)return alert(msg);t.textContent=msg;t.classList.remove('hidden');t.style.borderColor=bad?'#943540':'#9b692c';setTimeout(()=>t.classList.add('hidden'),5000)}
  function stateLabel(state){return ({running:'Online',offline:'Desligado',starting:'Iniciando',stopping:'Desligando'}[state]||state||'Indisponível')}
  function create(){const main=document.querySelector('.main');if(!main||$('serverControl'))return;const view=document.createElement('section');view.id='serverControl';view.className='view';view.innerHTML=
    '<div class="section"><div class="sectionHead"><div><h2>Servidor</h2><div class="subtitle">Energia, reinícios e estado da hospedagem em um só lugar.</div></div><span id="serverPowerBadge" class="badge yellow">CARREGANDO</span></div><div class="body">'+
    '<div class="cards"><div class="card accent"><small>ESTADO ATUAL</small><strong id="serverPowerState">—</strong></div><div class="card"><small>TEMPO ONLINE</small><strong id="serverUptime">—</strong></div><div class="card"><small>REDE ↓ ENTRADA</small><strong id="serverNetworkRx">—</strong></div><div class="card"><small>REDE ↑ SAÍDA</small><strong id="serverNetworkTx">—</strong></div><div class="card"><small>SEGURANÇA DE REDE</small><strong id="serverSecurity">Analisando</strong></div><div class="card"><small>REINÍCIO AGENDADO</small><strong id="serverRestartState">Nenhum</strong></div></div>'+
    '<div id="serverPowerNotice" class="stateCard" style="margin-top:14px"><b>Controle seguro da host</b><small>As ações só são confirmadas depois que o Pterodactyl informa o novo estado.</small></div>'+
    '<div class="actionGrid" style="margin-top:12px"><button id="serverStart" class="btn yellow">▶ Ligar servidor</button><button id="serverRestart" class="btn">↻ Reiniciar agora</button><button id="serverStop" class="btn red">■ Desligar servidor</button><button id="serverRefresh" class="btn">Atualizar estado</button></div></div></div>'+
    '<div class="section" style="margin-top:16px"><div class="sectionHead"><div><h2>Reinício com aviso</h2><div class="subtitle">Avisa os jogadores no chat antes de reiniciar.</div></div><span class="badge green">RCON + HOST</span></div><div class="body"><div class="field"><label>Antecedência do aviso</label><select id="serverWarningMinutes"><option value="5">5 minutos</option><option value="15">15 minutos</option><option value="1">1 minuto</option></select><small>O bot envia o primeiro aviso agora e reforça a contagem antes do reinício.</small></div><button id="serverWarningRestart" class="btn yellow" style="width:100%">Agendar reinício com aviso</button></div></div>';
    main.appendChild(view);$('serverStart').onclick=()=>power('start');$('serverStop').onclick=()=>power('stop');$('serverRestart').onclick=()=>power('restart');$('serverRefresh').onclick=load;$('serverWarningRestart').onclick=schedule;
  }
  function nav(){for(const id of ['nav','mobileNav']){const box=$(id);if(!box||box.querySelector('[data-server-control]'))continue;const b=document.createElement('button');b.type='button';b.textContent='🖥 Servidor';b.dataset.serverControl='1';b.dataset.view='serverControl';b.onclick=open;box.appendChild(b)}}
  function open(){create();nav();document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$('serverControl').classList.add('active');document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='serverControl'));if($('pageTitle'))$('pageTitle').textContent='Configurações do Servidor';load()}
  function uptime(ms){let s=Math.floor(Number(ms||0)/1000),d=Math.floor(s/86400);s%=86400;const h=Math.floor(s/3600),m=Math.floor(s%3600/60);return (d?d+'d ':'')+h+'h '+m+'min'}
  async function load(){try{const d=await api('/api/admin/server/power/status',{cache:'no-store'}),state=String(d.state||'unknown');$('serverPowerState').textContent=stateLabel(state);$('serverUptime').textContent=state==='running'?uptime(d.uptime):'—';$('serverNetworkRx').textContent=Number(d.network?.rxMbps||0).toFixed(2)+' Mbps';$('serverNetworkTx').textContent=Number(d.network?.txMbps||0).toFixed(2)+' Mbps';const suspect=d.security?.status==='suspected';$('serverSecurity').textContent=suspect?'⚠ Possível ataque':'✓ Tráfego normal';$('serverSecurity').style.color=suspect?'#ff6b6b':'#57d68d';$('serverPowerBadge').textContent=stateLabel(state).toUpperCase();$('serverPowerBadge').className='badge '+(state==='running'?'green':state==='offline'?'red':'yellow');$('serverStart').disabled=state==='running';$('serverStop').disabled=state==='offline';if(d.scheduledRestart){const when=new Date(d.scheduledRestart.executeAt);$('serverRestartState').textContent=when.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});$('serverPowerNotice').innerHTML='<b>Reinício com aviso programado</b><small>Solicitado por '+String(d.scheduledRestart.requestedBy||'Administrador')+' para '+when.toLocaleString('pt-BR')+'.</small>'}else if(suspect){$('serverRestartState').textContent='Nenhum';$('serverPowerNotice').innerHTML='<b>⚠ Tráfego de entrada anormal</b><small>Possível ataque detectado. Confirme o evento e a mitigação no painel da hospedagem.</small>'}else{$('serverRestartState').textContent='Nenhum';$('serverPowerNotice').innerHTML='<b>Monitoramento ativo</b><small>Rede estável. O detector compara picos consecutivos com a média normal do servidor.</small>'}}catch(e){$('serverPowerBadge').textContent='FALHA';$('serverPowerBadge').className='badge red';toast(e.message,true)}}
  async function power(signal){const labels={start:'ligar',stop:'desligar',restart:'reiniciar'};if(!confirm('Deseja realmente '+labels[signal]+' o servidor agora?'))return;const buttons=[$('serverStart'),$('serverStop'),$('serverRestart')];buttons.forEach(b=>b.disabled=true);try{await api('/api/admin/server/power',post({signal}));toast('Ação confirmada pela host.');await load()}catch(e){toast(e.message,true);await load()}finally{buttons.forEach(b=>b.disabled=false)}}
  async function schedule(){const minutes=Number($('serverWarningMinutes').value);if(!confirm('Avisar no jogo e reiniciar o servidor em '+minutes+' minuto(s)?'))return;const b=$('serverWarningRestart');b.disabled=true;try{const d=await api('/api/admin/server/restart-warning',post({minutes}));toast('Aviso enviado. Reinício agendado.');await load()}catch(e){toast(e.message,true)}finally{b.disabled=false}}
  function boot(){create();nav();setInterval(nav,2000);timer=setInterval(()=>{if($('serverControl')?.classList.contains('active'))load()},5000)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
`;
