export const publicMilitaryThemeCss = String.raw`<style id="gf-public-military-theme">
:root{
  --gf-bg:#050708;--gf-panel:#090d0f;--gf-panel2:#0d1215;--gf-line:#293238;
  --gf-line-soft:#20272b;--gf-text:#f4f2ed;--gf-muted:#8d959a;--gf-muted2:#626a70;
  --gf-orange:#ffb000;--gf-orange2:#ff7b00;--gf-green:#35da86;--gf-red:#ef5b50;
  --gf-page:1594px;--gf-ease:cubic-bezier(.2,.8,.2,1);
  --bg:#050708!important;--panel:#090d0f!important;--panel2:#0d1215!important;--line:#293238!important;
  --text:#f4f2ed!important;--txt:#f4f2ed!important;--muted:#8d959a!important;--mut:#8d959a!important;
  --yellow:#ffb000!important;--orange:#ffb000!important;--purple:#ffb000!important;--p:#ffb000!important;--y:#ffb000!important
}
*{box-sizing:border-box}html{background:var(--gf-bg)!important;scroll-behavior:smooth}body{margin:0!important;min-height:100vh;background:radial-gradient(ellipse at 0% 38%,#a4470913,transparent 34%),radial-gradient(ellipse at 100% 44%,#b4510a12,transparent 34%),var(--gf-bg)!important;color:var(--gf-text)!important;font-family:Arial,Helvetica,sans-serif!important;overflow-x:hidden}body:before,body:after{display:none!important}::selection{background:var(--gf-orange);color:#070809}a{color:inherit}

/* Shared chrome: same proportions and visual language as the Home header */
.gfChrome{height:66px!important;background:#050708ed!important;border-bottom:1px solid #1b2024!important;box-shadow:none!important;backdrop-filter:blur(14px)!important;-webkit-backdrop-filter:blur(14px)!important}.gfChromeInner{height:100%!important;width:min(var(--gf-page),87.4%)!important;max-width:none!important;grid-template-columns:1fr auto 1fr!important;gap:24px!important}.gfChromeBrand{gap:16px!important;color:#fff!important;font-size:12px!important;letter-spacing:.18em!important}.gfChromeBrand i{width:42px!important;height:42px!important;border:0!important;border-radius:0!important;background:linear-gradient(135deg,#ffc52c,#ffa600)!important;color:#050708!important;box-shadow:inset 0 0 0 1px #ffd66c44!important;font-size:11px!important}.gfChromeBrand b{font-size:10px!important;letter-spacing:.18em!important}.gfNav{gap:10px!important}.gfNavItem{height:44px!important;padding:0 20px!important;border:1px solid transparent!important;border-radius:0!important;background:transparent!important;color:#92999e!important;font-size:9px!important;letter-spacing:.13em!important;transition:color .25s,border-color .25s,transform .25s!important}.gfNavItem:hover{color:#fff!important;transform:translateY(-1px)!important}.gfNavItem.active{color:#fff!important;border-color:#a96b00!important;background:#090d0f!important;box-shadow:none!important}.gfChromeRight{gap:10px!important}.gfUser,.gfLogin,.gfAdminLink{min-height:44px!important;padding:0 12px!important;border-radius:0!important;border:1px solid #22282c!important;background:#090d0f!important;color:#f1f0eb!important;font-size:9px!important;letter-spacing:.06em!important;box-shadow:none!important}.gfUser{max-width:190px!important}.gfOnline{width:8px!important;height:8px!important;flex-basis:8px!important;background:var(--gf-green)!important;box-shadow:0 0 0 0 #35da8666!important}.gfAdminLink{border-color:#8a5a0f!important;color:#ffc05a!important}.gfMenuToggle{border-radius:0!important;background:#090d0f!important;border-color:#293238!important}.gfDrawer{background:#070a0b!important;border-color:#293238!important}.gfDrawerHead,.gfDrawerFoot,.gfDrawerItem{border-color:#20272b!important}.gfDrawerBrand i{border-radius:0!important;background:var(--gf-orange)!important;color:#050708!important}.gfDrawerItem.active b,.gfDrawerItem span{color:var(--gf-orange)!important}

/* Remove legacy mini-headers from pages already using the shared chrome */
body>.top,.wrap>.top,main.wrap>header.top{display:none!important}

/* Page geometry */
.wrap,.container,.main,.content,.w{width:min(var(--gf-page),87.4%)!important;max-width:none!important;margin-left:auto!important;margin-right:auto!important}.wrap,.w{padding-top:34px!important}.hero{box-shadow:none!important;border-radius:0!important}.hero h1,.hero h2,.heroTitle,h1,h2,.featureTitle{font-family:Impact,"Arial Narrow",Arial,sans-serif!important;text-transform:uppercase!important;letter-spacing:-.018em!important}.hero h1 span,.hero h2 span,.hero h1 em,.hero h2 em,h1 span,h2 span,h1 em,h2 em{background:none!important;color:var(--gf-orange)!important;-webkit-text-fill-color:var(--gf-orange)!important;text-shadow:none!important}.hero p,.subtitle,.muted,.mut,.sectionLead,.sub{color:#9aa0a4!important}.ey,.eyebrow,.live,.cardLabel,.promoTag,.hero small{color:var(--gf-orange)!important}.mark,.logo i{border-radius:0!important;background:var(--gf-orange)!important;color:#050708!important;border-color:var(--gf-orange)!important;box-shadow:none!important}

/* Page heroes use the same dark + warm glow surface as the Home content */
body .hero:not(.communityCard){background:radial-gradient(circle at 82% 15%,#ff990018,transparent 34%),linear-gradient(135deg,#0b1114ef,#060b0eee)!important;border:1px solid var(--gf-line)!important;padding:38px 34px!important}.hero h1,.hero h2{line-height:.93!important}.hero p{line-height:1.6!important}.ey,.eyebrow,.live{border-radius:0!important;border:1px solid #765016!important;background:#120e07!important;padding:7px 10px!important;font-size:9px!important;font-weight:950!important;letter-spacing:.16em!important}.dot{background:var(--gf-orange)!important;box-shadow:none!important}

/* Cards and surfaces */
.section,.card,.choice,.event,.eventCard,.drawer,.login,.stateCard,.financeHero,.financeMetric,.modal .box,.contact,.seasonCta,.storeCta,.box,.q,.drawing,.vipCard,.stat,.pod,.table,.rankCard,.rank,.patente,.node,.animal,.quiz,.notice,.steamBox,.numberCard,.wipe,.perk,.flow,.checkout,.priceBox,.idcard,.population,.award,.promo,.prize,.resetNotice,.rankcard,.discordRank{background:linear-gradient(145deg,#0b1114,#060b0e)!important;border:1px solid var(--gf-line)!important;box-shadow:none!important;border-radius:0!important}.section:before,.section:after,.card:before,.card:after,.choice:before,.financeHero:before,.stateCard:before,.seasonCta:before,.storeCta:before,.perk:before,.rankcard:before,.prize:after{display:none!important}.section:hover,.card.click:hover,.choice:hover,.vipCard:hover,.pod:hover,.rankCard:hover,.rank:hover,.patente:hover,.perk:hover{border-color:#3a454b!important;box-shadow:none!important}.card,.choice,.vipCard,.pod,.rankCard,.rank,.patente,.btn,.buy,.tab,.gfNavItem,.perk{transition:border-color .22s ease,background .22s ease,color .22s ease,transform .22s var(--gf-ease)!important}@media(hover:hover){.card.click:hover,.choice:hover,.vipCard:hover,.pod:hover,.rankCard:hover,.rank:hover,.patente:hover,.perk:hover{transform:translateY(-2px)!important}}

/* Buttons */
.btn,.buy,.close,.toggle,.tab,.pay,.steamLogin,.copy,.nav a,.seasonActions a,.outlineBtn,.back,.adminBtn{border-radius:0!important;box-shadow:none!important;font-family:Arial,Helvetica,sans-serif!important;font-weight:950!important;letter-spacing:.06em!important}.btn.primary,.btn.yellow,.btn.blue,.btn.gold,.buy,.toggle,.tab.active,.seasonMain,.cardpay,.gold{background:linear-gradient(120deg,#ffba08,#ffa800)!important;border-color:#ffc326!important;color:#070809!important}.btn.dark,.btn:not(.primary):not(.gold):not(.yellow):not(.blue):not(.green):not(.red),.outlineBtn,.back,.steamLogin,.copy{background:#090d0f!important;border:1px solid #32393d!important;color:#f4f2ed!important}.btn.red{background:#8f2822!important;border-color:#d65046!important;color:#fff!important}.btn.green{background:#12301f!important;border-color:#285f3f!important;color:#d7ffe8!important}.btn:hover,.buy:hover,.outlineBtn:hover,.back:hover{transform:translateY(-1px)!important;border-color:#b9760d!important}.tab{background:#090d0f!important;border-color:#293238!important;color:#8d959a!important}.tab.active{color:#070809!important}.badge,.pill,.account,.status,.loginLink,.head span,.tag{border-radius:0!important;background:#090d0f!important;border-color:#293238!important}.badge{background:var(--gf-orange)!important;color:#080808!important}.pill{color:#9aa0a4!important}.pill strong{color:#f4f2ed!important}

/* Form controls */
input,select,textarea{border-radius:0!important;background:#070b0d!important;border:1px solid #293238!important;color:#fff!important;box-shadow:none!important;font-family:Arial,Helvetica,sans-serif!important}input:focus,select:focus,textarea:focus{border-color:var(--gf-orange)!important;box-shadow:0 0 0 1px #ffb00022!important;outline:none!important}.field label{color:#92999e!important;letter-spacing:.08em!important}

/* Leaderboard */
.stats{gap:12px!important}.stat{padding:15px!important}.stat small{color:#788086!important}.stat strong{color:#f4f2ed!important}.yellow{color:var(--gf-orange)!important}.pod.first{border-color:#8b6018!important;background:radial-gradient(circle at 50% 0,#ffae0017,transparent 42%),linear-gradient(145deg,#0b1114,#060b0e)!important}.pod .value,.pod.first .value{color:var(--gf-orange)!important}.table{overflow:hidden!important}.thead,.row{border-color:#20272b!important}.row{border-top:1px solid #20272b!important}.row:hover{background:#0d1316!important}.steam{color:#667076!important}.controls .toggle{font-weight:950!important}.tabs{scrollbar-color:#5e4316 #090d0f!important}

/* Store */
.vipCard{overflow:hidden!important}.vipCard .accent{height:2px!important}.vipCard.bronze .accent{background:#b87333!important}.vipCard.prata .accent{background:#c8ccd0!important}.vipCard.ouro .accent{background:var(--gf-orange)!important}.vipCard .visual{background:#070b0d!important;border-color:#20272b!important}.vipCard .visual img{border-radius:0!important}.vipCard .price{font-family:Impact,"Arial Narrow",Arial,sans-serif!important;color:#f4f2ed!important;letter-spacing:-.02em!important}.vipCard .head span{border-radius:0!important}.vipCard .buy,.vipCard.bronze .buy,.vipCard.prata .buy,.vipCard.ouro .buy{background:linear-gradient(120deg,#ffba08,#ffa800)!important;border:1px solid #ffc326!important;color:#080808!important}.steamBox.ok{border-color:#285f3f!important;background:#0b1110!important}.pix{background:#35da86!important;color:#07140d!important}.cardPay,.cardpay{background:var(--gf-orange)!important;color:#080808!important}.stripePay{background:#111722!important;border:1px solid #303b4a!important;color:#eef3ff!important}.flash{border-radius:0!important}

/* Season / guides */
.quick{gap:12px!important}.q small{color:#788086!important}.q b{color:#f4f2ed!important}.promo,.prize,.resetNotice{border-color:#604716!important;background:radial-gradient(circle at 88% 12%,#ff9b0017,transparent 35%),linear-gradient(145deg,#0b1114,#060b0e)!important;color:#f4f2ed!important}.promoTag{border-radius:0!important;background:var(--gf-orange)!important;color:#080808!important}.price strong,.min,.podXp,.xp,.rank small{color:var(--gf-orange)!important}.rankCard:last-child,.rank:last-child,.patente:last-child{border-color:#745017!important}.rankCard .stars,.rank .stars,.patente .stars,.rankstar{color:var(--gf-orange)!important;text-shadow:none!important}.formula{background:#070b0d!important;border-color:#20272b!important}.faq details{border-color:#20272b!important}.faq summary:after{color:var(--gf-orange)!important}.discordLogo{border-radius:0!important;box-shadow:none!important}.seasonGuideCta,section[style*="#7046a0"]{border:1px solid #704c16!important;background:linear-gradient(135deg,#0b1114,#060b0e)!important;border-radius:0!important;box-shadow:none!important}.seasonGuideCta a,section[style*="#7046a0"] a{background:linear-gradient(120deg,#ffba08,#ffa800)!important;border:1px solid #ffc326!important;border-radius:0!important;color:#080808!important}.seasonGuideCta [style*="#d9bfff"],section[style*="#7046a0"] [style*="#d9bfff"]{color:var(--gf-orange)!important}

/* Promo */
.glow{background:radial-gradient(circle at 50% 5%,#ffae0018,transparent 30%),radial-gradient(circle at 88% 40%,#ff76000e,transparent 24%)!important}.priceBox{border-color:#765016!important}.price,.price sup,.priceBox b,.giftLink{color:#ffca4f!important}.step em{border-radius:0!important;background:#1a1307!important;border-color:#765016!important;color:#ffc44d!important}.gift{border-color:#765016!important}.giftLink{border-radius:0!important;background:#070b0d!important}.qr img,#qrImg{border-radius:0!important}.copyrow textarea{background:#070b0d!important}

/* Integrity / audit */
.toolbar{gap:14px!important}.toolbar .tabs{background:#070b0d!important;border-color:#293238!important}.tabs button{border-radius:0!important}.tabs button.active{background:var(--gf-orange)!important;color:#080808!important}.list .row{background:linear-gradient(145deg,#0b1114,#060b0e)!important;border-color:#293238!important;border-top-color:#3b454a!important;box-shadow:none!important}.list .row.warn{border-top-color:var(--gf-orange)!important}.list .row.ban{border-top-color:#d65046!important}.list .row.verify{border-top-color:var(--gf-green)!important}.steamAvatar,.steamAvatarFallback,.steamLink,.meta span{border-radius:0!important;background:#070b0d!important}.reason{border-color:#20272b!important}

/* Finance and misc public surfaces */
.financeTable{background:#070b0d!important}.cashBar.in{background:var(--gf-orange)!important}.track,.bar{background:#151a1e!important}.fill,.bar span{background:var(--gf-orange)!important}.homeMedia,.heroMedia,.banner,.siteBanner,.topBanner,img[src*="banner-guerra-fria-infinito"]{display:none!important}
footer,.footer,.foot{color:#596167!important;border-color:#1b2024!important}

a:focus-visible,button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible{outline:2px solid var(--gf-orange)!important;outline-offset:3px!important}

@media(max-width:1300px){.gfChromeInner,.wrap,.container,.main,.content,.w{width:calc(100% - 48px)!important}.gfNavItem{padding:0 12px!important}.hero h1,.hero h2{font-size:clamp(44px,6.2vw,70px)!important}}
@media(max-width:760px){body{padding-bottom:max(30px,env(safe-area-inset-bottom))!important}.gfChrome{height:62px!important}.gfChromeInner{width:calc(100% - 32px)!important;grid-template-columns:auto 1fr auto!important;gap:8px!important}.gfChromeBrand b{display:none!important}.gfNav{display:none!important}.gfUser,.gfLogin{min-height:40px!important;padding:0 9px!important;font-size:7px!important;max-width:100px!important}.gfAdminLink{display:none!important}.gfMenuToggle{display:block!important}.wrap,.container,.main,.content,.w{width:calc(100% - 32px)!important}.wrap,.w{padding-top:24px!important}body .hero:not(.communityCard){padding:28px 20px!important;margin-top:12px!important}.hero h1,.hero h2{font-size:clamp(38px,10vw,52px)!important;line-height:.96!important}.hero p,.subtitle,.lead,.sectionLead{font-size:12px!important;line-height:1.65!important}.stats{grid-template-columns:1fr 1fr!important}.podium{grid-template-columns:1fr!important}.grid{grid-template-columns:1fr!important}.thead,.row{grid-template-columns:38px 1fr 96px!important}.section,.card,.choice,.financeHero,.stateCard,.vipCard,.stat,.pod,.table,.perk,.flow,.checkout{border-radius:0!important}.gfDrawer{display:flex!important}.gfDrawerBackdrop{display:block!important}}
@media(max-width:520px){.gfChromeInner,.wrap,.container,.main,.content,.w{width:calc(100% - 24px)!important}.stats{grid-template-columns:1fr!important}body .hero:not(.communityCard){padding:24px 16px!important}.hero h1,.hero h2{font-size:clamp(35px,11vw,48px)!important}.ey,.eyebrow,.live{font-size:7px!important;letter-spacing:.11em!important}}
</style>`;