export const publicMilitaryThemeCss = String.raw`<style id="gf-public-military-theme">
:root{--gf-bg:#07090b;--gf-panel:#0b0e11;--gf-panel2:#0e1114;--gf-line:#20252a;--gf-text:#f4f4f1;--gf-muted:#747b81;--gf-orange:#f59d0a;--gf-red:#f05a24;--gf-green:#38cf7a;--bg:#07090b!important;--panel:#0b0e11!important;--panel2:#0e1114!important;--line:#20252a!important;--text:#f4f4f1!important;--muted:#747b81!important;--yellow:#f59d0a!important;--orange:#f59d0a!important;--purple:#f59d0a!important;--p:#f59d0a!important;--y:#f59d0a!important;--txt:#f4f4f1!important;--mut:#747b81!important}
*{box-sizing:border-box}html,body{background:#07090b!important;color:#f4f4f1!important}body{background-image:none!important;font-family:Arial,Helvetica,sans-serif!important}body:before,body:after{display:none!important}::selection{background:#f59d0a;color:#080808}a{color:inherit}
/* shared top navigation */
.gfChrome{background:#07090bf8!important;border-bottom:1px solid #171b1f!important;box-shadow:none!important;backdrop-filter:blur(12px)!important}.gfChromeInner{width:min(1100px,calc(100% - 26px))!important}.gfChromeBrand i{width:26px!important;height:26px!important;border:0!important;border-radius:0!important;transform:none!important;background:#f59d0a!important;color:#080808!important;box-shadow:none!important;font-size:8px!important}.gfChromeBrand b{font-size:9px!important;letter-spacing:.12em!important}.gfChromeBrand small{display:none!important}.gfBack{border-radius:0!important;background:#0b0e11!important;border-color:#282d32!important;height:30px!important;font-size:8px!important}.gfNav{gap:11px!important}.gfNavItem{height:30px!important;border-radius:0!important;padding:0 5px!important;color:#8c9399!important;background:transparent!important;border-color:transparent!important;font-size:8px!important;letter-spacing:.08em!important}.gfNavItem span{display:none!important}.gfNavItem.active,.gfNavItem:hover{color:#fff!important;background:transparent!important;box-shadow:none!important}.gfNavItem.active{border-bottom:1px solid #f59d0a!important}.gfUser{font-size:8px!important;border:1px solid #30353a!important;padding:7px 9px!important;max-width:130px!important;background:#0b0e11!important}.gfOnline{background:#38cf7a!important;box-shadow:none!important}.gfBetaStrip{background:#0b0e11!important;border-color:#20252a!important;box-shadow:none!important;color:#8d949a!important}.gfBetaStrip strong{color:#f59d0a!important}.gfBetaStrip a{border-radius:0!important;background:#0e1114!important;border-color:#2b3035!important}.gfBetaStrip .join{background:#f59d0a!important;border-color:#f59d0a!important;color:#080808!important}
/* page canvas */
.wrap,.container,.main,.content{max-width:1100px!important}.hero{background:#07090b!important;box-shadow:none!important}.hero h1,.hero h2,.heroTitle,h1,h2{font-family:Impact,"Arial Narrow",Arial,sans-serif!important;letter-spacing:-.02em!important;text-transform:uppercase!important}.hero h1 span,.hero h2 span,.hero h1 em,.hero h2 em,h1 span,h2 span{background:none!important;color:#f59d0a!important;-webkit-text-fill-color:#f59d0a!important}.hero p,.subtitle,.muted,.mut,.sectionLead{color:#747b81!important}.ey,.eyebrow,.cardLabel,.accent strong,.hero small{color:#f59d0a!important}.mark,.logo i{border-radius:0!important;background:#f59d0a!important;color:#080808!important;border-color:#f59d0a!important;box-shadow:none!important}
/* flat panels everywhere */
.section,.card,.choice,.event,.drawer,.login,.stateCard,.financeHero,.financeMetric,.modal,.contact,.seasonCta,.storeCta,.box,.q,.drawing,.vipCard,.stat,.pod,.table,.rankCard,.rank,.patente,.node,.animal,.quiz,.notice,.steamBox,.numberCard,.wipe{background:#0b0e11!important;border:1px solid #20252a!important;box-shadow:none!important;border-radius:0!important}.section:before,.section:after,.card:before,.card:after,.choice:before,.financeHero:before,.stateCard:before,.seasonCta:before,.storeCta:before{display:none!important}.section:hover,.card.click:hover,.choice:hover,.vipCard:hover,.pod:hover,.rankCard:hover,.rank:hover,.patente:hover{border-color:#343a40!important;box-shadow:none!important;transform:none!important}
/* buttons and controls */
.btn,.buy,.close,.toggle,.tab,.pay,.steamLogin,.copy,.nav a,.seasonActions a{border-radius:0!important;box-shadow:none!important}.btn.yellow,.btn.blue,.buy,.close,.toggle,.tab.active,.seasonMain{background:#f59d0a!important;border-color:#f59d0a!important;color:#080808!important}.btn.red{background:#f05a24!important;border-color:#f05a24!important}.btn.green{background:#14311f!important;border-color:#285f3f!important}.tab{background:#0b0e11!important;border-color:#20252a!important;color:#8c9399!important}.tab.active{color:#080808!important}.badge,.pill,.account,.status,.loginLink,.head span{border-radius:0!important;background:#0b0e11!important;border-color:#282d32!important}.badge{background:#f59d0a!important;color:#080808!important}input,select,textarea{border-radius:0!important;background:#090b0d!important;border-color:#282d32!important;color:#fff!important;box-shadow:none!important}input:focus,select:focus,textarea:focus{border-color:#f59d0a!important;box-shadow:none!important}
/* leaderboard */
.wrap>.top{border-bottom:1px solid #171b1f!important;padding-bottom:14px!important}.stats{gap:8px!important}.stat{padding:14px!important}.stat small{color:#747b81!important}.stat strong{color:#f4f4f1!important}.yellow{color:#f59d0a!important}.pod.first{border-color:#745017!important}.pod .value,.pod.first .value{color:#f59d0a!important}.table{overflow:hidden!important}.thead,.row{border-color:#20252a!important}.row{border-top:1px solid #20252a!important}.row:hover{background:#0d1114!important}.steam{color:#60676d!important}.controls .toggle{font-weight:950!important}
/* store */
.vipCard .accent{height:1px!important}.vipCard.bronze .accent{background:#b87333!important}.vipCard.prata .accent{background:#c8ccd0!important}.vipCard.ouro .accent{background:#f59d0a!important}.vipCard .visual{background:#090b0d!important;border-color:#20252a!important}.vipCard .visual img{border-radius:0!important}.vipCard .price{font-family:Impact,"Arial Narrow",Arial,sans-serif!important;color:#f4f4f1!important}.vipCard .head span{border-radius:0!important}.vipCard .buy{background:#f59d0a!important;color:#080808!important}.vipCard.bronze .buy,.vipCard.prata .buy,.vipCard.ouro .buy{background:#f59d0a!important;color:#080808!important}.steamBox.ok{border-color:#285f3f!important;background:#0b0e11!important}.pix{background:#38cf7a!important;color:#07140d!important}.cardPay{background:#f59d0a!important;color:#080808!important}
/* season / integrity */
.top{background:#07090bf7!important;border-color:#171b1f!important}.notice{color:#c9c9c5!important}.track{background:#15191c!important}.fill{background:#f59d0a!important}.rankCard:last-child,.rank:last-child,.patente:last-child{border-color:#745017!important;box-shadow:none!important}.rankCard .stars,.rank .stars,.patente .stars{color:#f59d0a!important;text-shadow:none!important}.formula{background:#090b0d!important;border-color:#20252a!important}.faq details{border-color:#20252a!important}.faq summary:after{color:#f59d0a!important}.financeTable{background:#090b0d!important}.cashBar.in{background:#f59d0a!important}
/* kill old decorative/banner media anywhere public */
.homeMedia,.heroMedia,.banner,.siteBanner,.topBanner,img[src*="banner-guerra-fria-infinito"]{display:none!important}
@media(max-width:760px){body{padding-bottom:max(30px,env(safe-area-inset-bottom))!important}.gfChrome{position:relative!important;height:52px!important;inset:auto!important;pointer-events:auto!important}.gfChromeInner{height:52px!important}.gfBack{display:none!important}.gfChromeBrand{display:flex!important}.gfUser{display:flex!important;margin-left:auto!important}.gfNav{display:none!important}.section,.card,.choice,.financeHero,.stateCard,.vipCard,.stat,.pod,.table{border-radius:0!important}.wrap{width:calc(100% - 24px)!important}.hero{margin-top:28px!important}.hero h1,.hero h2{font-size:clamp(38px,12vw,56px)!important}.stats{grid-template-columns:1fr 1fr!important}.podium{grid-template-columns:1fr!important}.grid{grid-template-columns:1fr!important}.thead,.row{grid-template-columns:38px 1fr 96px!important}.gfBetaStrip{position:relative!important;top:auto!important}}
</style>`;
