export const storeProductDetails=String.raw`
(function(){
 const root=document.getElementById('productModal'),items=document.getElementById('kitContents');let product=null,requestVersion=0;
 const money=n=>Number(n).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 const duration=s=>!s?'Sem espera':s>=86400?Math.floor(s/86400)+' dias':s>=3600?Math.floor(s/3600)+'h'+(s%3600?' '+Math.ceil(s%3600/60)+'min':''):Math.ceil(s/60)+' minutos';
 const selection=()=>window.gfSelectedServer||null;
 const quote=t=>window.gfStorePricing?.[selection()]?.[t];
 function refreshProduct(){
  document.querySelectorAll('.vipCard .buy').forEach(b=>{const q=quote(b.dataset.tier);if(q){b.dataset.name=q.name;b.dataset.price=q.price;}});
  if(!product)return;if(!selection()){document.getElementById('detailName').textContent=product.tier==='duo'?'Super Combo':product.name;document.getElementById('detailRegular').textContent='';document.getElementById('detailOffer').textContent='';document.getElementById('detailPrice').textContent='Selecione um servidor para ver o preço';document.getElementById('detailGift').hidden=product.tier==='duo';document.getElementById('detailNote').textContent=product.tier==='duo'?'Duo: você + 1 amigo. Trio: você + 2 amigos. Escolha um servidor ou compre nos dois.':'Escolha onde quer ativar o VIP para consultar o preço e os itens.';return;}document.getElementById('detailArt').src='/api/store/art/vip-'+(product.tier==='duo'&&selection()!=='solo-duo'?'trio':product.tier)+'?v=rust2';const q=quote(product.tier)||product;product={...product,...q};document.getElementById('detailName').textContent=product.name;document.getElementById('detailPrice').textContent=money(product.price)+' / 30 dias';document.getElementById('detailRegular').textContent=money(q.regularPrice||q.price);document.getElementById('detailOffer').textContent=selection()==='both'?'Preço promocional + 10% nos dois servidores':'Preço promocional';document.getElementById('detailGift').hidden=product.tier==='duo';document.getElementById('detailNote').textContent=product.tier==='duo'?(selection()==='both'?'Você e o primeiro amigo recebem os três VIPs nos dois servidores. O segundo amigo recebe os três VIPs no Trio. Dois convites exclusivos.':'Inclui Bronze + Prata + Ouro para você e '+(selection()==='trio'?'dois amigos. Após pagar, envie um convite exclusivo a cada amigo.':'um amigo. Após pagar, envie o convite exclusivo ao amigo.')):'Compre para sua conta ou presenteie um amigo. Ele entra com Discord e Steam para ativar o presente.';
 }
 function renderItems(kit){
  const header=document.createElement('div');header.className='kitHeader';const name=document.createElement('b');name.textContent=kit.name;const time=document.createElement('small');time.textContent='Resgate: '+duration(kit.cooldownSeconds)+(kit.wipeDelaySeconds?' • Após wipe: '+duration(kit.wipeDelaySeconds):'');header.append(name,time);items.append(header);
  for(const [category,label] of [['recursos','Recursos'],['componentes','Componentes'],['armas','Armas'],['roupas','Roupas']]){
   const rewards=kit.items.filter(i=>(i.category||'recursos')===category);if(!rewards.length)continue;const heading=document.createElement('h4');heading.className='kitCategory';heading.textContent=label;items.append(heading);const grid=document.createElement('div');grid.className='kitGrid';
   for(const item of rewards){const tile=document.createElement('div');tile.className='kitItem';const img=document.createElement('img');img.src=item.icon;img.alt=item.name;img.loading='lazy';img.referrerPolicy='no-referrer';img.onerror=()=>img.remove();const quantity=document.createElement('span');quantity.className='quantity';quantity.textContent='×'+item.amount.toLocaleString('pt-BR');const label=document.createElement('b');label.textContent=item.name;tile.append(img,quantity,label);if(item.includedIn||item.loadedAmmo){const info=document.createElement('small');info.textContent=item.includedIn?'Acessório de '+item.includedIn:'Carregado: '+item.loadedAmmo+' × '+item.ammoType;tile.append(info);}if(item.skin&&item.skin!=='0'){const skin=document.createElement('small');skin.textContent='Skin '+item.skin;tile.append(skin);}grid.append(tile);}items.append(grid);
  }
 }
 async function loadKits(){refreshProduct();if(!product)return;if(!selection()){items.textContent='Selecione um servidor para consultar os itens.';return;}const seq=++requestVersion,tier=product.tier;items.replaceChildren();items.textContent='Consultando os itens dos servidores…';try{
  const servers=selection()==='both'?['solo-duo','trio']:[selection()];const rows=await Promise.all(servers.map(async server=>{const r=await fetch('/api/store/catalog/'+tier+'?server='+server,{cache:'no-store'});if(!r.ok)throw Error();return {server,...await r.json()};}));if(seq!==requestVersion)return;items.replaceChildren();
  for(const d of rows){if(rows.length>1){const h=document.createElement('h3');h.textContent=d.server==='trio'?'Servidor Trio':'Servidor Solo/Duo';items.append(h);}if(!d.available||!d.complete||d.stale){const warning=document.createElement('p');warning.className='kitNotice';warning.textContent=!d.available?(d.message||'Itens temporariamente indisponíveis.'):d.stale?'Exibindo a última lista confirmada.':'Alguns kits estão sendo sincronizados.';items.append(warning);}for(const kit of d.kits||[])renderItems(kit);if(d.updatedAt){const stamp=document.createElement('p');stamp.className='kitSource';stamp.textContent='Itens do servidor • '+new Date(d.updatedAt).toLocaleString('pt-BR')+' • imagens dos itens base do Rust';items.append(stamp);}}
 }catch{if(seq===requestVersion)items.textContent='Não foi possível consultar os itens agora. Reabra o pacote para tentar novamente.';}}
 document.querySelectorAll('.vipCard .buy').forEach(b=>b.onclick=()=>{product={...b.dataset};document.dispatchEvent(new Event('gf:clear-server'));document.getElementById('detailArt').src='/api/store/art/vip-'+product.tier+'?v=rust2';refreshProduct();document.getElementById('detailArt').alt=product.name;root.classList.add('open');loadKits();});
 const close=()=>{root.classList.remove('open');requestVersion++;};document.getElementById('productClose').onclick=close;root.onclick=e=>{if(e.target===root)close()};document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
 document.getElementById('detailBuy').onclick=()=>{if(!product)return;close();document.dispatchEvent(new CustomEvent('gf:checkout',{detail:{...product,gift:false}}));};document.getElementById('detailGift').onclick=()=>{if(!product)return;close();document.dispatchEvent(new CustomEvent('gf:checkout',{detail:{...product,gift:true}}));};
 document.addEventListener('gf:server',loadKits);refreshProduct();
  async function gifts(){try{const r=await fetch('/api/store/gift/purchases',{cache:'no-store'});if(!r.ok)return;const rows=await r.json(),container=document.getElementById('giftPurchases');container.replaceChildren();if(!rows.length){container.textContent='Seus presentes e links aparecerão aqui após o pagamento.';return;}const labels={available:'Pronto para enviar',delivering:'Amigo ativando o VIP',redeemed:'Presente resgatado',expired:'Link expirado'};for(const row of rows){const box=document.createElement('div');box.className='purchase';const name=document.createElement('p');name.textContent=row.product+' • Compra #'+row.id+' • '+(labels[row.status]||'Aguardando pagamento');box.append(name);if(row.claimUrl){const input=document.createElement('input');input.value=row.claimUrl;input.readOnly=true;input.setAttribute('aria-label','Link do presente');const button=document.createElement('button');button.textContent='COPIAR PRESENTE';button.onclick=async()=>{try{await navigator.clipboard.writeText(row.claimUrl);button.textContent='COPIADO ✓'}catch{input.select();}};box.append(button,input);}container.append(box);}}catch{}}
  gifts();setInterval(gifts,10000);
  fetch('/api/store/popular').then(r=>r.ok?r.json():null).then(d=>{if(!['bronze','prata','ouro'].includes(d?.tier))return;const card=document.querySelector('.vipCard.'+d.tier);if(!card)return;card.classList.add('popular');const badge=document.createElement('span');badge.className='popularBadge';badge.textContent='MAIS POPULAR';card.querySelector('.visual').append(badge);}).catch(()=>{});
})();`;
