export const storeProductDetails=String.raw`
(function(){
  const root=document.getElementById('productModal'),items=document.getElementById('kitContents');let product=null,requestVersion=0;
  const duration=s=>!s?'Sem espera':s>=86400?(s/86400).toLocaleString('pt-BR')+' dias':s>=3600?(s/3600).toLocaleString('pt-BR')+' horas':Math.ceil(s/60)+' minutos';
  async function loadKits(){if(!product)return;const seq=++requestVersion,tier=product.tier;items.replaceChildren();const loading=document.createElement('p');loading.className='kitLoading';loading.textContent='Consultando os itens do servidor…';items.append(loading);
    try{const server=document.getElementById('serverSolo').classList.contains('active')?'solo-duo':'trio';const r=await fetch('/api/store/catalog/'+tier+'?server='+server,{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json();if(seq!==requestVersion)return;items.replaceChildren();
      if(!d.available||!d.complete||d.stale){const warning=document.createElement('p');warning.className='kitNotice';warning.textContent=!d.available?(d.message||'Itens temporariamente indisponíveis.'):d.stale?'Exibindo a última lista confirmada. A conexão com o servidor está sendo atualizada.':'Alguns kits ainda estão sendo sincronizados. Abaixo estão os itens já confirmados.';items.append(warning);}
      for(const kit of d.kits||[]){const title=document.createElement('div');title.className='kitHeader';const name=document.createElement('b');name.textContent=kit.name;const time=document.createElement('small');time.textContent='Resgate: '+duration(kit.cooldownSeconds)+(kit.wipeDelaySeconds?' • Após wipe: '+duration(kit.wipeDelaySeconds):'');title.append(name,time);items.append(title);const grid=document.createElement('div');grid.className='kitGrid';
        for(const item of kit.items){const tile=document.createElement('div');tile.className='kitItem';const img=document.createElement('img');img.src=item.icon;img.alt=item.name;img.loading='lazy';img.referrerPolicy='no-referrer';img.onerror=()=>{img.remove();};const quantity=document.createElement('span');quantity.className='quantity';quantity.textContent='×'+item.amount.toLocaleString('pt-BR');const label=document.createElement('b');label.textContent=item.name;tile.append(img,quantity,label);if(item.skin&&item.skin!=='0'){const skin=document.createElement('small');skin.textContent='Skin '+item.skin;tile.append(skin);}grid.append(tile);}items.append(grid);
      }
      if(d.updatedAt){const stamp=document.createElement('p');stamp.className='kitSource';stamp.textContent='Itens do servidor • '+new Date(d.updatedAt).toLocaleString('pt-BR')+' • imagens dos itens base do Rust';items.append(stamp);}
    }catch{if(seq!==requestVersion)return;items.textContent='Não foi possível consultar os itens agora. Reabra o pacote para tentar novamente.';}
  }
  document.querySelectorAll('.vipCard .buy').forEach(b=>b.onclick=()=>{product={...b.dataset};document.getElementById('detailName').textContent=product.name;document.getElementById('detailPrice').textContent=Number(product.price).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})+' / 30 dias';document.getElementById('detailArt').src='/api/store/art/vip-'+product.tier;document.getElementById('detailArt').alt=product.name;document.getElementById('detailGift').hidden=product.tier==='duo';document.getElementById('detailNote').textContent=product.tier==='duo'?'Inclui Bronze + Prata + Ouro para você e seu duo. Após pagar, envie o link de resgate ao amigo.':'Compre para sua conta ou envie como presente. O presente é ativado após o amigo entrar com Discord e Steam.';root.classList.add('open');loadKits();});
  const close=()=>{root.classList.remove('open');requestVersion++;};document.getElementById('productClose').onclick=close;root.onclick=e=>{if(e.target===root)close()};document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
  document.getElementById('detailBuy').onclick=()=>{if(!product)return;close();document.dispatchEvent(new CustomEvent('gf:checkout',{detail:{...product,gift:false}}));};
  document.getElementById('detailGift').onclick=()=>{if(!product)return;close();document.dispatchEvent(new CustomEvent('gf:checkout',{detail:{...product,gift:true}}));};
  document.addEventListener('gf:server',loadKits);
  async function gifts(){try{const r=await fetch('/api/store/gift/purchases',{cache:'no-store'});if(!r.ok)return;const rows=await r.json(),container=document.getElementById('giftPurchases');container.replaceChildren();if(!rows.length){container.textContent='Seus presentes e links aparecerão aqui após o pagamento.';return;}const labels={available:'Pronto para enviar',delivering:'Amigo ativando o VIP',redeemed:'Presente resgatado',expired:'Link expirado'};for(const row of rows){const box=document.createElement('div');box.className='purchase';const name=document.createElement('p');name.textContent=row.product+' • Compra #'+row.id+' • '+(labels[row.status]||'Aguardando pagamento');box.append(name);if(row.claimUrl){const input=document.createElement('input');input.value=row.claimUrl;input.readOnly=true;input.setAttribute('aria-label','Link do presente');const button=document.createElement('button');button.textContent='COPIAR PRESENTE';button.onclick=async()=>{try{await navigator.clipboard.writeText(row.claimUrl);button.textContent='COPIADO ✓'}catch{input.select();}};box.append(button,input);}container.append(box);}}catch{}}
  gifts();setInterval(gifts,10000);
})();`;
