import { Router, type IRouter } from "express";
import healthRouter from "./health";
import leaderboardRouter from "./leaderboardV2";
import adminRouter from "./admin";
import communityRouter from "./community.js";
import pwaRouter from "./pwa.js";
import storeRouter from "./store.js";
import revenueView from "../admin/revenueView.js";
import { startPaymentStatusNotifier } from "../admin/paymentStatusNotifier.js";
import { startCardPaymentReconciler } from "./paymentReconciler.js";
import { startSeasonPaymentReconciler } from "./seasonPaymentReconciler.js";
import leaderboardWebhookRouter from "./leaderboardWebhook.js";
import seasonTransportRouter from "./seasonTransport.js";
import seasonRouter from "./season.js";
import seasonIngestionSafeRouter from "./seasonIngestionSafe.js";
import seasonAuditRouter from "./seasonAudit.js";
import seasonSteamRegistrationRepairRouter from "./seasonSteamRegistrationRepair.js";
import seasonSteamSignupRouter from "./seasonSteamSignup.js";
import seasonAdjustedReadRouter from "./seasonAdjustedRead.js";
import seasonBetaIntroRouter from "./seasonBetaIntro.js";
import seasonBetaRouter, { startSeasonBetaController } from "./seasonBeta.js";
import seasonControlRouter from "./seasonControl.js";
import seasonOfficialRegistrationRouter from "./seasonOfficialRegistration.js";
import seasonOfficialEntryGateRouter from "./seasonOfficialEntryGate.js";
import seasonProductionRegistrationRouter from "./seasonProductionRegistration.js";
import seasonEmergencyEmailRepairRouter from "./seasonEmergencyEmailRepair.js";
import seasonEmergencyEmailRepairExecuteRouter from "./seasonEmergencyEmailRepairExecute.js";
import { runSeasonEmailRepairAutorun } from "./seasonEmailRepairAutorun.js";
import rankAssetsRouter from "./rankAssets.js";
import { startSeasonEmailLifecycle } from "./seasonEmailLifecycle.js";
import { startSeasonGameRankSync } from "../bot/seasonGameRankSync.js";

startPaymentStatusNotifier();
startCardPaymentReconciler();
startSeasonPaymentReconciler();
startSeasonBetaController();
startSeasonEmailLifecycle();
startSeasonGameRankSync();
void runSeasonEmailRepairAutorun();

const router: IRouter = Router();
router.use(healthRouter);
router.use(rankAssetsRouter);
router.use(leaderboardRouter);
router.use(leaderboardWebhookRouter);
router.use(seasonEmergencyEmailRepairRouter);
router.use(seasonEmergencyEmailRepairExecuteRouter);
router.use(seasonSteamRegistrationRepairRouter);
router.use(seasonOfficialEntryGateRouter);
router.use(seasonSteamSignupRouter);
router.use(seasonProductionRegistrationRouter);
router.use(seasonBetaIntroRouter);
router.use(seasonOfficialRegistrationRouter);
router.use(seasonControlRouter);
router.use(seasonIngestionSafeRouter);
router.use(seasonTransportRouter);
router.use(seasonAuditRouter);
router.use(seasonAdjustedReadRouter);
router.use(seasonRouter);
router.use(seasonBetaRouter);
router.use(pwaRouter);
router.use("/store", storeRouter);
router.use("/admin", adminRouter);
router.use("/community", communityRouter);
router.use("/finance", revenueView);
export default router;
