import { Router, type IRouter } from "express";
import { db } from "@workspace/db";
import { sql } from "drizzle-orm";
import { logger } from "../lib/logger.js";
const router: IRouter=Router(); const START=1000;
const RANKS=[{name:"Soldado",short:"SLD",level:1,xp:0},{name:"Tenente",short:"TEN",level:2,xp:450},{name:"Major",short:"MAJ",level:3,xp:900},{name:"Marechal",short:"MAR",level:4,xp:1350},{name:"General Frio",short:"GFR",level:5,xp:1800}];
const num=(v:any,f=0)=>Number.isFinite(Number(v))?Number(v):f, integer=(v:any)=>Math.trunc(num(v)), text=(v:any,m=1000)=>String(v??"").slice(0,m);
function xpFromMmr(v:any){return Math.max(0,Math.round((num(v,START)-START)*9));} function rankForXp(xp:number){return [...RANKS].reverse().find(r=>xp>=r.xp)||RANKS[0];}
function publicPlayer(row:any,position?:number){const xp=xpFromMmr(row.effective_mmr??row.mmr);const rank=rankForXp(xp);const next=RANKS.find(r=>r.level===rank.level+1)||null;return{position:position??integer(row.position),steam_id:text(row.steam_id,32),player_name:text(row.player_name,128),patente:rank.name,patente_codigo:rank.short,patente_nivel:rank.level,patente_maxima:rank.level===5,xp,experiencia:xp,proxima_patente:next?.name??null,xp_proxima_patente:next?.xp??null,xp_faltante:next?Math.max(0,next.xp-xp):0,progresso_percentual:next?Math.max(0,Math.min(100,Math.round(((xp-rank.xp)/(next.xp-rank.xp))*100))):100,season_scored:Boolean(row.season_scored),kills:integer(row.kills),deaths:integer(row.deaths),headshots:integer(row.headshots),assists:integer(row.assists),raids_participated:integer(row.raids_participated),raids_defended:integer(row.raids_defended),bradley_participations:integer(row.bradley_participations),heli_participations:integer(row.heli_participations),crates_hacked:integer(row.crates_hacked),updated_at:row.updated_at};}
async function source(requested:number){const r:any=await db.execute(sql`SELECT p.season_number,MAX(p.updated_at) last_update,MAX(s.status) status FROM season_players p LEFT JOIN seasons s ON s.season_number=p.season_number GROUP BY p.season_number ORDER BY CASE WHEN MAX(s.status)='active' THEN 0 ELSE 1 END,MAX(p.updated_at) DESC NULLS LAST`);return integer(r?.rows?.[0]?.season_number||requested);}
function universe(sn:number){return sql`WITH a AS(SELECT steam_id,COALESCE(SUM(final_value),0) delta FROM season_transactions WHERE season_number=${sn} AND category='admin' GROUP BY steam_id),sd AS(SELECT * FROM season_players WHERE season_number=${sn}),u AS(SELECT ps.steam_id,COALESCE(sd.player_name,ps.player_name) player_name,COALESCE(sd.mmr,${START}) mmr,COALESCE(sd.kills,ps.kills,0) kills,COALESCE(sd.deaths,ps.deaths,0) deaths,COALESCE(sd.headshots,ps.headshots,0) headshots,COALESCE(sd.assists,0) assists,COALESCE(sd.raids_participated,0) raids_participated,COALESCE(sd.raids_defended,0) raids_defended,COALESCE(sd.bradley_participations,0) bradley_participations,COALESCE(sd.heli_participations,0) heli_participations,COALESCE(sd.crates_hacked,0) crates_hacked,COALESCE(sd.updated_at,ps.updated_at) updated_at,(sd.steam_id IS NOT NULL) season_scored FROM player_stats ps LEFT JOIN sd ON sd.steam_id=ps.steam_id UNION ALL SELECT sd.steam_id,sd.player_name,sd.mmr,sd.kills,sd.deaths,sd.headshots,sd.assists,sd.raids_participated,sd.raids_defended,sd.bradley_participations,sd.heli_participations,sd.crates_hacked,sd.updated_at,true FROM sd LEFT JOIN player_stats ps ON ps.steam_id=sd.steam_id WHERE ps.steam_id IS NULL),r AS(SELECT u.*,u.mmr+COALESCE(a.delta,0) effective_mmr,ROW_NUMBER() OVER(ORDER BY u.mmr+COALESCE(a.delta,0) DESC,u.kills DESC,u.updated_at ASC NULLS LAST) position FROM u LEFT JOIN a ON a.steam_id=u.steam_id) SELECT * FROM r`;}
router.get("/season/:number",async(req,res,next)=>{if(!/^\d+$/.test(String(req.params.number||"")))return next();try{const sn=Math.max(1,integer(req.params.number)||1),src=await source(sn);const rr:any=await db.execute(sql`${universe(src)} ORDER BY position ASC`);const ranking=(rr?.rows||[]).map((r:any,i:number)=>publicPlayer(r,i+1));res.setHeader("Cache-Control","no-store");return void res.json({ok:true,season_number:sn,data_source_season_number:src,total_players:ranking.length,methodology:{metric:"Experiência",description:"A Experiência (XP) representa publicamente a evolução do jogador. O cálculo competitivo interno continua protegido."},ranks:RANKS,general_count:ranking.filter((p:any)=>p.patente_maxima).length,ranking});}catch(error){logger.error({error},"season XP ranking failed");return void res.status(500).json({error:"Falha ao carregar ranking da Season."});}});
router.get("/season/:number/player/:steamId",async(req,res,next)=>{const id=text(req.params.steamId,32);if(!/^7656119\d{10}$/.test(id))return next();try{const sn=Math.max(1,integer(req.params.number)||1),src=await source(sn);const pr:any=await db.execute(sql`${universe(src)} WHERE steam_id=${id} LIMIT 1`);const tx:any=await db.execute(sql`SELECT category,event_type,CASE WHEN final_value>0 THEN 'gain' WHEN final_value<0 THEN 'loss' ELSE 'neutral' END direction,ROUND(final_value*9)::int xp_change,details,happened_at FROM season_transactions WHERE season_number=${src} AND steam_id=${id} ORDER BY happened_at DESC LIMIT 100`);return void res.json({ok:true,season_number:sn,player:pr?.rows?.[0]?publicPlayer(pr.rows[0]):null,transactions:tx?.rows||[],ranks:RANKS});}catch(error){logger.error({error},"season XP player failed");return void res.status(500).json({error:"Falha ao carregar jogador da Season."});}}); export default router;
