function esc(value: unknown): string {
  return String(value ?? "").replace(/[&<>\"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c] || c));
}

export function renderSeasonPage(seasonNumber: number): string {
  const n = Math.max(1, Math.trunc(Number(seasonNumber) || 1));
  return `<!doctype html>
<html lang="pt-BR">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover" />
<meta name="theme-color" content="#080b12" />
<title>Season ${n} • Guerra Fria Rust</title>
<style>
:root{--bg:#070910;--panel:#0e121c;--panel2:#121827;--line:#252d40;--text:#f5f7fb;--muted:#9099aa;--red:#ef4444;--orange:#f59e0b;--cyan:#22d3ee;--green:#22c55e;--violet:#8b5cf6}
*{box-sizing:border-box}html{background:var(--bg)}body{margin:0;background:radial-gradient(circle at 50% -20%,#263149 0,#101521 28%,var(--bg) 65%);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;min-height:100vh}
a{color:inherit}.wrap{width:min(1180px,calc(100% - 28px));margin:auto}.topbar{height:72px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #ffffff0d}.brand{display:flex;gap:12px;align-items:center;font-weight:900;letter-spacing:.04em}.mark{width:38px;height:38px;border-radius:10px;display:grid;place-items:center;background:linear-gradient(135deg,#dc2626,#7f1d1d);box-shadow:0 8px 28px #ef44443d}.nav{display:flex;gap:8px}.nav a{text-decoration:none;color:var(--muted);padding:9px 12px;border-radius:9px;font-size:13px;font-weight:700}.nav a:hover{background:#ffffff0a;color:white}.hero{padding:58px 0 30px;text-align:center}.eyebrow{font-size:12px;color:#fca5a5;font-weight:900;letter-spacing:.18em;text-transform:uppercase}.hero h1{margin:9px 0 8px;font-size:clamp(34px,7vw,72px);line-height:.98;letter-spacing:-.05em}.hero h1 span{background:linear-gradient(90deg,#fff,#aab3c5);-webkit-background-clip:text;color:transparent}.hero p{color:var(--muted);max-width:680px;margin:14px auto 0;line-height:1.6}.statusline{margin:22px auto 0;display:inline-flex;align-items:center;gap:9px;border:1px solid var(--line);background:#0a0e16cc;padding:9px 14px;border-radius:999px;color:#c5ccda;font-size:12px}.dot{width:8px;height:8px;border-radius:50%;background:var(--green);box-shadow:0 0 12px var(--green)}
.podium{display:grid;grid-template-columns:1fr 1.12fr 1fr;gap:14px;align-items:end;margin:26px auto 36px;max-width:900px}.pod{border:1px solid var(--line);background:linear-gradient(180deg,#141b2a,#0c1019);border-radius:18px;padding:22px 16px;text-align:center;position:relative;overflow:hidden;min-height:176px;display:flex;flex-direction:column;justify-content:center}.pod.first{min-height:214px;border-color:#a1620766;background:linear-gradient(180deg,#271d0c,#11131b)}.pod .rank{font-size:13px;color:var(--muted);font-weight:800}.pod .name{font-weight:900;font-size:18px;margin-top:8px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.pod .mmr{font-size:28px;font-weight:950;margin-top:5px}.pod .sub{font-size:11px;color:var(--muted);margin-top:5px}.crown{font-size:31px;margin-bottom:4px}.emptyPod{opacity:.35}
.summary{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin-bottom:18px}.stat{background:#0d121c;border:1px solid var(--line);border-radius:13px;padding:14px}.stat b{display:block;font-size:19px}.stat span{font-size:10px;text-transform:uppercase;letter-spacing:.09em;color:var(--muted)}
.card{border:1px solid var(--line);background:#0b0f18dd;border-radius:18px;overflow:hidden;margin-bottom:40px}.cardHead{padding:17px 18px;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid var(--line)}.cardHead h2{font-size:15px;margin:0}.cardHead .small{font-size:11px;color:var(--muted)}.tableWrap{overflow:auto}.rankTable{width:100%;border-collapse:collapse;min-width:910px}.rankTable th{padding:12px 13px;text-align:right;font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:#737d90;background:#0b1019;position:sticky;top:0}.rankTable th:nth-child(1),.rankTable th:nth-child(2){text-align:left}.rankTable td{padding:13px;border-top:1px solid #ffffff0a;text-align:right;font-variant-numeric:tabular-nums;font-size:13px}.rankTable tr:hover td{background:#ffffff05}.rankTable td:nth-child(1){width:56px;text-align:left;color:#818b9f;font-weight:900}.rankTable td:nth-child(2){text-align:left;max-width:220px}.player{font-weight:850;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.steam{color:#596275;font-size:10px;margin-top:2px}.mmrCell{font-weight:950;font-size:15px;color:white}.pill{font-size:10px;font-weight:800;border-radius:999px;padding:5px 7px;background:#ffffff0a}.pvp{color:#fb7185}.farm{color:#4ade80}.build{color:#fbbf24}.event{color:#67e8f9}.footer{text-align:center;color:#596275;font-size:11px;padding:15px 0 42px}.loading{padding:60px;text-align:center;color:var(--muted)}
@media(max-width:760px){.nav a:nth-child(1){display:none}.hero{padding-top:38px}.podium{gap:7px}.pod{padding:14px 8px;min-height:150px}.pod.first{min-height:180px}.pod .name{font-size:13px}.pod .mmr{font-size:20px}.summary{grid-template-columns:repeat(2,1fr)}.summary .stat:last-child{grid-column:span 2}.wrap{width:min(100% - 18px,1180px)}}
</style>
</head>
<body>
<header class="topbar"><div class="wrap" style="display:flex;align-items:center;justify-content:space-between"><div class="brand"><div class="mark">GF</div><div>GUERRA FRIA</div></div><nav class="nav"><a href="/">Início</a><a href="/leaderboard">Leaderboard</a><a href="/season${n}" style="background:#ffffff0a;color:white">Season ${n}</a></nav></div></header>
<main class="wrap">
<section class="hero"><div class="eyebrow">Season Premiada</div><h1><span>SEASON ${n}</span></h1><p>Ranking mensal por MMR. PvP e raids, farm, construção e eventos contribuem para a classificação — premiando quem joga Rust de forma completa.</p><div class="statusline"><span class="dot" id="statusDot"></span><span id="seasonStatus">Carregando ranking...</span></div></section>
<section class="podium" id="podium"><div class="pod emptyPod">—</div><div class="pod first emptyPod">—</div><div class="pod emptyPod">—</div></section>
<section class="summary" id="summary"></section>
<section class="card"><div class="cardHead"><h2>Classificação geral</h2><span class="small" id="updated">Atualizando...</span></div><div class="tableWrap"><div class="loading" id="loading">Buscando dados da Season...</div><table class="rankTable" id="table" hidden><thead><tr><th>#</th><th>Jogador</th><th>MMR</th><th>PvP + Raid</th><th>Farm</th><th>Construção</th><th>Eventos</th><th>K</th><th>D</th><th>K/D</th><th>HS</th><th>Raids</th></tr></thead><tbody id="rows"></tbody></table></div></section>
</main><footer class="footer">GUERRA FRIA RUST • Ranking atualizado automaticamente pelo servidor</footer>
<script>
const SEASON=${n};
const fmt=(v,d=1)=>Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:d,minimumFractionDigits:d});
const ints=v=>Number(v||0).toLocaleString('pt-BR');
const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function podiumCard(p,pos){if(!p)return '<div class="pod '+(pos===1?'first ':'')+'emptyPod">Sem jogador</div>';const icons={1:'👑',2:'🥈',3:'🥉'};return '<div class="pod '+(pos===1?'first':'')+'"><div class="crown">'+icons[pos]+'</div><div class="rank">#'+pos+'</div><div class="name">'+escapeHtml(p.player_name)+'</div><div class="mmr">'+fmt(p.mmr,2)+'</div><div class="sub">MMR • '+ints(p.kills)+' kills</div></div>'}
function render(data){const r=data.ranking||[],season=data.season||{};document.getElementById('seasonStatus').textContent=(season.status==='finished'?'Season encerrada':'Season em andamento')+' • '+r.length+' jogadores no ranking';if(season.status==='finished')document.getElementById('statusDot').style.background='#94a3b8';document.getElementById('podium').innerHTML=podiumCard(r[1],2)+podiumCard(r[0],1)+podiumCard(r[2],3);const totals={players:r.length,kills:r.reduce((a,p)=>a+Number(p.kills||0),0),raids:r.reduce((a,p)=>a+Number(p.raids_participated||0),0),farm:r.reduce((a,p)=>a+Number(p.farm_mmr||0),0),top:r[0]?.mmr||1000};document.getElementById('summary').innerHTML='<div class="stat"><b>'+ints(totals.players)+'</b><span>Jogadores</span></div><div class="stat"><b>'+ints(totals.kills)+'</b><span>Kills registradas</span></div><div class="stat"><b>'+ints(totals.raids)+'</b><span>Raids</span></div><div class="stat"><b>'+fmt(totals.farm,1)+'</b><span>MMR de farm</span></div><div class="stat"><b>'+fmt(totals.top,1)+'</b><span>MMR do líder</span></div>';document.getElementById('rows').innerHTML=r.map(p=>{const kd=Number(p.deaths)>0?Number(p.kills)/Number(p.deaths):Number(p.kills);const hs=Number(p.kills)>0?Number(p.headshots)/Number(p.kills)*100:0;return '<tr><td>#'+p.position+'</td><td><div class="player">'+escapeHtml(p.player_name)+'</div><div class="steam">'+escapeHtml(p.steam_id)+'</div></td><td class="mmrCell">'+fmt(p.mmr,2)+'</td><td><span class="pill pvp">'+fmt(p.pvp_raid_mmr)+'</span></td><td><span class="pill farm">'+fmt(p.farm_mmr)+'</span></td><td><span class="pill build">'+fmt(p.building_mmr)+'</span></td><td><span class="pill event">'+fmt(p.event_mmr)+'</span></td><td>'+ints(p.kills)+'</td><td>'+ints(p.deaths)+'</td><td>'+fmt(kd,2)+'</td><td>'+fmt(hs,1)+'%</td><td>'+ints(p.raids_participated)+'</td></tr>'}).join('');document.getElementById('loading').hidden=true;document.getElementById('table').hidden=false;document.getElementById('updated').textContent='Atualizado agora';}
async function load(){try{const res=await fetch('/api/season/'+SEASON+'?limit=200',{cache:'no-store'});if(!res.ok)throw new Error('HTTP '+res.status);render(await res.json())}catch(e){document.getElementById('loading').textContent='Não foi possível carregar o ranking agora.';document.getElementById('seasonStatus').textContent='Temporariamente indisponível';document.getElementById('statusDot').style.background='#ef4444'}}
load();setInterval(load,15000);
</script>
</body></html>`;
}

export const seasonPagePlaceholder = esc;
