import { Router, type IRouter } from "express";
import { getCommunitySession } from "../admin/communitySession.js";

const router: IRouter = Router();

function shell(body: string) {
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#08090b"><title>Season Beta • Guerra Fria</title><style>
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:#08090b;color:#f7f7f5;font-family:Inter,system-ui,-apple-system,sans-serif}body{background:radial-gradient(circle at 50% -10%,#46160f,#171012 28%,#08090b 62%)}.wrap{width:min(760px,calc(100% - 24px));margin:auto;padding:24px 0 60px}.back,.btn{display:inline-flex;align-items:center;justify-content:center;text-decoration:none;border-radius:12px;padding:13px 16px;font-weight:950;font-size:12px}.back{border:1px solid #303641;color:#fff;background:#11141a}.hero{padding:38px 0 18px}.ey{font-size:10px;font-weight:1000;letter-spacing:.18em;color:#fca5a5}.hero h1{font-size:clamp(38px,8vw,66px);line-height:.95;letter-spacing:-.05em;margin:8px 0 12px}.hero p{color:#a0a7b2;line-height:1.65}.alert{border:1px solid #ef444477;background:linear-gradient(135deg,#351012,#180d10);border-radius:20px;padding:20px;box-shadow:0 20px 60px #0006}.alert h2{margin:0 0 8px;font-size:22px;color:#fff}.alert p{color:#e1c6c8;line-height:1.6;font-size:13px}.items{display:grid;gap:9px;margin:16px 0}.item{display:grid;grid-template-columns:34px 1fr;gap:10px;align-items:start;border:1px solid #36313a;background:#111217;border-radius:13px;padding:12px}.item i{font-style:normal;font-size:22px}.item b{display:block;font-size:12px}.item small{display:block;color:#9ea4ad;font-size:10px;line-height:1.5;margin-top:3px}.dates{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin:14px 0}.date{border:1px solid #343a44;background:#101216;border-radius:13px;padding:13px}.date b{display:block}.date small{display:block;color:#9aa0aa;margin-top:4px}.btn{width:100%;border:1px solid #f87171;background:linear-gradient(135deg,#ef4444,#b91c1c);color:#fff;box-shadow:0 12px 30px #ef444426}.secondary{background:#15181e;border-color:#414754;box-shadow:none}.check{display:flex;gap:10px;align-items:flex-start;color:#d4d8df;font-size:12px;line-height:1.55;margin:16px 0}.msg{font-size:12px;color:#fca5a5;margin-top:12px}.ok{color:#86efac}.actions{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:14px}@media(max-width:600px){.dates,.actions{grid-template-columns:1fr}.wrap{padding-top:14px}.hero{padding-top:26px}}
</style></head><body><main class="wrap">${body}</main></body></html>`;
}

router.get("/season/:number/inscricao", (req, res, next) => {
  const season = Math.max(1, Math.trunc(Number(req.params.number) || 1));
  if (season !== 1) return next();
  const session = getCommunitySession(req);
  const continuing = String(req.query.continue || "") === "1";

  if (!session) {
    const body = `<a class="back" href="/season1">← Voltar para Season</a><section class="hero"><div class="ey">🧪 BETA SEASON TESTER • GUERRA FRIA</div><h1>Antes de se inscrever</h1><p>Leia este aviso antes de conectar sua conta do Discord.</p></section><section class="alert"><h2>⚠️ Esta fase não tem premiação</h2><p>A Season atual é exclusivamente um teste público. Ela existe para a administração medir o sistema, encontrar bugs e fazer os ajustes necessários antes da competição oficial.</p><div class="items"><div class="item"><i>🏆</i><div><b>Sem dinheiro ou VIP nesta Beta</b><small>A colocação desta semana não gera qualquer premiação oficial.</small></div></div><div class="item"><i>⚙️</i><div><b>MMR e patentes podem mudar</b><small>Pesos, fórmulas, limites e classificações poderão ser rebalanceados durante os testes.</small></div></div><div class="item"><i>🧹</i><div><b>Dados podem ser corrigidos ou zerados</b><small>Se um bug afetar a medição, a equipe poderá recalcular ou limpar os resultados do Beta.</small></div></div><div class="item"><i>🎖️</i><div><b>Cargo Season Tester</b><small>Após concluir a inscrição, você receberá automaticamente o cargo de testador no Discord.</small></div></div></div><div class="dates"><div class="date"><b>🧪 Beta</b><small>28/08/2026 • 18:30</small></div><div class="date"><b>🏆 Season oficial</b><small>04/09/2026 • após o wipe das 18:30</small></div></div><a class="btn" href="/api/admin/auth/login?target=season">CONTINUAR COM A INSCRIÇÃO →</a></section>`;
    res.setHeader("Cache-Control", "no-store");
    return void res.status(200).type("html").send(shell(body));
  }

  if (!continuing) return next();
  const safeName = String(session.username || "Jogador").replace(/[<>&"']/g, "");
  const body = `<a class="back" href="/season1">← Voltar para Season</a><section class="hero"><div class="ey">✅ DISCORD CONECTADO</div><h1>Confirmar inscrição</h1><p>Conta conectada como <strong>${safeName}</strong>. Falta somente confirmar sua participação no teste.</p></section><section class="alert"><h2>🧪 Confirmação de Season Tester</h2><p>Ao confirmar, você reconhece que esta fase é somente de testes, sem premiação, e autoriza a aplicação automática do cargo <strong>Season Tester</strong> no Discord.</p><label class="check"><input id="accept" type="checkbox"><span>Li o <a href="/api/season/1/regras" style="color:#fca5a5">Regulamento da Season</a> e entendo que os resultados desta Beta podem ser ajustados, recalculados ou zerados antes da Season oficial.</span></label><div class="actions"><a class="btn secondary" href="/api/season/1/regras">VER REGRAS</a><button class="btn" id="send" type="button">CONFIRMAR INSCRIÇÃO</button></div><div id="msg" class="msg"></div></section><script>document.getElementById('send').onclick=async function(){var b=this,a=document.getElementById('accept'),m=document.getElementById('msg');if(!a.checked){m.textContent='Você precisa aceitar o regulamento e reconhecer que esta é uma fase de teste.';return}b.disabled=true;m.textContent='Registrando inscrição e aplicando o cargo Season Tester...';try{var r=await fetch('/api/season/1/inscricao',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({accept:true})});var j=await r.json();if(!r.ok)throw new Error(j.error||'Falha na inscrição');m.className='msg ok';m.textContent=j.message||'Inscrição concluída.';setTimeout(function(){location.href='/season1'},1200)}catch(e){m.className='msg';m.textContent=e.message;b.disabled=false}}</script>`;
  res.setHeader("Cache-Control", "no-store");
  return void res.status(200).type("html").send(shell(body));
});

export default router;
