import {test} from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {createRequire} from 'node:module';
import {resolve} from 'node:path';
const state=globalThis.__vipServerTests={calls:[],inserts:[],updates:[],rows:[]};
state.db={select:()=>({from:()=>({where:()=>{const rows=state.rows.shift()||[];return {then:(yes,no)=>Promise.resolve(rows).then(yes,no),limit:async()=>rows};}})}),insert:()=>({values:async x=>state.inserts.push(x)}),update:()=>({set:x=>({where:async()=>state.updates.push(x)})})};
const mocks={'@workspace/db':'export const db=globalThis.__vipServerTests.db;export const vipSubscriptionsTable={};export const pool={query:async()=>{throw Error("Unexpected purchase SQL");}};', 'serverRcon.js':'export const executeServerRcon=async(server,command)=>{globalThis.__vipServerTests.calls.push({server,command});return "confirmed";};','logger.js':'export const logger={info(){},warn(){},error(){}};'};
const b=await build({entryPoints:[resolve('src/bot/vip.ts')],bundle:true,platform:'node',format:'cjs',write:false,plugins:[{name:'mocks',setup(p){p.onResolve({filter:/.*/},a=>{const key=Object.keys(mocks).find(k=>a.path===k||a.path.endsWith('/'+k));if(key)return {path:key,namespace:'mock'};});p.onLoad({filter:/.*/,namespace:'mock'},a=>({contents:mocks[a.path]}));}}]});
const mod={exports:{}};new Function('require','module','exports',b.outputFiles[0].text)(createRequire(import.meta.url),mod,mod.exports);const vip=mod.exports;
function reset(){state.calls=[];state.inserts=[];state.updates=[];state.rows=[];delete process.env.DISCORD_VIP_ROLE_ID;delete process.env.DISCORD_GUILD_ID;for(const prefix of ['', 'TRIO_']){process.env[prefix+'VIP_BRONZE_GRANT_CMD']='oxide.usergroup add {steamId} vip1';process.env[prefix+'VIP_BRONZE_REVOKE_CMD']='oxide.usergroup remove {steamId} vip1';}}
test('manual grants target chosen server and retain validity',async()=>{reset();await vip.grantVip({discordUserId:'manual',steamId:'sample',tier:'bronze',durationDays:30,source:'manual:trio',client:{}});assert.deepEqual(state.calls,[{server:'trio',command:'c.usergroup add sample vip1'}]);assert.equal(state.inserts[0].expiresAt-state.inserts[0].startsAt,30*86400000);});
test('expiry revokes Trio despite another Duo subscription, preserving expiry date',async()=>{reset();state.rows=[[{id:1,source:'manual:trio'},{id:2,source:'purchase'}],[{id:1,source:'manual:trio'}]];await vip.revokeVip({subscriptionId:1,tier:'bronze',steamId:'sample',discordUserId:'manual',client:{},reason:'expired'});assert.deepEqual(state.calls,[{server:'trio',command:'c.usergroup remove sample vip1'}]);assert.equal('expiresAt' in state.updates[0],false);});
test('another subscription on the same server preserves the game group',async()=>{reset();state.rows=[[{id:1,source:'manual:trio'},{id:2,source:'manual:trio'}],[{id:1,source:'manual:trio'}]];await vip.revokeVip({subscriptionId:1,tier:'bronze',steamId:'sample',discordUserId:'manual',client:{},reason:'expired'});assert.equal(state.calls.length,0);});
test('Discord failure rolls back on same server without recording delivery',async()=>{reset();process.env.DISCORD_VIP_ROLE_ID='role';process.env.DISCORD_GUILD_ID='guild';await assert.rejects(vip.grantVip({discordUserId:'user',steamId:'sample',tier:'bronze',durationDays:30,source:'manual:trio',client:{guilds:{fetch:async()=>{throw Error('unavailable')}}}}));assert.deepEqual(state.calls.map(c=>c.server),['trio','trio']);assert.equal(state.inserts.length,0);});
test('Duo restoration grants existing membership without changing dates or adding subscription',async()=>{reset();const sub={id:9,steamId:'76561199999999999',vipTier:'bronze',discordUserId:'manual',source:'purchase',expiresAt:new Date(Date.now()+86400000),gameVipRemoved:false};state.rows=[[sub],[sub]];assert.equal(await vip.reapplyDuoVip(9,{}),true);assert.deepEqual(state.calls,[{server:'solo-duo',command:'c.usergroup add 76561199999999999 vip1'}]);assert.equal(state.inserts.length,0);assert.equal(state.updates.length,0);});
test('Duo restoration excludes expired, removed and Trio entitlements',async()=>{reset();for(const sub of [{expiresAt:new Date(0),gameVipRemoved:false,source:'purchase'},{expiresAt:new Date(Date.now()+86400000),gameVipRemoved:true,source:'purchase'},{expiresAt:new Date(Date.now()+86400000),gameVipRemoved:false,source:'manual:trio'}]){state.rows=[[{id:9,...sub}]];assert.equal(await vip.reapplyDuoVip(9,{}),false);}assert.equal(state.calls.length,0);assert.equal(state.inserts.length,0);assert.equal(state.updates.length,0);});
